[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pyarest"
version = "0.0.1"
description = "AREST engine on Python's lambda"
requires-python = ">=3.14"

[tool.setuptools.packages.find]
where = ["python"]
include = ["pyarest*"]

[tool.pytest.ini_options]
pythonpath = ["python"]
testpaths = ["tests"]
