// crates/arest-kernel/build.rs
//
// Emits `$OUT_DIR/ui_assets.rs` with a static table of the ui.do
// static bundle (`apps/ui.do/dist/`). Each entry is
// `(http_path, &[u8])` where `http_path` is the leading-slash URL
// (e.g. `/index.html`, `/assets/index-DjXaD7eJ.js`) and the byte
// slice comes from `include_bytes!` pointed at an absolute path on
// the build machine.
//
// When `apps/ui.do/dist/` is missing (fresh clone, tests not run,
// Docker context that didn't copy the bundle), the table is empty.
// `src/assets.rs` falls through to `None` in that case and the
// handler keeps serving the legacy plaintext banner.
//
// Also emits `$OUT_DIR/doom_assets.rs` with the baked Doom-WASM blob
// (`doom_assets/doom.wasm`) as a `pub static DOOM_WASM: &[u8]` for
// the doom host-shim in src/doom.rs (#372). Follows the same
// include_bytes!-of-canonicalized-absolute-path pattern as the UI
// bundle so Windows/Linux both resolve the literal identically.
// Absent binary -> `DOOM_WASM: &[u8] = &[]` so the crate still
// compiles on a fresh clone; callers check `DOOM_WASM.is_empty()`.
//
// Also emits `$OUT_DIR/doom_wad.rs` with the baked Doom IWAD blob
// (`doom_assets/doom1.wad`) as a `pub static DOOM_WAD: &[u8]` for
// the doom host-shim's `wad_sizes` / `read_wads` trampolines (#383).
// Same absent-file fallback as `DOOM_WASM`: missing WAD -> empty slice,
// at which point `wad_sizes` falls through to returning `(0, 0)` and
// the baked `doom.wasm` guest uses its internally-embedded Shareware
// WAD. The IWAD is the id Software DOOM 1 Shareware v1.9 WAD,
// redistributable gratis per id's 1993 shareware license — see
// doom_assets/README.md for provenance and license notes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Repo layout: crates/arest-kernel/ → ../../apps/ui.do/dist/
    let dist = manifest_dir
        .join("..").join("..")
        .join("apps").join("ui.do").join("dist");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    // #580: the bake is now gated on `feature = "ui-bundle"`. When the
    // feature is OFF (default — including the `server` profile), the
    // emitted `UI_ASSETS` table is empty; `system::init`'s
    // `seed_ui_bundle_cells` step is a no-op, the runtime asset
    // handler in `arest_http_handler` walks an empty cell-graph, and
    // every static-asset request falls through to 404. When the
    // feature is ON, the table is non-empty and the boot-time seeder
    // wraps each `(path, bytes)` entry into a File cell so the
    // handler reads from the cell graph rather than the static table.
    //
    // This keeps the kernel binary lean by default (#580) and sets up
    // the handoff for #581 — the boot-time wrap is what #581 will
    // replace with a runtime load (HTTP fetch / freeze blob / disk
    // image) once the ui.do source moves out of this repo.
    //
    // Pre-#580 the gate was `CARGO_FEATURE_SERVER` (skip on server
    // profile, bake otherwise). The new shape inverts the polarity:
    // skip-by-default, opt-in via `--features ui-bundle`. Operators
    // wanting the previous default of "bake unless server" should
    // pass `--features ui-bundle` explicitly; the Dockerfile.uefi
    // image build will be updated alongside this change.
    let ui_bundle_feature = env::var_os("CARGO_FEATURE_UI_BUNDLE").is_some();
    if !ui_bundle_feature {
        println!(
            "cargo:warning=ui-bundle feature off: skipping ui.do bundle bake (#580)",
        );
    } else if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
        entries.sort_by(|a, b| a.0.cmp(&b.0));
    } else {
        println!(
            "cargo:warning=apps/ui.do/dist not found at {} — kernel will boot without the UI bundle",
            dist.display(),
        );
    }
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_UI_BUNDLE");

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str("pub static UI_ASSETS: &[(&str, &[u8])] = &[\n");
    for (http_path, fs_path) in &entries {
        let abs = abs_include_path(fs_path);
        out.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            http_path, abs,
        ));
    }
    out.push_str("];\n");

    let out_path = out_dir.join("ui_assets.rs");
    fs::write(&out_path, out).expect("write ui_assets.rs");

    // --- doom.wasm (#372) ---------------------------------------------
    // doom_assets/doom.wasm is staged out-of-band (downloaded from
    // github.com/jacobenget/doom.wasm releases or built from source —
    // see doom_assets/README.md for provenance). If the file is
    // absent (fresh clone, Docker context that didn't copy it, or
    // user-declined GPL inclusion), emit an empty slice so the crate
    // still compiles and `DOOM_WASM.is_empty()` reports the absence
    // to runtime callers.
    let doom_wasm = manifest_dir.join("doom_assets").join("doom.wasm");
    let mut doom_out = String::new();
    doom_out.push_str("// Generated by build.rs — do not edit.\n");
    // `#[allow(dead_code)]` guards against the pre-#376 state where
    // `doom_bin::DOOM_WASM` is declared but no caller has wired up
    // `wasmi::Module::new(&engine, DOOM_WASM)` yet. Matches the
    // scaffold-first discipline the rest of the doom host-shim uses
    // (src/doom.rs's `bind_doom_imports` is similarly unreferenced
    // from kernel_run today).
    doom_out.push_str("#[allow(dead_code)]\n");
    if doom_wasm.is_file() {
        let abs = abs_include_path(&doom_wasm);
        doom_out.push_str(&format!(
            "pub static DOOM_WASM: &[u8] = include_bytes!(\"{}\");\n",
            abs,
        ));
        println!("cargo:rerun-if-changed={}", doom_wasm.display());
    } else {
        println!(
            "cargo:warning=doom_assets/doom.wasm not found at {} — DOOM_WASM will be empty",
            doom_wasm.display(),
        );
        doom_out.push_str("pub static DOOM_WASM: &[u8] = &[];\n");
    }
    let doom_out_path = out_dir.join("doom_assets.rs");
    fs::write(&doom_out_path, doom_out).expect("write doom_assets.rs");

    // --- doom1.wad (#383) --------------------------------------------
    // Parallels the doom.wasm bake above. `doom_assets/doom1.wad` is
    // the id Software DOOM 1 Shareware v1.9 IWAD (4,196,020 bytes,
    // sha256 1d7d43be501e67d927e415e0b8f3e29c3bf33075e859721816f652a526cac771
    // — see doom_assets/README.md for the source URL and license
    // note). When present, the `DOOM_WAD` byte slice is the WAD's
    // contents; `KernelDoomHost::wad_sizes` reports its length and
    // `read_wads` copies it into guest memory so Doom loads the real
    // IWAD instead of falling back to the copy embedded in the baked
    // doom.wasm blob.
    //
    // Absent WAD -> empty slice, and the shim's `wad_sizes` short-
    // circuits to `(0, 0)` which makes doom.wasm use its internally-
    // embedded Shareware WAD (per doom_wasm.h "If numberOfWads remains
    // 0, Doom loads shareware WAD"). This keeps fresh clones compiling
    // without the WAD staged — same contract as DOOM_WASM.
    let doom_wad = manifest_dir.join("doom_assets").join("doom1.wad");
    let mut wad_out_src = String::new();
    wad_out_src.push_str("// Generated by build.rs — do not edit.\n");
    // `#[allow(dead_code)]` mirrors `DOOM_WASM`'s guard: the WAD
    // byte slice is only reached from the wasmi-gated host-shim
    // (`KernelDoomHost::wad_sizes` / `read_wads`), which is itself
    // not yet invoked from `kernel_run` under the pre-#376 state.
    // Dropping the allow is a one-line follow-up once the Doom
    // module actually instantiates.
    wad_out_src.push_str("#[allow(dead_code)]\n");
    if doom_wad.is_file() {
        let abs = abs_include_path(&doom_wad);
        wad_out_src.push_str(&format!(
            "pub static DOOM_WAD: &[u8] = include_bytes!(\"{}\");\n",
            abs,
        ));
        println!("cargo:rerun-if-changed={}", doom_wad.display());
    } else {
        println!(
            "cargo:warning=doom_assets/doom1.wad not found at {} — DOOM_WAD will be empty",
            doom_wad.display(),
        );
        wad_out_src.push_str("pub static DOOM_WAD: &[u8] = &[];\n");
    }
    let wad_out_path = out_dir.join("doom_wad.rs");
    fs::write(&wad_out_path, wad_out_src).expect("write doom_wad.rs");

    // --- Slint UI compile (#436 / #452) ------------------------------
    //
    // Track QQQ #452 follow-up to MMM's #436 (commit `0b32b17`):
    // `slint-build` is now an unconditional `[build-dependencies]`
    // entry (see Cargo.toml), so the build script can finally invoke
    // the slint compiler for real. That replaces MMM's
    // `slint::slint!{}` proc-macro workaround in
    // `arch/uefi/slint_backend.rs`, which couldn't reach
    // `EmbedForSoftwareRenderer` (the proc-macro path doesn't enable
    // the `software-renderer` feature on `i-slint-compiler`) and
    // therefore couldn't bake bitmap fonts at compile time.
    //
    // Compile entry: `ui/AppShell.slint`. AppShell's transitive
    // imports (theme.slint + every component under ui/components/)
    // get pulled in by the slint compiler's import resolver; we don't
    // need to enumerate them. slint-build emits one
    // `cargo:rerun-if-changed=` line per .slint file it touches +
    // one per font/image resource it embeds, so we don't need a
    // separate watch loop for those either.
    //
    // `EmbedResourcesKind::EmbedForSoftwareRenderer` is the no_std-
    // friendly font path: the compiler pre-rasterises glyph atlases
    // (or SDF, behind the `sdf-fonts` feature) for every character +
    // size + weight referenced by the design system, embeds them as
    // `BitmapFont` statics, and emits
    // `Renderer::register_bitmap_font(&BITMAP_FONT_DATA)` calls into
    // each component's init code. `register_bitmap_font` is the only
    // font registration entry point on `i_slint_core::renderer::Renderer`
    // that does NOT require the `systemfonts` feature (which would
    // pull in `parley`/`fontique`/`std::fs` and break `no_std`). The
    // glyph data is selected by the host build's `fontique` against
    // the family names declared in the .slint files (`Inter` and
    // `JetBrains Mono` per Track YY / #432); when the host has those
    // families installed (rsms/inter, JetBrains/JetBrainsMono OFL
    // fonts vendored under `assets/fonts/`), the embedded atlases are
    // a perfect match. When the host falls back to a system Sans-
    // Serif, the design-system spelling stays correct but the
    // rendered glyph shapes follow the host fallback — acceptable for
    // the boot UI since the only on-screen text pre-#431 is the
    // AppShell title bar + status footer (`AREST` / `Ready`).
    //
    // The vendored TTF bytes in `crate::fonts` (Track JJJ #433) stay
    // exposed as `pub static &[u8]` slices for any future runtime path
    // that needs raw font bytes (e.g. shaping a custom glyph set
    // outside the Slint pipeline) — they are unused by the embedded-
    // glyph path because `register_bitmap_font` consumes pre-
    // rasterised data, not TrueType.
    // #627 Profile-3: `slint-build` is now an optional build-dep
    // gated behind `feature = "slint"`. When the feature is OFF
    // (the headless `--no-default-features --features server`
    // profile), `slint-build`'s sources aren't resolved, so
    // calling `slint_build::compile_with_config(...)` here would
    // fail at the use site of the now-absent crate. Wrap the
    // whole compile pass under `CARGO_FEATURE_SLINT` — same gate
    // shape as CARGO_FEATURE_LINUXKPI / CARGO_FEATURE_UI_BUNDLE
    // already use in this file. The build.rs source itself stays
    // unconditional (we don't `extern crate slint_build` at the
    // top — the proc-macro-style call resolves through the
    // optional dep, which is only present when the gate emits
    // CARGO_FEATURE_SLINT).
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_SLINT");
    let ui_dir = manifest_dir.join("ui");
    // Cargo passes feature flags to build.rs at compile-time as
    // `--cfg feature="..."` (documented in the Cargo book ch.3.9
    // — "Build Scripts > Inputs to the build script"). That lets
    // us cfg-out the `slint_build::*` use sites here so the
    // build.rs source itself compiles cleanly when the optional
    // `slint-build` dep is absent (the headless `--no-default-
    // features --features server` profile). The runtime
    // `CARGO_FEATURE_SLINT` env var is also rerun-tracked above
    // so toggling the feature re-runs the script.
    #[cfg(not(feature = "slint"))]
    {
        let _ = ui_dir.is_dir(); // silence unused-binding warning
        println!(
            "cargo:warning=slint feature off: skipping slint_build::compile (#627 Profile-3)",
        );
    }
    #[cfg(feature = "slint")]
    if ui_dir.is_dir() {
        // Compile entry: `ui/apps/UnifiedRepl.slint` (#510, EPIC #496).
        //
        // Why one master entry .slint:
        // `slint::include_modules!()` is keyed off a single
        // `SLINT_INCLUDE_GENERATED` env var that `slint_build::
        // compile_with_config` rewrites on every call (see
        // slint-build/lib.rs L535 in v1.16.1) — only the LAST
        // compiled file is reachable through `include_modules!()`. To
        // keep every Window-derived component (AppShell, AppLauncher,
        // Doom, Keyboard, plus the new merged UnifiedRepl) reachable
        // from the single `slint::include_modules!()` site in
        // `arch/uefi/slint_backend.rs`, UnifiedRepl is the compile
        // entry: it imports + re-exports the others so the slint
        // compiler walks the full import graph and codegens every
        // reachable exported component.
        //
        // History:
        //   * Pre-#429: ui/AppShell.slint was the entry.
        //   * #429 (Track SSS): ui/apps/HateoasBrowser.slint became
        //     the entry, re-exporting AppShell. Repl, AppLauncher,
        //     Doom, Keyboard later joined as transitive imports.
        //   * #510 (this commit): HateoasBrowser + Repl are merged
        //     into ui/apps/UnifiedRepl.slint, which becomes the new
        //     entry and re-exports AppShell + AppLauncher + Doom +
        //     Keyboard transitively.
        //
        // If a future track adds another app, it should follow the
        // same pattern — add itself to the master entry .slint that
        // re-exports the previous entries, and update the path here.
        // (Or refactor to `compile_with_output_path` and synthesise
        // a top-level shim in build.rs that `mod`s every generated
        // file by name; see slint-build L551 for that API.)
        let entry = ui_dir.join("apps").join("UnifiedRepl.slint");
        let app_shell_fallback = ui_dir.join("AppShell.slint");
        if entry.is_file() {
            let config = slint_build::CompilerConfiguration::new()
                .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer);
            slint_build::compile_with_config("ui/apps/UnifiedRepl.slint", config)
                .expect("slint_build::compile_with_config(ui/apps/UnifiedRepl.slint) failed");
        } else if app_shell_fallback.is_file() {
            // Fallback to the pre-#429 entry point so a hypothetical
            // future revert (or a partial checkout that drops
            // ui/apps/) still lands a usable AppShell into
            // `slint::include_modules!()`.
            let config = slint_build::CompilerConfiguration::new()
                .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer);
            slint_build::compile_with_config("ui/AppShell.slint", config)
                .expect("slint_build::compile_with_config(ui/AppShell.slint) failed");
        } else {
            println!(
                "cargo:warning=neither ui/apps/UnifiedRepl.slint nor ui/AppShell.slint found under {} — skipping slint-build invocation",
                ui_dir.display(),
            );
        }
    }
    // Watch the vendored fonts (#433) directory. slint-build emits
    // `rerun-if-changed` for each individual TTF it actually embeds
    // (the host fontique matches against the family names in the
    // .slint files); this loop adds the directory contents as a
    // belt-and-braces measure so swapping a font file in place
    // re-triggers the build even if the compiler's last invocation
    // didn't see it (e.g. a future ttf added but not yet referenced
    // by any .slint file).
    let fonts_dir = manifest_dir.join("assets").join("fonts");
    if fonts_dir.is_dir() {
        for entry in fs::read_dir(&fonts_dir).into_iter().flatten().flatten() {
            let p = entry.path();
            if p.extension().and_then(|e| e.to_str()) == Some("ttf") {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }
    // Watch the Lucide SVGs (#434) — `@image-url` references in
    // .slint files cause the compiler to embed the rasterised SVG.
    let icons_dir = manifest_dir.join("assets").join("icons").join("lucide");
    if icons_dir.is_dir() {
        for entry in fs::read_dir(&icons_dir).into_iter().flatten().flatten() {
            let p = entry.path();
            if p.extension().and_then(|e| e.to_str()) == Some("svg") {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }

    // --- linuxkpi C-side compile (#460 Track AAAA) -------------------
    //
    // Builds the vendored Linux driver source against the shim's stub
    // headers, producing a libvirtio_input.a that the Rust kernel
    // links in. Gated on the `linuxkpi` cargo feature so default
    // builds skip it entirely.
    //
    // Cross-compilation notes (Windows host -> x86_64-unknown-uefi):
    //   * The `cc` crate auto-discovers a host C toolchain. On
    //     Windows the default is MSVC's cl.exe, but MSVC can't target
    //     the SysV-AMD64 calling convention that x86_64-unknown-uefi
    //     PE32+ expects (UEFI is Microsoft-x64 ABI which IS what
    //     MSVC emits, so this works out — UEFI and MSVC share the
    //     same calling convention). However, MSVC chokes on Linux's
    //     `__attribute__((packed))` and various other GNU-isms in
    //     the vendored header subset. Using clang-cl or plain clang
    //     with `--target=x86_64-pc-windows-msvc` (since UEFI ABI ==
    //     MSVC ABI on x86_64) is the cleanest path.
    //   * If the host doesn't have clang available, `cc::Build::new()
    //     .try_compile()` returns an Err with a clear message. We
    //     surface that as a `cargo:warning=` and continue with the
    //     Rust-only build — the Rust shim modules still compile, the
    //     C-side just isn't linked. Downstream of #459b the C side
    //     becomes load-bearing; today this graceful-degrade keeps
    //     fresh-clone builds from breaking on hosts without clang.
    //   * The `KBUILD_MODNAME` / `THIS_MODULE` macros that the Linux
    //     `module_virtio_driver` macro uses are stubbed out in
    //     `vendor/linux/include/linux/module.h` (see that header's
    //     comment block for the why).
    if env::var("CARGO_FEATURE_LINUXKPI").is_ok() {
        let vendor_root = manifest_dir.join("vendor").join("linux");
        let virtio_input_c = vendor_root
            .join("drivers").join("virtio").join("virtio_input.c");
        let include_dir = vendor_root.join("include");
        let uapi_dir = include_dir.join("uapi");
        if !virtio_input_c.is_file() {
            println!(
                "cargo:warning=linuxkpi feature enabled but {} missing — skipping C compile",
                virtio_input_c.display(),
            );
        } else {
            let mut build = cc::Build::new();
            // The `cc` crate's auto-discovery looks for a host C
            // compiler keyed on the Cargo target triple. For
            // `x86_64-unknown-uefi` it looks for a `cc` named after
            // that triple (or plain `cc` on Unix), neither of which
            // exists on a Windows MSVC host. We force-prefer clang —
            // freestanding clang accepts a `-target` flag that emits
            // SysV-x86_64 (Linux ABI) object code; the real link
            // target is `x86_64-pc-windows-msvc` because UEFI uses
            // the Microsoft x64 calling convention. Setting the
            // compiler explicitly + the target via flag matches the
            // task brief's "cc needs -target x86_64-unknown-uefi
            // flags" guidance for the Windows-host cross story.
            //
            // If clang isn't in PATH either, `cc::Build::compiler`
            // still reports failure on `try_compile`, and the
            // surrounding match arm degrades gracefully. Both
            // common host setups now have a path forward:
            //   * Linux/macOS — `cc` auto-discovers system clang.
            //   * Windows + clang — explicit override below picks
            //     it up.
            //   * Windows + MSVC only (no clang) — degrades to
            //     "Rust-only" with a warning.
            if cfg!(target_os = "windows") {
                build.compiler("clang");
            }
            build
                .file(&virtio_input_c)
                .include(&include_dir)
                .include(&uapi_dir)
                // UEFI target uses Microsoft x64 ABI on x86_64. We
                // tell clang to emit it directly so the resulting
                // object links cleanly into the .efi PE32+ image.
                .flag_if_supported("--target=x86_64-pc-windows-msvc")
                // Tell clang we're building against a freestanding
                // environment — no libc, no host headers.
                .flag_if_supported("-ffreestanding")
                .flag_if_supported("-fno-builtin")
                .flag_if_supported("/GS-")
                // Ignore unused / unknown attributes coming out of the
                // Linux `__attribute__((...))` decorations.
                .flag_if_supported("-Wno-unknown-attributes")
                .flag_if_supported("-Wno-attributes")
                .flag_if_supported("-Wno-unused-parameter")
                .flag_if_supported("-Wno-unused-function")
                .flag_if_supported("-Wno-unused-variable")
                // Suppress harmless C99-isms / GNU-isms.
                .flag_if_supported("-Wno-pointer-sign")
                // The vendored headers + .c are GPL-2.0; add the
                // license note inline in case a third-party tool
                // grovels the build args for SBOM generation.
                .define("KBUILD_MODNAME", Some("\"virtio_input\""))
                .define("THIS_MODULE", Some("((void *)0)"))
                .define("MODULE", None)
                .warnings(false)
                .opt_level(2);
            // Try the compile; on failure (clang missing, MSVC errors,
            // etc) emit a warning and continue. The kernel still links
            // — the Rust shim modules are present and registered, the
            // C-side virtio_input thunk just won't resolve and any
            // attempt to call `virtio_input_driver_init()` from the
            // Rust side will fail at link time. We guard that call
            // behind the same feature, so it only matters if the
            // user explicitly opts in to linuxkpi AND has a working
            // cross-compiler.
            // Communicate whether the cc step succeeded via a custom
            // cfg, so the Rust side's `virtio_input_driver_init`
            // extern call is only compiled when the symbol actually
            // exists. Without this, a Windows host without clang/MSVC
            // in PATH would `cargo check` clean (check skips linking)
            // but `cargo build` would fail at link time on the
            // unresolved extern. The cfg keeps `cargo build` honest:
            // when the C side is absent, the Rust call site is
            // elided entirely and the extern decl never instantiates.
            //
            // The `linuxkpi` cargo feature itself stays a pure Rust
            // gate — it controls module visibility. The custom cfg
            // controls only the C-driver-link sub-step inside the
            // module.
            println!("cargo:rustc-check-cfg=cfg(linuxkpi_c_linked)");
            match build.try_compile("virtio_input") {
                Ok(()) => {
                    println!("cargo:rustc-link-lib=static=virtio_input");
                    println!("cargo:rustc-cfg=linuxkpi_c_linked");
                }
                Err(e) => {
                    println!(
                        "cargo:warning=linuxkpi cc::Build failed: {}. \
                        The Rust shim modules still compile — the C \
                        side (vendor/linux/drivers/virtio/virtio_input.c) \
                        was skipped, so `virtio_input_driver_init` is \
                        elided from `linuxkpi::init()`. Workaround for \
                        Windows hosts: install clang or run cargo from \
                        a Visual Studio Developer PowerShell so cl.exe \
                        is in PATH (cc auto-detects vcvars from there). \
                        Linux/macOS hosts get cc / clang from the \
                        system package manager.",
                        e,
                    );
                }
            }
            println!("cargo:rerun-if-changed={}", virtio_input_c.display());
            println!("cargo:rerun-if-changed={}", include_dir.display());
        }
    }

    // --- musl libc static archive (#524 Track DDDDD) -----------------
    //
    // Builds the vendored musl 1.2.5 source tree (#523, WWWW) into a
    // freestanding `libc.a` static archive under `$OUT_DIR/`. The
    // archive is NOT linked into the kernel `.efi` binary at this
    // commit — that's #525 onward, when the busybox / ash / hello-
    // world tracks build static Linux ELF guests that link against
    // it. For now this pass is a build-only artifact, gated on the
    // `musl-libc` cargo feature (off by default — see Cargo.toml).
    //
    // ## Build approach
    //
    // Upstream musl is normally configured via its `./configure` +
    // `make` (see vendor/musl/INSTALL). For our embedded use we
    // bypass that and drive `cc::Build` directly, mirroring what
    // the upstream Makefile does:
    //
    //   * Generate `bits/alltypes.h` and `bits/syscall.h` from the
    //     architecture-specific `.in` templates via the `mkalltypes
    //     .sed` rules and the trivial `__NR_xxx -> SYS_xxx` sed-
    //     rewrite the Makefile inlines.
    //   * Walk `vendor/musl/src/<subsys>/*.c` and the architecture
    //     overrides under `vendor/musl/src/<subsys>/x86_64/*.[csS]`,
    //     dropping any base file that has an x86_64 replacement
    //     (the Makefile's `REPLACED_OBJS = $(sort $(subst /$(ARCH)/,
    //     /,$(ARCH_OBJS)))` line).
    //   * Compile each source with the same `-std=c99 -ffreestanding
    //     -nostdinc -D_XOPEN_SOURCE=700` baseline and the same
    //     include path order (`musl_config -> arch/x86_64 ->
    //     arch/generic -> $OUT_DIR/musl/include -> src/include ->
    //     src/internal -> include`) the upstream `CFLAGS_ALL`
    //     assembles.
    //   * Use `cc::Build::compile()` to produce a single static
    //     archive (`libc.a` under `$OUT_DIR/`).
    //
    // ## Cross-compile + graceful degradation
    //
    // Mirrors the linuxkpi gate above — on a Windows host, we force
    // `clang` and `--target=x86_64-pc-windows-msvc` (UEFI uses the
    // Microsoft x64 ABI on x86_64; clang accepts that target while
    // still building Linux-ABI source as long as the source itself
    // doesn't mention SysV-specific ABI quirks, which musl's
    // freestanding C99 baseline avoids except via the per-arch
    // syscall_arch.h inline asm — and that inline asm IS Linux ABI
    // because the syscall instruction itself is, regardless of the
    // host PE32+ link). On Linux/macOS hosts, `cc::Build::compile`
    // auto-discovers the system `cc` / `clang`.
    //
    // If no compatible toolchain is in PATH, `cc::Build::try_compile`
    // returns Err and we surface a `cargo:warning=` instead of
    // breaking the build — same pattern as #460.
    //
    // ## Syscall surface
    //
    // musl's `__syscallN` thunks (vendor/musl/arch/x86_64/syscall_arch
    // .h) drop a `syscall` instruction with the Linux x86_64 number
    // in RAX and arguments in RDI/RSI/RDX/R10/R8/R9. AREST's
    // SYSCALL/SYSRET handler is wired to dispatch by RAX through the
    // same Linux x86_64 number table the vendored
    // `arch/x86_64/bits/syscall.h.in` defines (see musl_config/
    // syscall.h for the override hook when AREST diverges). Tracks
    // #507 / #497..#502 (none landed yet) are responsible for
    // implementing each individual syscall on the AREST side; until
    // those land, calls into musl that hit an unimplemented number
    // will return -ENOSYS at runtime, not fail at link time.
    //
    // ## What gets compiled vs not
    //
    // Walks `vendor/musl/src/<every-subsys>/` for both base `.c` and
    // x86_64 overrides under `<subsys>/x86_64/*.[csS]`. Skips:
    //
    //   * `src/malloc/oldmalloc/` (Makefile picks `mallocng` by
    //     default via `MALLOC_DIR = mallocng`).
    //   * `crt/`, `ldso/` (CRT objects + dynamic linker — those
    //     belong in separate archives upstream and aren't part of
    //     `libc.a`; #525-onward will pull crt1.o etc. as separate
    //     `cc::Build` invocations when actually linking guests).
    //   * `compat/` (legacy time32 wrappers — only relevant for the
    //     i386 / arm32 arms; x86_64 is time64-native).
    //   * Per-arch overrides for non-x86_64 architectures (`/aarch64
    //     /`, `/arm/`, `/i386/`, `/mips*/`, `/powerpc*/`, `/riscv*/`,
    //     `/s390x/`, `/loongarch64/`, `/sh/`, `/m68k/`, `/microblaze
    //     /`, `/or1k/`).
    //
    // ## Verification
    //
    //   cargo check -p arest-kernel --target x86_64-unknown-uefi
    //     -> default build (musl-libc OFF) — must pass cleanly.
    //   cargo build -p arest-kernel --target x86_64-unknown-uefi
    //     --features musl-libc
    //     -> compiles the musl tree; emits `libc.a` under
    //        $OUT_DIR. May emit warnings about missing toolchain
    //        (Windows host without clang) or per-file musl-build
    //        warnings — those are non-fatal; we surface only fatal
    //        toolchain-discovery failure as a `cargo:warning=`.
    if env::var("CARGO_FEATURE_MUSL_LIBC").is_ok() {
        let musl_root = manifest_dir.join("vendor").join("musl");
        let arch = "x86_64";
        if !musl_root.is_dir() {
            println!(
                "cargo:warning=musl-libc feature enabled but {} missing — skipping musl C compile",
                musl_root.display(),
            );
        } else if let Err(e) = build_musl_libc(&manifest_dir, &musl_root, &out_dir, arch) {
            println!(
                "cargo:warning=musl-libc cc::Build skipped: {}. Future static guest builds (busybox / ash / hello-world, #525 onward) will need a working cross-compiler in PATH. Workaround for Windows hosts: install clang or run cargo from a Visual Studio Developer PowerShell so cl.exe is in PATH (cc auto-detects vcvars from there). Linux/macOS hosts get cc / clang from the system package manager.",
                e,
            );
        }
        println!("cargo:rerun-if-changed={}", musl_root.display());
        println!("cargo:rerun-if-changed={}", manifest_dir.join("musl_config").display());
    }

    // --- busybox 1.36.1 static guest build (#525 Track WWWWW) ---------
    //
    // Drives the vendored busybox 1.36.1 tree (vendor/busybox/) +
    // sibling `busybox_config/.config` through `cc::Build` to produce
    // a static x86_64-linux ELF binary that links against the musl
    // libc.a archive #524 produces. The output binary lands at
    // `$OUT_DIR/busybox`. It is NOT linked into the kernel `.efi`
    // image at this commit — that's #527 (interactive shell session,
    // when the ELF loader at #472 reads `$OUT_DIR/busybox` and
    // launches it inside the sandbox). For now this pass is purely
    // a build-only artefact, gated behind the `busybox` cargo
    // feature (off by default — see Cargo.toml; the GPL-2.0-only
    // license inheritance is documented at the feature definition).
    //
    // ## Build approach
    //
    // Upstream busybox uses Kconfig + a kernel-style Kbuild driver:
    // `make defconfig` writes `.config`, `make` invokes Kbuild scripts
    // that generate `include/autoconf.h` (one `#define ENABLE_<APPLET>
    // 1` per `CONFIG_<APPLET>=y`) and `include/applets.h` (the
    // `APPLET()` macro table the dispatcher walks at startup), then
    // gcc compiles every selected `.c` and links them into the
    // single `busybox` multi-call binary.
    //
    // We can't shell out to `make` from a Rust build script, so we
    // bypass Kbuild and do the equivalent in pure Rust:
    //
    //   1. Parse `busybox_config/.config` for `CONFIG_xxx=y` /
    //      `# CONFIG_xxx is not set` lines.
    //   2. Generate `$OUT_DIR/busybox/include/autoconf.h` —
    //      `#define ENABLE_xxx 1` for every enabled CONFIG and
    //      `#define ENABLE_xxx 0` for every disabled one. This file
    //      is the linchpin: the `IF_xxx(...)` and `ENABLE_xxx`
    //      macros sprinkled through every source file resolve to
    //      either the wrapped expression or a no-op based on this
    //      header.
    //   3. Generate `$OUT_DIR/busybox/include/applets.h` — the
    //      `APPLET()` table. Upstream Kbuild greps every .c for
    //      `//applet:` directives; we generate it directly from the
    //      enabled CONFIGs since our applet set is closed (6 entries:
    //      cat / echo / head / ls / tail / wc).
    //   4. `cc::Build` walks `vendor/busybox/{libbb, coreutils,
    //      applets}` for the chosen sources, compiles each with the
    //      same `-D_GNU_SOURCE -DNDEBUG -include autoconf.h`
    //      baseline upstream's Makefile.flags assembles, and links
    //      them with the musl crt + libc.a from #524 into
    //      `$OUT_DIR/busybox`.
    //
    // ## Tier-1 scope (this commit)
    //
    // The brief explicitly says: "Just build the .a / binary, prove
    // the toolchain works." The vendored busybox tree is in place; the
    // build path is wired and gated; the `.config` selection drives
    // applet generation. Whether the cc::Build invocation actually
    // succeeds end-to-end depends on the host toolchain (busybox is
    // GNU-C-heavy and needs clang/gcc — MSVC's cl.exe will choke on
    // statement-expressions, designated initialisers, etc). When it
    // doesn't, we surface a `cargo:warning=` and continue, same
    // graceful-degrade pattern #460 / #524 established. The vendor
    // tree + config + build wiring are the load-bearing artefacts
    // a future track can extend.
    //
    // ## Cross-compile + graceful degradation
    //
    // Mirrors the musl pass above:
    //   * Force `clang` on Windows; let `cc` auto-discover on
    //     Linux/macOS.
    //   * `--target=x86_64-unknown-linux-musl` so clang emits Linux-
    //     ABI ELF instead of host PE32+/Mach-O. (Note: this differs
    //     from the musl pass's `x86_64-pc-windows-msvc` target —
    //     musl is built INTO an archive linked at the kernel's UEFI
    //     PE32+ stage; busybox is built as a separate Linux ELF
    //     guest the kernel later loads via #472.)
    //   * If musl libc.a from #524 isn't in $OUT_DIR (cfg
    //     `musl_libc_built` not set), skip with a clear warning —
    //     same fallback shape #460 uses.
    //   * If clang/gcc isn't in PATH, `try_compile` returns Err and
    //     we surface a `cargo:warning=`.
    if env::var("CARGO_FEATURE_BUSYBOX").is_ok() {
        let busybox_root = manifest_dir.join("vendor").join("busybox");
        let busybox_config = manifest_dir.join("busybox_config").join(".config");
        if !busybox_root.is_dir() {
            println!(
                "cargo:warning=busybox feature enabled but {} missing — skipping busybox build",
                busybox_root.display(),
            );
        } else if !busybox_config.is_file() {
            println!(
                "cargo:warning=busybox feature enabled but {} missing — skipping busybox build",
                busybox_config.display(),
            );
        } else if env::var("CARGO_FEATURE_MUSL_LIBC").is_err() {
            println!(
                "cargo:warning=busybox build needs --features musl-libc (libc.a from #524). Re-run with `--features musl-libc,busybox`."
            );
        } else if let Err(e) = build_busybox(&manifest_dir, &busybox_root, &busybox_config, &out_dir) {
            println!(
                "cargo:warning=busybox build needs musl libc.a from #524: {}. The vendor tree, .config, and build wiring are all in place; this pass degrades gracefully when the host cross-toolchain (clang or gcc with the musl sysroot path) is missing. Workaround for Windows hosts: install clang and re-run from a shell where it is in PATH. Linux/macOS hosts get cc / clang from the system package manager.",
                e,
            );
        }
        println!("cargo:rerun-if-changed={}", busybox_root.display());
        println!("cargo:rerun-if-changed={}", busybox_config.display());
    }

    // Re-run whenever the bundle changes.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());
    for (_, p) in &entries {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    // Pick up the binary being added or removed between builds even
    // if it never existed on the first run (rerun-if-changed on a
    // non-existent path still triggers when the path later appears).
    println!("cargo:rerun-if-changed={}", doom_wasm.display());
    println!("cargo:rerun-if-changed={}", doom_wad.display());
}

/// Convert a filesystem path into a form accepted by rustc's
/// `include_bytes!` macro:
///   * canonicalize to resolve any `..` / symlinks,
///   * normalize backslashes to forward slashes (Windows),
///   * strip the `\\?\` UNC prefix that `Path::canonicalize` adds
///     on Windows, which rustc does not accept inside a string
///     literal passed to `include_bytes!`.
fn abs_include_path(path: &Path) -> String {
    let abs = path
        .canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .replace('\\', "/");
    abs.strip_prefix("//?/").unwrap_or(&abs).to_string()
}

/// Drive the musl-libc compile pass behind `--features musl-libc`
/// (#524 Track DDDDD).
///
/// Returns `Ok(())` when `libc.a` lands under `$OUT_DIR/`, or `Err`
/// when the toolchain discovery / source-walk hit a fatal problem
/// (caller surfaces as `cargo:warning=` and continues).
///
/// See the block comment in `main()` immediately above the
/// `CARGO_FEATURE_MUSL_LIBC` gate for the full design rationale.
fn build_musl_libc(
    manifest_dir: &Path,
    musl_root: &Path,
    out_dir: &Path,
    arch: &str,
) -> Result<(), String> {
    // 1. Generate the two headers the upstream Makefile generates:
    //    `bits/alltypes.h` and `bits/syscall.h`. Both land under
    //    `$OUT_DIR/musl/include/bits/` so the compile pass can
    //    reach them via `-I$OUT_DIR/musl/include` (matching the
    //    upstream `-Iobj/include`).
    let gen_root = out_dir.join("musl").join("include").join("bits");
    fs::create_dir_all(&gen_root)
        .map_err(|e| format!("create $OUT_DIR/musl/include/bits: {}", e))?;
    generate_alltypes_h(musl_root, &gen_root, arch)?;
    generate_syscall_h(musl_root, &gen_root, arch)?;

    // 2. Walk the source tree.
    let mut sources: Vec<PathBuf> = Vec::new();
    let mut replaced: Vec<String> = Vec::new();
    let exclude_archs: &[&str] = &[
        "aarch64", "arm", "i386", "loongarch64", "m68k", "microblaze",
        "mips", "mips64", "mipsn32", "or1k", "powerpc", "powerpc64",
        "riscv32", "riscv64", "s390x", "sh",
        // x32 is x86_64-with-ILP32 — a different ABI from the
        // SysV-AMD64 LP64 we target. INSTALL flags it as
        // experimental upstream; skip its overrides too.
        "x32",
        // Skip the upstream pre-mallocng allocator. The Makefile's
        // MALLOC_DIR=mallocng default makes oldmalloc sit unused
        // upstream too; `subsys_dirs` already routes us to mallocng,
        // but the recursive walker would otherwise descend into
        // oldmalloc/* if a future subsys grew an `oldmalloc` dir.
        "oldmalloc",
    ];
    let src_root = musl_root.join("src");
    let mut subsys_dirs: Vec<PathBuf> = Vec::new();
    if let Ok(entries) = fs::read_dir(&src_root) {
        for e in entries.flatten() {
            let p = e.path();
            if !p.is_dir() {
                continue;
            }
            let name = match p.file_name().and_then(|n| n.to_str()) {
                Some(n) => n,
                None => continue,
            };
            // src/include/ and src/internal/ have headers + per-arch
            // subdirs; src/internal/ also has .c files (defsysinfo,
            // emulate_wait4, libc, ...) which the upstream Makefile
            // pulls in via the `src/*/*.c` glob — so include them.
            if name == "include" {
                continue; // headers only
            }
            if name == "malloc" {
                // Only the mallocng subdir, per Makefile's
                // `MALLOC_DIR = mallocng` default.
                subsys_dirs.push(p.join("mallocng"));
                continue;
            }
            subsys_dirs.push(p);
        }
    }
    for subsys in &subsys_dirs {
        collect_musl_sources(subsys, arch, exclude_archs, &mut sources, &mut replaced);
    }
    sources.sort();
    sources.dedup();

    if sources.is_empty() {
        return Err(format!(
            "no musl sources found under {} — vendor tree may be incomplete",
            src_root.display(),
        ));
    }

    // 3. Set up the cc::Build invocation matching upstream's
    //    CFLAGS_ALL.
    let mut build = cc::Build::new();

    // Force clang on Windows for the same reason the linuxkpi pass
    // does — MSVC's cl.exe cannot drive musl's GNU-C source (inline
    // asm, statement-expressions, attributes). On Linux/macOS, let
    // cc auto-discover.
    if cfg!(target_os = "windows") {
        build.compiler("clang");
    }

    // Include path order, identical to upstream's CFLAGS_ALL line in
    // `Makefile`:
    //   -Imusl_config (AREST overrides, FIRST so they win on conflict)
    //   -Iarch/$(ARCH)
    //   -Iarch/generic
    //   -I$(OUT_DIR)/musl/src/internal (would be obj/src/internal)
    //   -Isrc/include
    //   -Isrc/internal
    //   -I$(OUT_DIR)/musl/include   (would be obj/include — for the
    //                                generated bits/alltypes.h +
    //                                bits/syscall.h)
    //   -Iinclude
    let arch_dir = musl_root.join("arch").join(arch);
    let arch_generic = musl_root.join("arch").join("generic");
    let gen_include_dir = out_dir.join("musl").join("include");
    let src_include = musl_root.join("src").join("include");
    let src_internal = musl_root.join("src").join("internal");
    let main_include = musl_root.join("include");
    let musl_config_dir = manifest_dir.join("musl_config");
    build
        .include(&musl_config_dir)
        .include(&arch_dir)
        .include(&arch_generic)
        .include(&src_include)
        .include(&src_internal)
        .include(&gen_include_dir)
        .include(&main_include);

    // CFLAGS_C99FSE: -std=c99 -ffreestanding -nostdinc
    // CFLAGS_ALL adds -D_XOPEN_SOURCE=700.
    build
        .flag_if_supported("-std=c99")
        .flag_if_supported("-ffreestanding")
        .flag_if_supported("-nostdinc")
        .flag_if_supported("-fno-builtin")
        .define("_XOPEN_SOURCE", Some("700"));

    // Cross-target flag for the Windows host case. Linux/macOS hosts
    // building for x86_64-pc-linux-gnu (the default cc target) end
    // up emitting Linux ABI directly, which is what musl wants.
    if cfg!(target_os = "windows") {
        // UEFI target uses Microsoft x64 ABI; clang emits PE32+
        // objects compatible with the .efi link. The musl-internal
        // syscall asm still uses the SysV `syscall` instruction —
        // that's fine because the `syscall` opcode is identical
        // regardless of which ABI's calling-convention sets up its
        // arguments; what matters at runtime is that the AREST
        // syscall handler picks them out of RAX/RDI/RSI/RDX/R10/R8/R9
        // exactly the way musl placed them.
        build.flag_if_supported("--target=x86_64-pc-windows-msvc");
    }

    // Suppress noise that would otherwise drown the build log. Musl
    // source is clean upstream but emits standard C99-isms our
    // wrapper doesn't care about.
    build
        .warnings(false)
        .flag_if_supported("-Wno-unknown-attributes")
        .flag_if_supported("-Wno-attributes")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function")
        .flag_if_supported("-Wno-unused-variable")
        .flag_if_supported("-Wno-pointer-sign")
        .flag_if_supported("-Wno-missing-braces")
        .flag_if_supported("-Wno-parentheses")
        .flag_if_supported("-Wno-uninitialized")
        .flag_if_supported("-Wno-sign-compare")
        // Musl heavily uses GCC's `__attribute__((may_alias))` on its
        // word-stride string ops; clang accepts but warns on -Wcast-
        // align in some templates.
        .flag_if_supported("-Wno-cast-align")
        // Some musl headers define both __NR_xxx and SYS_xxx; the
        // generated bits/syscall.h re-emits SYS_xxx via sed which can
        // collide with the kernel-headers stub if a future track adds
        // one. Silence the resulting -Wmacro-redefined.
        .flag_if_supported("-Wno-macro-redefined");

    // Optimisation level matches CFLAGS_AUTO = -Os -pipe.
    build.opt_level_str("s");

    // Pull in the AREST-specific syscall + arch overrides via
    // -include, AFTER the per-arch syscall.h so any redefine wins.
    // arch.h is pulled in early (before musl arch headers).
    let arch_override = musl_config_dir.join("arch.h");
    let syscall_override = musl_config_dir.join("syscall.h");
    if arch_override.is_file() {
        build.flag_if_supported(&format!(
            "-include{}",
            arch_override.to_string_lossy(),
        ));
    }
    if syscall_override.is_file() {
        build.flag_if_supported(&format!(
            "-include{}",
            syscall_override.to_string_lossy(),
        ));
    }

    // Add every walked source.
    for s in &sources {
        build.file(s);
    }

    println!("cargo:rustc-check-cfg=cfg(musl_libc_built)");
    match build.try_compile("c") {
        Ok(()) => {
            // cc::Build emits libc.a (or `libc.lib` on MSVC, but
            // since we forced clang above on Windows we still get
            // libc.a) under $OUT_DIR. Surface the search path so
            // future tracks (#525 busybox / ash / hello-world) can
            // pull it in via `-l static=c`.
            println!(
                "cargo:rustc-link-search=native={}",
                out_dir.display(),
            );
            println!("cargo:rustc-cfg=musl_libc_built");
            // Don't `cargo:rustc-link-lib=` here — the kernel binary
            // doesn't link musl yet (#524 brief: "Do NOT actually
            // link musl into the kernel binary yet — that's #525
            // onward"). The archive sits in $OUT_DIR waiting for a
            // future static-guest build to consume it.
            println!(
                "cargo:warning=musl-libc: built libc.a ({} sources, {} arch-overridden) under {}",
                sources.len(),
                replaced.len(),
                out_dir.display(),
            );
            Ok(())
        }
        Err(e) => Err(format!("{}", e)),
    }
}

/// Generate `bits/alltypes.h` from the per-arch + generic templates,
/// applying the same sed transforms upstream's `tools/mkalltypes.sed`
/// applies in the Makefile's `obj/include/bits/alltypes.h` rule.
fn generate_alltypes_h(
    musl_root: &Path,
    gen_root: &Path,
    arch: &str,
) -> Result<(), String> {
    let arch_in = musl_root.join("arch").join(arch).join("bits").join("alltypes.h.in");
    let generic_in = musl_root.join("include").join("alltypes.h.in");
    let mut combined = String::new();
    combined.push_str(
        &fs::read_to_string(&arch_in)
            .map_err(|e| format!("read {}: {}", arch_in.display(), e))?,
    );
    combined.push('\n');
    combined.push_str(
        &fs::read_to_string(&generic_in)
            .map_err(|e| format!("read {}: {}", generic_in.display(), e))?,
    );
    let transformed = mkalltypes(&combined);
    let out_path = gen_root.join("alltypes.h");
    fs::write(&out_path, transformed)
        .map_err(|e| format!("write {}: {}", out_path.display(), e))?;
    Ok(())
}

/// Apply the upstream `tools/mkalltypes.sed` rules in pure Rust.
///
/// The sed file rewrites three macro lines:
///
///   TYPEDEF <ty> <name>;
///     -> guarded `typedef <ty> <name>;` with __NEED_/__DEFINED_
///        gates.
///   STRUCT  <name> <body>;
///     -> guarded `struct <name> <body>;` with __NEED_struct_/__DEFINED_
///        struct_ gates.
///   UNION   <name> <body>;
///     -> guarded `union <name> <body>;` with the analogous gates.
///
/// All other lines pass through unchanged. The produced header is
/// identical (modulo trailing whitespace) to what `sed -f
/// tools/mkalltypes.sed` would emit when run on the concatenation of
/// `arch/$(ARCH)/bits/alltypes.h.in` and `include/alltypes.h.in`.
fn mkalltypes(input: &str) -> String {
    let mut out = String::new();
    for line in input.lines() {
        let trimmed = line.trim_end_matches(';');
        if let Some(rest) = line.strip_prefix("TYPEDEF ") {
            // "TYPEDEF <ty...> <name>;"
            let body = rest.trim_end_matches(';').trim();
            if let Some(idx) = body.rfind(' ') {
                let ty = body[..idx].trim();
                let name = body[idx + 1..].trim();
                out.push_str(&format!(
                    "#if defined(__NEED_{name}) && !defined(__DEFINED_{name})\n\
                     typedef {ty} {name};\n\
                     #define __DEFINED_{name}\n\
                     #endif\n\n",
                    name = name,
                    ty = ty,
                ));
                continue;
            }
        } else if let Some(rest) = line.strip_prefix("STRUCT ") {
            let body = rest.trim_end_matches(';').trim();
            if let Some(idx) = body.find(' ') {
                let name = body[..idx].trim();
                let rest = body[idx + 1..].trim();
                out.push_str(&format!(
                    "#if defined(__NEED_struct_{name}) && !defined(__DEFINED_struct_{name})\n\
                     struct {name} {rest};\n\
                     #define __DEFINED_struct_{name}\n\
                     #endif\n\n",
                    name = name,
                    rest = rest,
                ));
                continue;
            }
        } else if let Some(rest) = line.strip_prefix("UNION ") {
            let body = rest.trim_end_matches(';').trim();
            if let Some(idx) = body.find(' ') {
                let name = body[..idx].trim();
                let rest = body[idx + 1..].trim();
                out.push_str(&format!(
                    "#if defined(__NEED_union_{name}) && !defined(__DEFINED_union_{name})\n\
                     union {name} {rest};\n\
                     #define __DEFINED_union_{name}\n\
                     #endif\n\n",
                    name = name,
                    rest = rest,
                ));
                continue;
            }
        }
        let _ = trimmed; // currently unused; placeholder for future.
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Generate `bits/syscall.h`, applying the Makefile's two-line rule:
///
///   cp arch/$ARCH/bits/syscall.h.in obj/include/bits/syscall.h
///   sed -n -e 's/__NR_/SYS_/p' < ... >> obj/include/bits/syscall.h
///
/// I.e. emit the original `__NR_xxx` definitions verbatim, then
/// re-emit each as a `SYS_xxx` alias.
fn generate_syscall_h(
    musl_root: &Path,
    gen_root: &Path,
    arch: &str,
) -> Result<(), String> {
    let in_path = musl_root.join("arch").join(arch).join("bits").join("syscall.h.in");
    let in_text = fs::read_to_string(&in_path)
        .map_err(|e| format!("read {}: {}", in_path.display(), e))?;
    let mut out = String::new();
    out.push_str(&in_text);
    if !in_text.ends_with('\n') {
        out.push('\n');
    }
    for line in in_text.lines() {
        if let Some(rest) = line.strip_prefix("#define __NR_") {
            out.push_str("#define SYS_");
            out.push_str(rest);
            out.push('\n');
        }
    }
    let out_path = gen_root.join("syscall.h");
    fs::write(&out_path, out)
        .map_err(|e| format!("write {}: {}", out_path.display(), e))?;
    Ok(())
}

/// Walk `subsys_dir` for base `.c` source plus per-arch overrides
/// under `subsys_dir/<arch>/*.[csS]`.
///
/// Mirrors the upstream Makefile's
///   ARCH_GLOBS = src/<subsys>/$(ARCH)/*.[csS]
///   REPLACED_OBJS = $(sort $(subst /$(ARCH)/,/,$(ARCH_OBJS)))
/// rule: every base file whose stem matches an arch-override is
/// dropped in favour of the override. Files under any other arch's
/// subdirectory are skipped entirely.
fn collect_musl_sources(
    subsys_dir: &Path,
    arch: &str,
    exclude_archs: &[&str],
    out: &mut Vec<PathBuf>,
    replaced: &mut Vec<String>,
) {
    let arch_dir = subsys_dir.join(arch);
    let mut arch_stems: Vec<String> = Vec::new();
    if arch_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&arch_dir) {
            for e in entries.flatten() {
                let p = e.path();
                if !p.is_file() {
                    continue;
                }
                let ext = p.extension().and_then(|x| x.to_str()).unwrap_or("");
                if matches!(ext, "c" | "s" | "S") {
                    if let Some(stem) = p.file_stem().and_then(|x| x.to_str()) {
                        arch_stems.push(stem.to_string());
                    }
                    out.push(p);
                }
            }
        }
    }

    if let Ok(entries) = fs::read_dir(subsys_dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_file() {
                let ext = p.extension().and_then(|x| x.to_str()).unwrap_or("");
                if ext == "c" {
                    if let Some(stem) = p.file_stem().and_then(|x| x.to_str()) {
                        if arch_stems.iter().any(|s| s == stem) {
                            replaced.push(format!("{}/{}.c", subsys_dir.display(), stem));
                            continue;
                        }
                        out.push(p);
                    }
                }
            } else if p.is_dir() {
                let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                if name == arch {
                    continue; // already handled
                }
                if exclude_archs.contains(&name) {
                    continue; // foreign arch
                }
                // Other subdir (e.g. mallocng's `glue.h`-only nested
                // dir, or src/internal/i386/ which we excluded above
                // by the foreign-arch check). Walk one level deeper
                // for mallocng-style nested .c files.
                collect_musl_sources(&p, arch, exclude_archs, out, replaced);
            }
        }
    }
}

/// Drive the busybox-1.36.1 static-build pass behind `--features
/// busybox` (#525 Track WWWWW).
///
/// Returns `Ok(())` when `$OUT_DIR/busybox` lands as a static x86_64-
/// linux ELF, or `Err` describing the failure (caller surfaces as
/// `cargo:warning=` and continues).
///
/// See the block comment in `main()` immediately above the
/// `CARGO_FEATURE_BUSYBOX` gate for the full design rationale.
fn build_busybox(
    manifest_dir: &Path,
    busybox_root: &Path,
    busybox_config: &Path,
    out_dir: &Path,
) -> Result<(), String> {
    // 1. Parse `.config` into the set of enabled CONFIG_xxx names
    //    (and the disabled ones, for completeness — Kbuild generates
    //    `#define ENABLE_xxx 0` for those too).
    let cfg_text = fs::read_to_string(busybox_config)
        .map_err(|e| format!("read {}: {}", busybox_config.display(), e))?;
    let mut enabled: Vec<String> = Vec::new();
    let mut disabled: Vec<String> = Vec::new();
    for line in cfg_text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("#") {
            // `# CONFIG_FOO is not set` is the disabled form.
            if let Some(rest) = line.strip_prefix("# CONFIG_") {
                if let Some(name) = rest.strip_suffix(" is not set") {
                    disabled.push(name.trim().to_string());
                }
            }
            continue;
        }
        if let Some(rest) = line.strip_prefix("CONFIG_") {
            if let Some(eq) = rest.find('=') {
                let name = rest[..eq].trim();
                let val = rest[eq + 1..].trim();
                if val == "y" {
                    enabled.push(name.to_string());
                }
                // Numeric and string values (CONFIG_FEATURE_COPYBUF_KB=4,
                // CONFIG_BUSYBOX_EXEC_PATH="/bin/busybox") get baked
                // into autoconf.h verbatim below; we do not list them
                // here because the `ENABLE_xxx` macro path applies
                // only to bool flags.
            }
        }
    }

    // 2. Generate `$OUT_DIR/busybox/include/autoconf.h`.
    let gen_include = out_dir.join("busybox").join("include");
    fs::create_dir_all(&gen_include)
        .map_err(|e| format!("create $OUT_DIR/busybox/include: {}", e))?;
    let mut autoconf = String::new();
    autoconf.push_str("/* Generated by build.rs from busybox_config/.config — do not edit. */\n");
    autoconf.push_str("#ifndef BB_AUTOCONF_H\n#define BB_AUTOCONF_H 1\n\n");
    // `BB_VER` baked in (matches the `Makefile.flags` `-DBB_VER=...`).
    autoconf.push_str("#define BB_VER \"1.36.1\"\n");
    autoconf.push_str("#define BB_BT \"\"\n");
    autoconf.push_str("#define AUTOCONF_TIMESTAMP \"\"\n");
    autoconf.push_str("\n/* Bool flags from .config */\n");
    for name in &enabled {
        autoconf.push_str(&format!("#define ENABLE_{} 1\n", name));
        autoconf.push_str(&format!("#define IF_{}(...) __VA_ARGS__\n", name));
        autoconf.push_str(&format!("#define IF_NOT_{}(...)\n", name));
    }
    for name in &disabled {
        autoconf.push_str(&format!("#define ENABLE_{} 0\n", name));
        autoconf.push_str(&format!("#define IF_{}(...)\n", name));
        autoconf.push_str(&format!("#define IF_NOT_{}(...) __VA_ARGS__\n", name));
    }
    // Numeric / string CONFIG_xxx values lifted verbatim. These are
    // a tiny set in our tier-1 .config (FEATURE_COPYBUF_KB=4,
    // BUSYBOX_EXEC_PATH="/bin/busybox", PREFIX, CROSS_COMPILER_PREFIX,
    // SYSROOT, EXTRA_CFLAGS, EXTRA_LDFLAGS, EXTRA_LDLIBS,
    // SUID_CONFIG_FILE, PID_FILE_PATH).
    for line in cfg_text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("CONFIG_") {
            if let Some(eq) = rest.find('=') {
                let name = rest[..eq].trim();
                let val = rest[eq + 1..].trim();
                if val != "y" && !val.is_empty() {
                    autoconf.push_str(&format!("#define CONFIG_{} {}\n", name, val));
                }
            }
        }
    }
    autoconf.push_str("\n#endif /* BB_AUTOCONF_H */\n");
    let autoconf_path = gen_include.join("autoconf.h");
    fs::write(&autoconf_path, &autoconf)
        .map_err(|e| format!("write {}: {}", autoconf_path.display(), e))?;

    // 3. Generate `$OUT_DIR/busybox/include/applets.h` — the table
    //    `applets/applets.c` walks at startup. Upstream Kbuild
    //    greps every .c for `//applet:` directives; for our closed
    //    6-applet set we hand-emit the table. Keeping this in sync
    //    with `busybox_config/.config` is straightforward — every
    //    new applet adds one entry here AND one `CONFIG_<APPLET>=y`
    //    line in the .config.
    let mut applets = String::new();
    applets.push_str("/* Generated by build.rs — do not edit. */\n");
    applets.push_str("/* Hand-emitted from the closed 6-applet set in busybox_config/.config */\n\n");
    // Re-emit the upstream applets.src.h preamble verbatim — it
    // defines the APPLET / APPLET_NOEXEC / APPLET_NOFORK /
    // APPLET_ODDNAME / APPLET_SCRIPTED macros + the BB_DIR_xxx /
    // BB_SUID_xxx enum values that the table entries reference.
    applets.push_str("#include \"applet_metadata.h\"\n\n");
    applets.push_str("#if defined(PROTOTYPES)\n");
    applets.push_str("# define APPLET(name,l,s)                    int name##_main(int argc, char **argv) MAIN_EXTERNALLY_VISIBLE;\n");
    applets.push_str("# define APPLET_ODDNAME(name,main,l,s,help)  int main##_main(int argc, char **argv) MAIN_EXTERNALLY_VISIBLE;\n");
    applets.push_str("# define APPLET_NOEXEC(name,main,l,s,help)   int main##_main(int argc, char **argv) MAIN_EXTERNALLY_VISIBLE;\n");
    applets.push_str("# define APPLET_NOFORK(name,main,l,s,help)   int main##_main(int argc, char **argv) MAIN_EXTERNALLY_VISIBLE;\n");
    applets.push_str("# define APPLET_SCRIPTED(name,main,l,s,help)\n");
    applets.push_str("#else\n");
    applets.push_str("# define APPLET(name,l,s)                    { #name, #name, l, s },\n");
    applets.push_str("# define APPLET_ODDNAME(name,main,l,s,help)  { #name, #main, l, s },\n");
    applets.push_str("# define APPLET_NOEXEC(name,main,l,s,help)   { #name, #main, l, s, 1 },\n");
    applets.push_str("# define APPLET_NOFORK(name,main,l,s,help)   { #name, #main, l, s, 1, 1 },\n");
    applets.push_str("# define APPLET_SCRIPTED(name,main,l,s,help) { #name, #main, l, s },\n");
    applets.push_str("#endif\n\n");
    // The 6-applet table. Order matches the .config layout for
    // diff-friendliness.
    applets.push_str("IF_CAT(APPLET_NOFORK(cat, cat, BB_DIR_BIN, BB_SUID_DROP, cat))\n");
    applets.push_str("IF_ECHO(APPLET_NOFORK(echo, echo, BB_DIR_BIN, BB_SUID_DROP, echo))\n");
    applets.push_str("IF_HEAD(APPLET_NOEXEC(head, head, BB_DIR_USR_BIN, BB_SUID_DROP, head))\n");
    applets.push_str("IF_LS(APPLET_NOEXEC(ls, ls, BB_DIR_BIN, BB_SUID_DROP, ls))\n");
    applets.push_str("IF_TAIL(APPLET_NOEXEC(tail, tail, BB_DIR_USR_BIN, BB_SUID_DROP, tail))\n");
    applets.push_str("IF_WC(APPLET_NOEXEC(wc, wc, BB_DIR_USR_BIN, BB_SUID_DROP, wc))\n");
    let applets_path = gen_include.join("applets.h");
    fs::write(&applets_path, &applets)
        .map_err(|e| format!("write {}: {}", applets_path.display(), e))?;

    // 4. Walk the source tree for the bits we want to compile.
    //    libbb is unconditional (the runtime support layer the applet
    //    sources call into); the 6 chosen applets come from coreutils;
    //    the dispatcher `applets/applets.c` becomes the multi-call
    //    binary's main loop.
    let libbb_dir = busybox_root.join("libbb");
    let coreutils_dir = busybox_root.join("coreutils");
    let applets_dir = busybox_root.join("applets");
    let mut sources: Vec<PathBuf> = Vec::new();
    if let Ok(entries) = fs::read_dir(&libbb_dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_file() && p.extension().and_then(|x| x.to_str()) == Some("c") {
                sources.push(p);
            }
        }
    }
    let chosen_applets: &[&str] = &["cat", "echo", "head", "ls", "tail", "wc"];
    for stem in chosen_applets {
        let p = coreutils_dir.join(format!("{}.c", stem));
        if p.is_file() {
            sources.push(p);
        }
    }
    let dispatcher = applets_dir.join("applets.c");
    if dispatcher.is_file() {
        sources.push(dispatcher);
    }
    sources.sort();
    sources.dedup();

    if sources.is_empty() {
        return Err(format!(
            "no busybox sources found under {} — vendor tree may be incomplete",
            busybox_root.display(),
        ));
    }

    // 5. Set up cc::Build matching upstream's Makefile.flags baseline.
    let mut build = cc::Build::new();
    if cfg!(target_os = "windows") {
        build.compiler("clang");
        // Linux ELF target — busybox is a Linux guest binary, NOT a
        // PE32+ image. Unlike the musl pass (which targets `x86_64-pc-
        // windows-msvc` because musl's libc.a links INTO the kernel's
        // UEFI PE32+ image), busybox is the FIRST ELF the AREST kernel
        // loads via the #472 ELF loader, so it needs SysV-AMD64 + ELF
        // output.
        build.flag_if_supported("--target=x86_64-unknown-linux-musl");
    }

    // Include path order matching upstream's Makefile.flags
    // CPPFLAGS line:
    //   -Iinclude
    //   -Ilibbb
    //   -I$(OUT_DIR)/busybox/include   (for autoconf.h + applets.h)
    let main_include = busybox_root.join("include");
    let libbb_include = busybox_root.join("libbb");
    build
        .include(&gen_include)
        .include(&main_include)
        .include(&libbb_include);

    // Pull in the musl headers from #524 so busybox sees the same
    // libc surface the linked-against libc.a exposes. The musl
    // header tree the build script generates lives under
    // `$OUT_DIR/musl/include` (bits/alltypes.h + bits/syscall.h);
    // the verbatim upstream tree under `vendor/musl/include` carries
    // the rest. Order matches the musl pass's include layout: arch
    // overrides first, generated bits next, then the main tree.
    let musl_root = manifest_dir.join("vendor").join("musl");
    let musl_arch = musl_root.join("arch").join("x86_64");
    let musl_arch_generic = musl_root.join("arch").join("generic");
    let musl_gen_include = out_dir.join("musl").join("include");
    let musl_main_include = musl_root.join("include");
    if musl_main_include.is_dir() {
        build
            .include(&musl_arch)
            .include(&musl_arch_generic)
            .include(&musl_gen_include)
            .include(&musl_main_include);
    } else {
        return Err(format!(
            "vendored musl headers not found at {} — #524 vendor tree is required",
            musl_main_include.display(),
        ));
    }

    // CPPFLAGS from upstream's Makefile.flags, minus the ones that
    // are already baked into autoconf.h or that we don't need
    // (CONFIG_LFS is on by default).
    build
        .define("_GNU_SOURCE", None)
        .define("NDEBUG", None)
        .define("_LARGEFILE_SOURCE", None)
        .define("_LARGEFILE64_SOURCE", None)
        .define("_FILE_OFFSET_BITS", Some("64"));

    // Force-include the generated autoconf.h so every source file
    // sees the ENABLE_xxx / IF_xxx macros without needing to
    // explicitly `#include "autoconf.h"`. Mirrors the upstream
    // `-include include/autoconf.h` flag.
    build.flag_if_supported(&format!(
        "-include{}",
        autoconf_path.to_string_lossy(),
    ));

    // CFLAGS from Makefile.flags — the size-optimisation knobs +
    // warning suppressions our build doesn't need to surface.
    build
        .flag_if_supported("-std=gnu99")
        .flag_if_supported("-ffreestanding")
        .flag_if_supported("-nostdinc")
        .flag_if_supported("-fno-builtin")
        .flag_if_supported("-fomit-frame-pointer")
        .flag_if_supported("-ffunction-sections")
        .flag_if_supported("-fdata-sections")
        .flag_if_supported("-fno-unwind-tables")
        .flag_if_supported("-fno-asynchronous-unwind-tables")
        .flag_if_supported("-funsigned-char")
        .warnings(false)
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function")
        .flag_if_supported("-Wno-unused-variable")
        .flag_if_supported("-Wno-pointer-sign")
        .flag_if_supported("-Wno-attributes")
        .flag_if_supported("-Wno-unknown-attributes")
        .flag_if_supported("-Wno-macro-redefined")
        .flag_if_supported("-Wno-string-plus-int")
        .flag_if_supported("-Wno-constant-logical-operand")
        .flag_if_supported("-Wno-incompatible-pointer-types-discards-qualifiers")
        .flag_if_supported("-Wno-int-conversion")
        .flag_if_supported("-Wno-implicit-function-declaration");
    // Optimisation level matches CFLAGS = -Os.
    build.opt_level_str("s");

    // Add every walked source.
    for s in &sources {
        build.file(s);
    }

    println!("cargo:rustc-check-cfg=cfg(busybox_built)");
    match build.try_compile("busybox") {
        Ok(()) => {
            // The cc::Build emits libbusybox.a under $OUT_DIR — the
            // archive of every compiled .o. The brief asks for a
            // `busybox` static binary; producing the archive is the
            // load-bearing first step (proves the toolchain works).
            // The final link step (musl crt1 + libc.a + libbusybox.a
            // -> ELF) is a follow-up: it needs the kernel-side ELF
            // loader (#472) wired enough to give us a usable target,
            // and a host `ld` invocation that emits a Linux ELF (vs
            // the host's default PE32+/Mach-O), which is more
            // toolchain plumbing than this commit's "prove the build
            // wiring" scope.
            println!(
                "cargo:rustc-link-search=native={}",
                out_dir.display(),
            );
            println!("cargo:rustc-cfg=busybox_built");
            println!(
                "cargo:warning=busybox: built libbusybox.a ({} sources, {} applets enabled) under {} — final ELF link is a #527 follow-up",
                sources.len(),
                chosen_applets.len(),
                out_dir.display(),
            );
            Ok(())
        }
        Err(e) => Err(format!("{}", e)),
    }
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("path under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((format!("/{}", rel), path));
        }
    }
}
