// crates/arest-kernel/build.rs
//
// Emits `$OUT_DIR/ui_assets.rs` with a static table of the ui.do
// static bundle (`apps/ui.do/dist/`). Each entry is
// `(http_path, &[u8])` where `http_path` is the leading-slash URL
// (e.g. `/index.html`, `/assets/index-DjXaD7eJ.js`) and the byte
// slice comes from `include_bytes!` pointed at an absolute path on
// the build machine.
//
// When `apps/ui.do/dist/` is missing (fresh clone, tests not run,
// Docker context that didn't copy the bundle), the table is empty.
// `src/assets.rs` falls through to `None` in that case and the
// handler keeps serving the legacy plaintext banner.
//
// Also emits `$OUT_DIR/doom_assets.rs` with the baked Doom-WASM blob
// (`doom_assets/doom.wasm`) as a `pub static DOOM_WASM: &[u8]` for
// the doom host-shim in src/doom.rs (#372). Follows the same
// include_bytes!-of-canonicalized-absolute-path pattern as the UI
// bundle so Windows/Linux both resolve the literal identically.
// Absent binary -> `DOOM_WASM: &[u8] = &[]` so the crate still
// compiles on a fresh clone; callers check `DOOM_WASM.is_empty()`.
//
// Also emits `$OUT_DIR/doom_wad.rs` with the baked Doom IWAD blob
// (`doom_assets/doom1.wad`) as a `pub static DOOM_WAD: &[u8]` for
// the doom host-shim's `wad_sizes` / `read_wads` trampolines (#383).
// Same absent-file fallback as `DOOM_WASM`: missing WAD -> empty slice,
// at which point `wad_sizes` falls through to returning `(0, 0)` and
// the baked `doom.wasm` guest uses its internally-embedded Shareware
// WAD. The IWAD is the id Software DOOM 1 Shareware v1.9 WAD,
// redistributable gratis per id's 1993 shareware license — see
// doom_assets/README.md for provenance and license notes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Repo layout: crates/arest-kernel/ → ../../apps/ui.do/dist/
    let dist = manifest_dir
        .join("..").join("..")
        .join("apps").join("ui.do").join("dist");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
        entries.sort_by(|a, b| a.0.cmp(&b.0));
    } else {
        println!(
            "cargo:warning=apps/ui.do/dist not found at {} — kernel will boot without the UI bundle",
            dist.display(),
        );
    }

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str("pub static UI_ASSETS: &[(&str, &[u8])] = &[\n");
    for (http_path, fs_path) in &entries {
        let abs = abs_include_path(fs_path);
        out.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            http_path, abs,
        ));
    }
    out.push_str("];\n");

    let out_path = out_dir.join("ui_assets.rs");
    fs::write(&out_path, out).expect("write ui_assets.rs");

    // --- doom.wasm (#372) ---------------------------------------------
    // doom_assets/doom.wasm is staged out-of-band (downloaded from
    // github.com/jacobenget/doom.wasm releases or built from source —
    // see doom_assets/README.md for provenance). If the file is
    // absent (fresh clone, Docker context that didn't copy it, or
    // user-declined GPL inclusion), emit an empty slice so the crate
    // still compiles and `DOOM_WASM.is_empty()` reports the absence
    // to runtime callers.
    let doom_wasm = manifest_dir.join("doom_assets").join("doom.wasm");
    let mut doom_out = String::new();
    doom_out.push_str("// Generated by build.rs — do not edit.\n");
    // `#[allow(dead_code)]` guards against the pre-#376 state where
    // `doom_bin::DOOM_WASM` is declared but no caller has wired up
    // `wasmi::Module::new(&engine, DOOM_WASM)` yet. Matches the
    // scaffold-first discipline the rest of the doom host-shim uses
    // (src/doom.rs's `bind_doom_imports` is similarly unreferenced
    // from kernel_run today).
    doom_out.push_str("#[allow(dead_code)]\n");
    if doom_wasm.is_file() {
        let abs = abs_include_path(&doom_wasm);
        doom_out.push_str(&format!(
            "pub static DOOM_WASM: &[u8] = include_bytes!(\"{}\");\n",
            abs,
        ));
        println!("cargo:rerun-if-changed={}", doom_wasm.display());
    } else {
        println!(
            "cargo:warning=doom_assets/doom.wasm not found at {} — DOOM_WASM will be empty",
            doom_wasm.display(),
        );
        doom_out.push_str("pub static DOOM_WASM: &[u8] = &[];\n");
    }
    let doom_out_path = out_dir.join("doom_assets.rs");
    fs::write(&doom_out_path, doom_out).expect("write doom_assets.rs");

    // --- doom1.wad (#383) --------------------------------------------
    // Parallels the doom.wasm bake above. `doom_assets/doom1.wad` is
    // the id Software DOOM 1 Shareware v1.9 IWAD (4,196,020 bytes,
    // sha256 1d7d43be501e67d927e415e0b8f3e29c3bf33075e859721816f652a526cac771
    // — see doom_assets/README.md for the source URL and license
    // note). When present, the `DOOM_WAD` byte slice is the WAD's
    // contents; `KernelDoomHost::wad_sizes` reports its length and
    // `read_wads` copies it into guest memory so Doom loads the real
    // IWAD instead of falling back to the copy embedded in the baked
    // doom.wasm blob.
    //
    // Absent WAD -> empty slice, and the shim's `wad_sizes` short-
    // circuits to `(0, 0)` which makes doom.wasm use its internally-
    // embedded Shareware WAD (per doom_wasm.h "If numberOfWads remains
    // 0, Doom loads shareware WAD"). This keeps fresh clones compiling
    // without the WAD staged — same contract as DOOM_WASM.
    let doom_wad = manifest_dir.join("doom_assets").join("doom1.wad");
    let mut wad_out_src = String::new();
    wad_out_src.push_str("// Generated by build.rs — do not edit.\n");
    // `#[allow(dead_code)]` mirrors `DOOM_WASM`'s guard: the WAD
    // byte slice is only reached from the wasmi-gated host-shim
    // (`KernelDoomHost::wad_sizes` / `read_wads`), which is itself
    // not yet invoked from `kernel_run` under the pre-#376 state.
    // Dropping the allow is a one-line follow-up once the Doom
    // module actually instantiates.
    wad_out_src.push_str("#[allow(dead_code)]\n");
    if doom_wad.is_file() {
        let abs = abs_include_path(&doom_wad);
        wad_out_src.push_str(&format!(
            "pub static DOOM_WAD: &[u8] = include_bytes!(\"{}\");\n",
            abs,
        ));
        println!("cargo:rerun-if-changed={}", doom_wad.display());
    } else {
        println!(
            "cargo:warning=doom_assets/doom1.wad not found at {} — DOOM_WAD will be empty",
            doom_wad.display(),
        );
        wad_out_src.push_str("pub static DOOM_WAD: &[u8] = &[];\n");
    }
    let wad_out_path = out_dir.join("doom_wad.rs");
    fs::write(&wad_out_path, wad_out_src).expect("write doom_wad.rs");

    // --- Slint UI compile (#436 / #452) ------------------------------
    //
    // Track QQQ #452 follow-up to MMM's #436 (commit `0b32b17`):
    // `slint-build` is now an unconditional `[build-dependencies]`
    // entry (see Cargo.toml), so the build script can finally invoke
    // the slint compiler for real. That replaces MMM's
    // `slint::slint!{}` proc-macro workaround in
    // `arch/uefi/slint_backend.rs`, which couldn't reach
    // `EmbedForSoftwareRenderer` (the proc-macro path doesn't enable
    // the `software-renderer` feature on `i-slint-compiler`) and
    // therefore couldn't bake bitmap fonts at compile time.
    //
    // Compile entry: `ui/AppShell.slint`. AppShell's transitive
    // imports (theme.slint + every component under ui/components/)
    // get pulled in by the slint compiler's import resolver; we don't
    // need to enumerate them. slint-build emits one
    // `cargo:rerun-if-changed=` line per .slint file it touches +
    // one per font/image resource it embeds, so we don't need a
    // separate watch loop for those either.
    //
    // `EmbedResourcesKind::EmbedForSoftwareRenderer` is the no_std-
    // friendly font path: the compiler pre-rasterises glyph atlases
    // (or SDF, behind the `sdf-fonts` feature) for every character +
    // size + weight referenced by the design system, embeds them as
    // `BitmapFont` statics, and emits
    // `Renderer::register_bitmap_font(&BITMAP_FONT_DATA)` calls into
    // each component's init code. `register_bitmap_font` is the only
    // font registration entry point on `i_slint_core::renderer::Renderer`
    // that does NOT require the `systemfonts` feature (which would
    // pull in `parley`/`fontique`/`std::fs` and break `no_std`). The
    // glyph data is selected by the host build's `fontique` against
    // the family names declared in the .slint files (`Inter` and
    // `JetBrains Mono` per Track YY / #432); when the host has those
    // families installed (rsms/inter, JetBrains/JetBrainsMono OFL
    // fonts vendored under `assets/fonts/`), the embedded atlases are
    // a perfect match. When the host falls back to a system Sans-
    // Serif, the design-system spelling stays correct but the
    // rendered glyph shapes follow the host fallback — acceptable for
    // the boot UI since the only on-screen text pre-#431 is the
    // AppShell title bar + status footer (`AREST` / `Ready`).
    //
    // The vendored TTF bytes in `crate::fonts` (Track JJJ #433) stay
    // exposed as `pub static &[u8]` slices for any future runtime path
    // that needs raw font bytes (e.g. shaping a custom glyph set
    // outside the Slint pipeline) — they are unused by the embedded-
    // glyph path because `register_bitmap_font` consumes pre-
    // rasterised data, not TrueType.
    let ui_dir = manifest_dir.join("ui");
    if ui_dir.is_dir() {
        // Compile entry: `ui/apps/HateoasBrowser.slint` (Track SSS #429).
        //
        // Why HateoasBrowser is the compile entry instead of AppShell:
        // `slint::include_modules!()` is keyed off a single
        // `SLINT_INCLUDE_GENERATED` env var that `slint_build::
        // compile_with_config` rewrites on every call (see
        // slint-build/lib.rs L535 in v1.16.1) — only the LAST
        // compiled file is reachable through `include_modules!()`. To
        // keep both `AppShell` (Track MMM #436's root) and
        // `HateoasBrowser` (this commit) reachable from the single
        // `slint::include_modules!()` site in
        // `arch/uefi/slint_backend.rs`, the new file is the compile
        // entry: it imports + re-exports AppShell so AppShell stays
        // emitted into the same generated `.rs` (the slint compiler
        // walks the full import graph and codegens every reachable
        // exported component).
        //
        // If a future track adds a third app, it should follow the
        // same pattern — add itself to a master entry .slint that
        // re-exports the previous entries, and update the path here.
        // (Or refactor to `compile_with_output_path` and synthesise
        // a top-level shim in build.rs that `mod`s every generated
        // file by name; see slint-build L551 for that API.)
        let entry = ui_dir.join("apps").join("HateoasBrowser.slint");
        let app_shell_fallback = ui_dir.join("AppShell.slint");
        if entry.is_file() {
            let config = slint_build::CompilerConfiguration::new()
                .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer);
            slint_build::compile_with_config("ui/apps/HateoasBrowser.slint", config)
                .expect("slint_build::compile_with_config(ui/apps/HateoasBrowser.slint) failed");
        } else if app_shell_fallback.is_file() {
            // Fallback to the pre-#429 entry point so a hypothetical
            // future revert (or a partial checkout that drops
            // ui/apps/) still lands a usable AppShell into
            // `slint::include_modules!()`.
            let config = slint_build::CompilerConfiguration::new()
                .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer);
            slint_build::compile_with_config("ui/AppShell.slint", config)
                .expect("slint_build::compile_with_config(ui/AppShell.slint) failed");
        } else {
            println!(
                "cargo:warning=neither ui/apps/HateoasBrowser.slint nor ui/AppShell.slint found under {} — skipping slint-build invocation",
                ui_dir.display(),
            );
        }
    }
    // Watch the vendored fonts (#433) directory. slint-build emits
    // `rerun-if-changed` for each individual TTF it actually embeds
    // (the host fontique matches against the family names in the
    // .slint files); this loop adds the directory contents as a
    // belt-and-braces measure so swapping a font file in place
    // re-triggers the build even if the compiler's last invocation
    // didn't see it (e.g. a future ttf added but not yet referenced
    // by any .slint file).
    let fonts_dir = manifest_dir.join("assets").join("fonts");
    if fonts_dir.is_dir() {
        for entry in fs::read_dir(&fonts_dir).into_iter().flatten().flatten() {
            let p = entry.path();
            if p.extension().and_then(|e| e.to_str()) == Some("ttf") {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }
    // Watch the Lucide SVGs (#434) — `@image-url` references in
    // .slint files cause the compiler to embed the rasterised SVG.
    let icons_dir = manifest_dir.join("assets").join("icons").join("lucide");
    if icons_dir.is_dir() {
        for entry in fs::read_dir(&icons_dir).into_iter().flatten().flatten() {
            let p = entry.path();
            if p.extension().and_then(|e| e.to_str()) == Some("svg") {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }

    // Re-run whenever the bundle changes.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());
    for (_, p) in &entries {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    // Pick up the binary being added or removed between builds even
    // if it never existed on the first run (rerun-if-changed on a
    // non-existent path still triggers when the path later appears).
    println!("cargo:rerun-if-changed={}", doom_wasm.display());
    println!("cargo:rerun-if-changed={}", doom_wad.display());
}

/// Convert a filesystem path into a form accepted by rustc's
/// `include_bytes!` macro:
///   * canonicalize to resolve any `..` / symlinks,
///   * normalize backslashes to forward slashes (Windows),
///   * strip the `\\?\` UNC prefix that `Path::canonicalize` adds
///     on Windows, which rustc does not accept inside a string
///     literal passed to `include_bytes!`.
fn abs_include_path(path: &Path) -> String {
    let abs = path
        .canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .replace('\\', "/");
    abs.strip_prefix("//?/").unwrap_or(&abs).to_string()
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("path under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((format!("/{}", rel), path));
        }
    }
}
