// crates/arest-kernel/build.rs
//
// Emits `$OUT_DIR/ui_assets.rs` with a static table of the ui.do
// static bundle (`apps/ui.do/dist/`). Each entry is
// `(http_path, &[u8])` where `http_path` is the leading-slash URL
// (e.g. `/index.html`, `/assets/index-DjXaD7eJ.js`) and the byte
// slice comes from `include_bytes!` pointed at an absolute path on
// the build machine.
//
// When `apps/ui.do/dist/` is missing (fresh clone, tests not run,
// Docker context that didn't copy the bundle), the table is empty.
// `src/assets.rs` falls through to `None` in that case and the
// handler keeps serving the legacy plaintext banner.
//
// Also emits `$OUT_DIR/doom_assets.rs` with the baked Doom-WASM blob
// (`doom_assets/doom.wasm`) as a `pub static DOOM_WASM: &[u8]` for
// the doom host-shim in src/doom.rs (#372). Follows the same
// include_bytes!-of-canonicalized-absolute-path pattern as the UI
// bundle so Windows/Linux both resolve the literal identically.
// Absent binary -> `DOOM_WASM: &[u8] = &[]` so the crate still
// compiles on a fresh clone; callers check `DOOM_WASM.is_empty()`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Repo layout: crates/arest-kernel/ → ../../apps/ui.do/dist/
    let dist = manifest_dir
        .join("..").join("..")
        .join("apps").join("ui.do").join("dist");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
        entries.sort_by(|a, b| a.0.cmp(&b.0));
    } else {
        println!(
            "cargo:warning=apps/ui.do/dist not found at {} — kernel will boot without the UI bundle",
            dist.display(),
        );
    }

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str("pub static UI_ASSETS: &[(&str, &[u8])] = &[\n");
    for (http_path, fs_path) in &entries {
        let abs = abs_include_path(fs_path);
        out.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            http_path, abs,
        ));
    }
    out.push_str("];\n");

    let out_path = out_dir.join("ui_assets.rs");
    fs::write(&out_path, out).expect("write ui_assets.rs");

    // --- doom.wasm (#372) ---------------------------------------------
    // doom_assets/doom.wasm is staged out-of-band (downloaded from
    // github.com/jacobenget/doom.wasm releases or built from source —
    // see doom_assets/README.md for provenance). If the file is
    // absent (fresh clone, Docker context that didn't copy it, or
    // user-declined GPL inclusion), emit an empty slice so the crate
    // still compiles and `DOOM_WASM.is_empty()` reports the absence
    // to runtime callers.
    let doom_wasm = manifest_dir.join("doom_assets").join("doom.wasm");
    let mut doom_out = String::new();
    doom_out.push_str("// Generated by build.rs — do not edit.\n");
    // `#[allow(dead_code)]` guards against the pre-#376 state where
    // `doom_bin::DOOM_WASM` is declared but no caller has wired up
    // `wasmi::Module::new(&engine, DOOM_WASM)` yet. Matches the
    // scaffold-first discipline the rest of the doom host-shim uses
    // (src/doom.rs's `bind_doom_imports` is similarly unreferenced
    // from kernel_run today).
    doom_out.push_str("#[allow(dead_code)]\n");
    if doom_wasm.is_file() {
        let abs = abs_include_path(&doom_wasm);
        doom_out.push_str(&format!(
            "pub static DOOM_WASM: &[u8] = include_bytes!(\"{}\");\n",
            abs,
        ));
        println!("cargo:rerun-if-changed={}", doom_wasm.display());
    } else {
        println!(
            "cargo:warning=doom_assets/doom.wasm not found at {} — DOOM_WASM will be empty",
            doom_wasm.display(),
        );
        doom_out.push_str("pub static DOOM_WASM: &[u8] = &[];\n");
    }
    let doom_out_path = out_dir.join("doom_assets.rs");
    fs::write(&doom_out_path, doom_out).expect("write doom_assets.rs");

    // Re-run whenever the bundle changes.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());
    for (_, p) in &entries {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    // Pick up the binary being added or removed between builds even
    // if it never existed on the first run (rerun-if-changed on a
    // non-existent path still triggers when the path later appears).
    println!("cargo:rerun-if-changed={}", doom_wasm.display());
}

/// Convert a filesystem path into a form accepted by rustc's
/// `include_bytes!` macro:
///   * canonicalize to resolve any `..` / symlinks,
///   * normalize backslashes to forward slashes (Windows),
///   * strip the `\\?\` UNC prefix that `Path::canonicalize` adds
///     on Windows, which rustc does not accept inside a string
///     literal passed to `include_bytes!`.
fn abs_include_path(path: &Path) -> String {
    let abs = path
        .canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .replace('\\', "/");
    abs.strip_prefix("//?/").unwrap_or(&abs).to_string()
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("path under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((format!("/{}", rel), path));
        }
    }
}
