"""The include! equivalent for the Java host: byte-wrap each shared intersection
file into varargs method bodies (T <bytes> ;) inside the generated Canon.java.
The element bytes are verbatim -- the same bytes CPython execs, rustc tokenizes,
and the C# host wraps; only the commas BETWEEN top-level elements are the
generator's, so it can slice one tuple across several methods.

Why slicing: Java caps a single method at 64KB of BYTECODE. The four production
files now live in ONE shared file (arest.canon, 325 defs); wrapped as a single
method it overflows (the old per-file loadSystem at 223 defs compiled, a lone
325-def loadArest does not). So arest.canon is emitted as consecutive
loadArest_k() calls over slices of the SAME top-level element sequence, in
order -- DEF's registration side effect makes the split invisible. scenarios
(70 defs) still fits one method. Run from java/."""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# each method stays well under Java's 64KB bytecode ceiling; the heaviest
# single pre-merge method (system, 223 defs) compiled, so slices this size
# carry ample margin.
CHUNK = 100


def read_shared(name):
    return open(os.path.join(ROOT, "shared", name), encoding="utf-8").read()


def top_level_elements(text):
    """The top-level element substrings of ONE canon tuple literal, split only
    at depth-0 commas outside double-quoted strings (\\-escapes honoured). No
    element's bytes are altered; the outer parens become the T(...) call's."""
    s = text.strip()
    assert s[0] == "(" and s[-1] == ")", "not a tuple literal"
    inner = s[1:-1]
    elems = []
    depth = instr = esc = 0
    start = 0
    for i, ch in enumerate(inner):
        if instr:
            if esc:
                esc = 0
            elif ch == "\\":
                esc = 1
            elif ch == '"':
                instr = 0
            continue
        if ch == '"':
            instr = 1
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            elems.append(inner[start:i])
            start = i + 1
    elems.append(inner[start:])
    return elems


out = io.StringIO()
out.write("// GENERATED by gen_canon.py: the shared bytes, wrapped. Do not edit.\n")
out.write("package arest;\n\nimport static arest.Vocab.*;\n\n")
out.write("public class Canon {\n")

# the merged production canon, sliced across sub-64KB methods
elems = top_level_elements(read_shared("arest.canon"))
nchunks = (len(elems) + CHUNK - 1) // CHUNK
for c in range(nchunks):
    part = elems[c * CHUNK:(c + 1) * CHUNK]
    out.write("    static void loadArest_%d() { T(" % c)
    out.write(",".join(part))
    out.write("); }\n\n")
out.write("    public static Object loadArest() {\n")
for c in range(nchunks):
    out.write("        loadArest_%d();\n" % c)
out.write("        return null;\n    }\n\n")

# the case table still fits one method
out.write("    public static Object loadScenarios() { return T\n")
out.write(read_shared("scenarios.canon"))
out.write("\n; }\n\n")

out.write("""    public static java.util.List<Object[]> loadAll() {
        Vocab.DEFS.clear();
        loadArest();
        return Vocab.DEFS;
    }

    public static java.util.List<Object[]> loadScenarioDefs() {
        Vocab.DEFS.clear();
        loadScenarios();
        return new java.util.ArrayList<Object[]>(Vocab.DEFS);
    }
}
""")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Canon.java")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(out.getvalue())
print(path)
