"""The include! equivalent for the Java host: byte-concatenate each shared
intersection file into a varargs method body (return T <file bytes> ;) inside
the generated Canon.java. Never parses, never transforms: the same bytes
CPython execs, rustc tokenizes, and the C# host wraps. Run from java/."""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILES = [("loadTheta", "theta.canon"), ("loadConstraints", "constraints.canon"),
         ("loadAst", "ast.canon"), ("loadSystem", "system.canon"),
         ("loadScenarios", "scenarios.canon")]

out = io.StringIO()
out.write("// GENERATED by gen_canon.py: the shared bytes, wrapped. Do not edit.\n")
out.write("package arestlam;\n\nimport static arestlam.Vocab.*;\n\n")
out.write("public class Canon {\n")
for method, fname in FILES:
    body = open(os.path.join(ROOT, "shared", fname), encoding="utf-8").read()
    out.write("    public static Object %s() { return T\n" % method)
    out.write(body)
    out.write("\n; }\n\n")
out.write("""    public static java.util.List<Object[]> loadAll() {
        Vocab.DEFS.clear();
        loadTheta();
        loadConstraints();
        loadAst();
        loadSystem();
        return Vocab.DEFS;
    }

    public static java.util.List<Object[]> loadScenarioDefs() {
        Vocab.DEFS.clear();
        loadScenarios();
        return new java.util.ArrayList<Object[]>(Vocab.DEFS);
    }
}
""")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Canon.java")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(out.getvalue())
print(path)
