// crates/arest-kernel/src/ui_apps/doom.rs
//
// Doom — Rust glue for the third launchable Slint app
// (#455 Track VVV).
//
// Bridges the existing `crate::doom` host shim (#270/#271, scaffolded
// across Tracks B/D/G/H/JJ/HH and finalised by #376/#384) to the
// `Doom` Slint component generated by `slint::include_modules!()`
// from `ui/apps/Doom.slint`. Mirrors the constructor shape Track SSS
// (#429 / `ui_apps::hateoas`) and Track TTT (#430 / `ui_apps::repl`)
// landed: a `pub fn build_app() -> Result<DoomApp, slint::PlatformError>`
// that returns the constructed Window plus a small bag of state, with
// every per-frame side effect driven by a `slint::Timer` so the
// launcher's super loop (Track UUU #431) keeps `draw_if_needed`
// painting the framebuffer in step.
//
// # Why a Timer instead of the launcher's super-loop hooking
//
// The launcher's `run(...)` super-loop (`ui_apps::launcher.rs` L272+)
// calls `update_timers_and_animations` per frame. That advances every
// `slint::Timer` Slint knows about, so a `Timer::single_shot` style
// repeating timer set to ~28 ms (35 Hz, matching Doom's tic rate)
// fires once per launcher iteration without the launcher having to
// know anything about Doom. This keeps `launcher.rs`'s navigation
// logic agnostic of which app is showing — it just shows / hides a
// Window, drains the keyboard ring (with Esc-intercept), and lets
// the active app's own Timer run the work. Same pattern any future
// app with a per-frame loop would use.
//
// # Init policy: instantiate once, cache for re-launches
//
// First call to `build_app()`:
//   1. Build a `wasmi::Engine` with `consume_fuel(true)` (matches
//      `entry_uefi.rs`'s smoke shape so wasmi accepts `Store::set_fuel`
//      calls under the same engine config).
//   2. Parse `crate::doom_bin::DOOM_WASM` into a `wasmi::Module`.
//      Empty (fresh-clone) -> the constructor returns Ok with the
//      window but the per-frame loop runs in an idle "WASM absent"
//      mode; the user sees the splash background and a footer hint.
//   3. Construct a `wasmi::Store<SlintDoomHost>` with the captured-
//      frame host. Fuel is initialised to `INSTANTIATE_FUEL`.
//   4. Bind all 10 host imports via `crate::doom::bind_doom_imports`
//      (the trait-generic helper accepts any `T: DoomHost + 'static`).
//   5. `linker.instantiate_and_start(&mut store, &module)` — same
//      shape `entry_uefi.rs` already uses.
//   6. Refill fuel and call `initGame` once. After this returns the
//      guest is ready for the per-tic `tickGame` pump.
//
// Subsequent re-launches (user hits Esc back to launcher and clicks
// Doom again): the `DoomApp`'s state is constructed once and held
// for the lifetime of the launcher (see `launcher.rs`'s
// `doom_app = doom::build_app().expect(...)` at startup — same shape
// as `repl_app` and `hateoas_window`). Showing/hiding the Window does
// not destroy the wasmi store, so the game state survives a
// back-and-forth navigation. Quitting (Esc) suspends the per-frame
// timer (it keeps firing but does nothing useful when the Window is
// hidden — Slint's `draw_if_needed` is a no-op in that state, and
// `pump_keys_into_guest` reads the ring drained by the launcher's
// `drain_keyboard_with_esc_intercept` so the guest sees no input
// while not active).
//
// # Frame capture: WHY a separate SlintDoomHost vs reusing
// KernelDoomHost
//
// `KernelDoomHost::draw_frame` (src/doom.rs L442) blits the guest's
// 640x400 BGRA frame straight onto the kernel framebuffer via
// `framebuffer::with_back(...).blit_doom_frame(...)` and presents.
// That's the path the boot smoke uses — the Doom output lands
// directly on the GOP MMIO before any UI launcher comes up.
//
// Inside the launcher we want the same bytes inside a Slint Image,
// not on the framebuffer directly: the launcher's super-loop owns
// the framebuffer (via `FramebufferBackend` + Slint's software
// renderer) and any direct framebuffer writes would be clobbered on
// the next `draw_if_needed` call. So `SlintDoomHost::draw_frame`
// captures the BGRA bytes into a shared `Vec<u8>` (the back buffer
// of the captured frame); the per-frame loop then converts that
// BGRA into RGBA (R<->B swap, alpha forced to 0xFF for opaqueness)
// inside a `slint::SharedPixelBuffer<Rgba8Pixel>`, wraps it as
// `slint::Image::from_rgba8`, and sets the Slint Image's `frame`
// property. Slint's software renderer then composes the RGBA image
// into the Window's surface at next `draw_if_needed`.
//
// Pixel layout citation (per src/doom.rs L208-219 / L442-460): the
// guest writes the 640x400 frame as `[B, G, R, A]` in memory — the
// little-endian form of Doom's `0xAARRGGBB`, total 1_024_000 bytes.
// `slint::Rgba8Pixel` is `rgb::RGBA8` (`{r, g, b, a}` in declaration
// order, matching `[R, G, B, A]` in memory). The conversion is a
// per-pixel swap of bytes 0 and 2, plus forcing the alpha byte to
// 0xFF (Doom's alpha is 0xFF for opaque pixels per the `0xAARRGGBB`
// convention but explicit makes the visual deterministic across any
// future format drift inside the WASM).

#![allow(dead_code)]

use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
#[cfg(test)]
use alloc::vec;
use alloc::vec::Vec;
use core::cell::RefCell;
use core::time::Duration;

use slint::{ComponentHandle, Image, Rgba8Pixel, SharedPixelBuffer, SharedString, Timer, TimerMode};
use wasmi::{Engine, Instance, Linker, Module, Store};

use pc_keyboard::DecodedKey;

use crate::arch::uefi::keyboard;
use crate::arch::uefi::slint_backend::Doom as DoomWindow;
use crate::doom::{DoomHost, bind_doom_imports, translate_decoded_key};

/// Doom guest framebuffer dimensions. Hard-coded by the WASM build
/// (`DOOMGENERIC_RESX` x `DOOMGENERIC_RESY`); the host imports the
/// `(width, height)` pair via `loading.onGameInit` for verification
/// but never re-shapes anything below.
const DOOM_W: u32 = 640;
const DOOM_H: u32 = 400;
/// Bytes per Doom frame — 640 * 400 * 4 (BGRA8888) = 1_024_000.
const DOOM_FRAME_LEN: usize = (DOOM_W as usize) * (DOOM_H as usize) * 4;

/// Per-call wasmi fuel budget. Sized to cover both the cold-cache
/// `instantiate_and_start` + `initGame` path (which empirically takes
/// a few tens of millions of wasmi instructions, see `entry_uefi.rs`
/// L1025-L1034) and a steady-state `tickGame` (which usually consumes
/// well below 10M but spikes around level transitions and audio
/// init). 200M leaves comfortable headroom in both cases. Each
/// top-level call refills fuel before invoking, so this is the
/// per-call cap rather than a cumulative ceiling.
const DOOM_FUEL: u64 = 200_000_000;

/// 35 Hz target tic rate — Doom's canonical loop frequency. The
/// `slint::Timer` granularity is millisecond, so 28 ms is the
/// closest integer divisor (1000 / 35 ≈ 28.57). Drift across many
/// frames is acceptable: Doom's internal time accounting is anchored
/// on `runtimeControl.timeInMilliseconds`, which the host wires to
/// the PIT 1 kHz IRQ counter (see `crate::doom::KernelDoomHost::
/// time_in_milliseconds`), so the guest-side game logic stays
/// honest regardless of how often the host calls `tickGame`.
const TIC_INTERVAL: Duration = Duration::from_millis(28);

/// Captured 640x400 BGRA frame, shared between the host shim
/// (`SlintDoomHost::draw_frame` writes here) and the per-frame
/// timer (`tic` reads here, converts BGRA->RGBA, and re-binds the
/// Slint Image).
///
/// Wrapped in `Rc<RefCell<...>>` so the wasmi `Store<SlintDoomHost>`
/// (which owns one clone of the `Rc` via the embedded
/// `SlintDoomHost`) and the per-frame timer (which captures another
/// clone) can each access the buffer. The kernel's
/// `unsafe-single-threaded` slint feature (Cargo.toml feature list)
/// makes the lack of `Send` / `Sync` on `Rc<RefCell>` sound — boot
/// is single-threaded.
type CapturedFrame = Rc<RefCell<FrameBuffer>>;

/// Latest frame the guest's `drawFrame` host import handed us, plus
/// a generation counter so the per-frame timer can skip the channel-
/// swap + Image re-bind when nothing changed since the previous tic.
struct FrameBuffer {
    /// 1_024_000 bytes of `[B, G, R, A]`-in-memory Doom output.
    /// Allocated once at construction; `draw_frame` overwrites in
    /// place to keep allocator churn bounded (the boot heap survives
    /// 35 MB/s of `Vec::new` + drop, but reusing this slot drops the
    /// allocator pressure to zero per frame). Empty (`Vec::new()`)
    /// before the guest's first `drawFrame` lands.
    bgra: Vec<u8>,
    /// Bumped each time `draw_frame` overwrites `bgra`. The per-frame
    /// timer compares against the last-seen generation and skips the
    /// per-pixel R<->B swap when no new frame arrived (saves
    /// 1_024_000-byte memcpy + alloc when the guest's `tickGame`
    /// returned without producing a frame, which is the common case
    /// when `D_DoomLoop` is waiting on a pending input event).
    generation: u64,
}

impl FrameBuffer {
    fn new() -> Self {
        Self { bgra: Vec::new(), generation: 0 }
    }
}

/// Captured-frame variant of `crate::doom::KernelDoomHost`. Instead
/// of blitting `drawFrame` straight onto the kernel framebuffer (the
/// kernel-host's behaviour, which would race the launcher's
/// software-renderer surface), this implementation copies the BGRA
/// bytes into the shared `CapturedFrame` so the per-frame timer can
/// re-bind them as a `slint::Image`. Every other host import
/// delegates to a private `KernelDoomHost` field so the save-game
/// pipeline (#375), WAD pump (#383), key translation (#377), and
/// console message routing (#384) all stay live without re-
/// implementation here.
struct SlintDoomHost {
    /// Embedded kernel host — handles every import that doesn't
    /// touch the framebuffer (save game, WADs, time, console).
    inner: crate::doom::KernelDoomHost,
    /// Shared buffer the per-frame timer reads from. Cloned from
    /// the `DoomApp::frame` `Rc` so both the wasmi store and the
    /// timer see writes here.
    frame: CapturedFrame,
}

impl SlintDoomHost {
    fn new(frame: CapturedFrame) -> Self {
        Self { inner: crate::doom::KernelDoomHost::new(), frame }
    }
}

impl DoomHost for SlintDoomHost {
    fn on_game_init(&mut self, width: i32, height: i32) {
        // Forward to the kernel host so the boot serial log keeps
        // its `doom: game init` marker; useful when debugging a
        // Doom-launches-but-no-frame scenario.
        self.inner.on_game_init(width, height);
    }

    fn wad_sizes(&mut self) -> (u32, u32) {
        self.inner.wad_sizes()
    }

    fn read_wads(&mut self, wad_out: &mut [u8], lengths_out: &mut [i32]) {
        self.inner.read_wads(wad_out, lengths_out);
    }

    fn time_in_milliseconds(&mut self) -> i64 {
        self.inner.time_in_milliseconds()
    }

    fn draw_frame(&mut self, frame: &[u8]) {
        // Capture only — do NOT call the kernel host's `draw_frame`
        // (which would blit through `framebuffer::with_back` and
        // race the launcher's software-renderer surface). The per-
        // frame timer (`tic`) reads this buffer, converts BGRA ->
        // RGBA, and re-binds it as a `slint::Image` on the Slint
        // Window. Slint's software renderer then composes the
        // result into the Window's surface at the next
        // `draw_if_needed`.
        let mut buf = self.frame.borrow_mut();
        if buf.bgra.len() != frame.len() {
            // First frame (or a guest that re-shaped the surface
            // after init — not expected with the 640x400 hard-coded
            // build, but harmless to handle). Allocate to match.
            buf.bgra.resize(frame.len(), 0);
        }
        buf.bgra.copy_from_slice(frame);
        // Wrap-around at u64::MAX is pure cosmetic — at 35 Hz the
        // counter would take ~16.7 billion years to overflow.
        buf.generation = buf.generation.wrapping_add(1);
    }

    fn size_of_save_game(&mut self, gamemap: i32) -> i32 {
        self.inner.size_of_save_game(gamemap)
    }

    fn read_save_game(&mut self, gamemap: i32, out: &mut [u8]) -> i32 {
        self.inner.read_save_game(gamemap, out)
    }

    fn write_save_game(&mut self, gamemap: i32, data: &[u8]) -> i32 {
        self.inner.write_save_game(gamemap, data)
    }

    fn on_info_message(&mut self, message: &str) {
        self.inner.on_info_message(message);
    }

    fn on_error_message(&mut self, message: &str) {
        self.inner.on_error_message(message);
    }
}

/// One-time-instantiated wasmi guest. Cached on `DoomApp` so a
/// Esc-back-to-launcher-and-relaunch round-trip reuses the same
/// game state (player position, health, current level, save table
/// pointers). Recreating it would re-run `initGame` from scratch
/// and lose any in-progress play.
struct DoomGuest {
    store: Store<SlintDoomHost>,
    instance: Instance,
}

/// The constructed Doom Window plus its per-frame state. Returned
/// from `build_app` so the boot UI launcher (#431 Track UUU) can
/// `show()` / `hide()` the window like any other app.
pub struct DoomApp {
    /// The Slint window. `ComponentHandle` requires the inner
    /// `Doom` component to stay alive for the duration of the
    /// event loop; `DoomApp` holds it by value to make that
    /// lifetime explicit.
    pub window: DoomWindow,
    /// Captured frame storage, shared with the embedded
    /// `SlintDoomHost` inside `guest`. The per-frame timer reads
    /// from here.
    frame: CapturedFrame,
    /// The wasmi guest, or `None` when `crate::doom_bin::DOOM_WASM`
    /// was empty at build time (fresh clone). When `None` the per-
    /// frame timer is a no-op and the Window shows a placeholder
    /// background.
    guest: Rc<RefCell<Option<DoomGuest>>>,
    /// Per-frame timer (35 Hz target). Held by value so its drop
    /// at end-of-life cancels the closure cleanly. The closure
    /// captures clones of `frame`, `guest`, and the window weak
    /// ref so the timer can run independently of any caller's
    /// borrow state.
    _tic_timer: Timer,
}

impl DoomApp {
    /// True iff the WASM module was baked into this build (i.e.
    /// `DOOM_WASM` was non-empty at build time and instantiation
    /// succeeded). Useful for tests + diagnostics.
    pub fn guest_alive(&self) -> bool {
        self.guest.borrow().is_some()
    }

    /// Number of frames captured from the guest so far. Bumped by
    /// `SlintDoomHost::draw_frame` each time `tickGame` produces a
    /// frame. Useful for tests + diagnostics.
    pub fn frame_generation(&self) -> u64 {
        self.frame.borrow().generation
    }

    /// Drain every pending decoded keystroke off the UEFI keyboard
    /// ring (`arch::uefi::keyboard::read_keystroke`) and dispatch
    /// each non-Esc key to the Doom guest as a synthetic
    /// press-then-release pair against `reportKeyDown` /
    /// `reportKeyUp`. Returns `true` if Escape was seen — the
    /// caller (`crate::ui_apps::launcher`) interprets that as
    /// "back to launcher" and hides the Doom window.
    ///
    /// # Why the launcher calls this instead of a per-frame timer
    ///
    /// The keyboard ring is single-consumer: `read_keystroke` is a
    /// `pop_front` and there's no peek API. If the per-frame timer
    /// drained the ring, the launcher's Esc-intercept couldn't run
    /// — the key would have already been handed to the guest's
    /// `reportKeyDown(0x1B)` call and Doom's in-game menu would
    /// open. By moving the drain to the launcher, the Esc check
    /// happens BEFORE the dispatch and the keystroke is dropped
    /// when it's the back-to-launcher signal.
    ///
    /// Mirrors the shape of `crate::doom::pump_keys_into_guest`
    /// but with the Esc filter inlined. Untranslatable keys
    /// (caps lock, F11/F12, multimedia keys) are silently dropped,
    /// same as `pump_keys_into_guest`.
    pub fn drain_keystrokes_intercept_esc(&mut self) -> bool {
        let mut esc_seen = false;
        let mut maybe_guest = self.guest.borrow_mut();
        let Some(guest) = maybe_guest.as_mut() else {
            // No guest — drain the ring anyway so leftover keys
            // don't queue up for whichever app the launcher
            // navigates to next. Esc still routes back.
            while let Some(decoded) = keyboard::read_keystroke() {
                if matches!(decoded, DecodedKey::Unicode('\u{001B}')) {
                    esc_seen = true;
                }
            }
            return esc_seen;
        };

        // Resolve both exports once per drain. `get_typed_func`
        // validates the (param, result) shape against the imported
        // binary; a signature drift would surface as Err here, in
        // which case we drop every keystroke for this drain pass
        // and let the next call retry. Esc routing still works on
        // the missing-export path.
        let report_down = match guest
            .instance
            .get_typed_func::<i32, ()>(&guest.store, "reportKeyDown")
        {
            Ok(f) => Some(f),
            Err(_) => None,
        };
        let report_up = match guest
            .instance
            .get_typed_func::<i32, ()>(&guest.store, "reportKeyUp")
        {
            Ok(f) => Some(f),
            Err(_) => None,
        };

        while let Some(decoded) = keyboard::read_keystroke() {
            // Esc is the back-to-launcher signal. Drop it; do not
            // forward to the guest. We still keep draining so a
            // burst of input doesn't leak into the about-to-be-
            // hidden window.
            if matches!(decoded, DecodedKey::Unicode('\u{001B}')) {
                esc_seen = true;
                continue;
            }
            // Esc-already-seen mode: drain the rest of the ring
            // without dispatch (matches the
            // `drain_keyboard_with_esc_intercept` policy in
            // launcher.rs — once Esc fires, the rest of the burst
            // is implicitly stale).
            if esc_seen {
                continue;
            }
            let Some(doom_key) = translate_decoded_key(decoded) else {
                // Untranslatable — drop without dispatch.
                continue;
            };
            let key_i32 = doom_key as i32;
            // Down then up — synthesize a tap. Same workaround
            // documented in `crate::doom::pump_keys_into_guest`'s
            // module-level "Press/release fidelity gap" comment:
            // the keyboard ring stores `DecodedKey` post-
            // translation with no Down/Up state, so we can't
            // dispatch real edges without Track EE growing a
            // sibling `KeyEvent` ring (#377 follow-up).
            if let (Some(down), Some(up)) = (report_down.as_ref(), report_up.as_ref()) {
                if let Err(e) = down.call(&mut guest.store, key_i32) {
                    crate::println!("doom: reportKeyDown({key_i32}): {e}");
                    break;
                }
                if let Err(e) = up.call(&mut guest.store, key_i32) {
                    crate::println!("doom: reportKeyUp({key_i32}): {e}");
                    break;
                }
            }
        }
        esc_seen
    }
}

/// Construct the Doom Window + wasmi guest, bind the per-frame
/// timer.
///
/// The Slint platform must be installed before this is called
/// (`slint::platform::set_platform(Box::new(UefiSlintPlatform::new(...)))`)
/// — Slint refuses to instantiate components otherwise. The
/// launcher's `run()` does that on its first call before reaching
/// `build_app()`.
///
/// The window is *not* shown here; the caller (launcher) drives
/// the Slint-side show/hide based on user navigation. Same shape
/// as `ui_apps::repl::build_app` and `ui_apps::hateoas::build_app`.
///
/// Failure modes:
///   * `slint::PlatformError` from `DoomWindow::new()` — propagated
///     to the caller so the launcher can decide whether to abort
///     boot or fall through to a degraded splash.
///   * wasmi instantiation / `initGame` failure — caught locally:
///     the window is still constructed and the user can navigate
///     to it; the surface stays blank with a footer hint about
///     the failure. This keeps a partial-build path observable.
pub fn build_app() -> Result<DoomApp, slint::PlatformError> {
    let window = DoomWindow::new()?;
    let frame: CapturedFrame = Rc::new(RefCell::new(FrameBuffer::new()));

    // ------ wasmi guest construction ----------------------------
    // Mirrors the shape `entry_uefi.rs`'s smoke uses: same
    // `consume_fuel(true)` engine config, same `instantiate_and_start`
    // call, same `initGame` invocation. The boot smoke and this
    // app live in different `Engine` instances (engines are
    // per-Store), so there's no resource sharing — the boot smoke
    // can run all the way through and drop its store before the
    // launcher even constructs `DoomApp`.
    let guest = match instantiate_guest(frame.clone()) {
        Ok(g) => {
            window.set_status_text(SharedString::from("Doom — Esc to return"));
            Some(g)
        }
        Err(reason) => {
            // Either the WASM bake was absent (fresh clone) or
            // wasmi failed to load / initGame trapped. Surface the
            // reason in the footer so the user sees why the
            // surface is blank. Don't return Err — the Window is
            // still useful (the user can navigate back to the
            // launcher) and a partial / degraded boot is more
            // informative than a hard failure.
            crate::println!("doom: build_app: guest init skipped — {reason}");
            window.set_status_text(SharedString::from(format!(
                "Doom WASM unavailable: {reason}"
            )));
            None
        }
    };

    let guest_cell: Rc<RefCell<Option<DoomGuest>>> = Rc::new(RefCell::new(guest));

    // ------ Theme toggle hook ------------------------------------
    // Passive forward — Theme.toggle-mode() has already swapped
    // the global mode inside the Slint handler. No host-side
    // persistence yet; the callback's existence keeps the hook
    // reachable for a future ThemePref cell wire-up. Same shape
    // as Repl / HateoasBrowser / AppLauncher.
    window.on_theme_toggled(|| {});

    // ------ Per-frame timer -------------------------------------
    // 35 Hz target, repeating. Each tic:
    //   1. If the Window isn't currently visible (user is on a
    //      different app), skip — nothing to render and the
    //      kernel-side keyboard ring is being drained by whichever
    //      app the launcher has active. Pumping into Doom while
    //      it's hidden would steal keystrokes meant for other apps.
    //   2. Pump pending keystrokes into the guest via
    //      `crate::doom::pump_keys_into_guest`.
    //   3. Refill fuel and call `tickGame`. OutOfFuel is the
    //      expected yield path (the guest's `D_DoomLoop` would
    //      otherwise spin forever); other traps surface in the
    //      console via `on_error_message` already.
    //   4. If a new frame landed (generation bumped), convert
    //      BGRA -> RGBA into a `SharedPixelBuffer<Rgba8Pixel>`,
    //      wrap as `slint::Image::from_rgba8`, and set on the
    //      Window's `frame` property. The next `draw_if_needed`
    //      call paints it.
    let timer = Timer::default();
    {
        let weak = window.as_weak();
        let frame = frame.clone();
        let guest_cell = guest_cell.clone();
        // Tracks the last frame generation we've already pushed to
        // the Slint Image. Skipping the BGRA->RGBA conversion when
        // generation hasn't changed saves the per-pixel R<->B swap
        // cost (1_024_000 byte reads + writes) on idle tics.
        let last_gen: Rc<RefCell<u64>> = Rc::new(RefCell::new(0));
        timer.start(TimerMode::Repeated, TIC_INTERVAL, move || {
            let Some(window) = weak.upgrade() else { return };
            tic(&window, &frame, &guest_cell, &last_gen);
        });
    }

    Ok(DoomApp {
        window,
        frame,
        guest: guest_cell,
        _tic_timer: timer,
    })
}

/// Per-tic body, factored out of the timer closure so it can be
/// tested + traced independently. Driven exclusively by the timer
/// in `build_app`; not called from anywhere else.
///
/// Key pumping does NOT happen here — it's the launcher's job to
/// call `DoomApp::drain_keystrokes_intercept_esc` from the super-
/// loop, so Esc can short-circuit back to the launcher BEFORE the
/// keystroke reaches the guest (otherwise Esc would open Doom's
/// in-game menu and the user would be stuck unless they navigated
/// out of the menu first). The keyboard ring is single-consumer
/// (`crate::arch::uefi::keyboard` exposes a `pop_front` `read_keystroke`,
/// no peek API), so the launcher pops + intercepts in one pass and
/// the guest never sees Esc.
fn tic(
    window: &DoomWindow,
    frame: &CapturedFrame,
    guest_cell: &Rc<RefCell<Option<DoomGuest>>>,
    last_gen: &Rc<RefCell<u64>>,
) {
    // 1. Drive a tic. Bail early when the guest is absent (fresh-
    //    clone build).
    {
        let mut maybe_guest = guest_cell.borrow_mut();
        let Some(guest) = maybe_guest.as_mut() else { return };

        // tickGame. Refill fuel before the call so the guest gets
        // a fresh budget per tic (same shape `entry_uefi.rs` uses
        // for its boot smoke; OutOfFuel after one D_DoomLoop pass
        // is the expected yield).
        if guest.store.set_fuel(DOOM_FUEL).is_ok() {
            let tick_fn = match guest
                .instance
                .get_typed_func::<(), ()>(&guest.store, "tickGame")
            {
                Ok(f) => f,
                Err(e) => {
                    crate::println!("doom: tickGame export missing: {e}");
                    return;
                }
            };
            match tick_fn.call(&mut guest.store, ()) {
                Ok(()) => {}
                Err(e) if e.as_trap_code() == Some(wasmi::TrapCode::OutOfFuel) => {
                    // Expected — Doom's outer `while (true)` would
                    // otherwise spin forever. The guest's tic
                    // already happened before fuel ran out, so the
                    // captured frame is up to date.
                }
                Err(e) => {
                    crate::println!("doom: tickGame trapped: {e}");
                }
            }
        }
    }

    // 2. Re-bind the captured frame as a Slint Image if it's new.
    let buf = frame.borrow();
    if buf.bgra.is_empty() {
        // Guest hasn't drawn yet (still inside initGame, or
        // tickGame didn't reach drawFrame this pass). Window stays
        // black until the first frame lands.
        return;
    }
    let mut last = last_gen.borrow_mut();
    if buf.generation == *last {
        // Generation unchanged — no new frame to push. Avoids the
        // per-pixel BGRA->RGBA conversion + Image alloc on idle
        // tics.
        return;
    }
    *last = buf.generation;

    // BGRA -> RGBA conversion. Doom's frame is `[B, G, R, A]` per
    // pixel (little-endian 0xAARRGGBB, see src/doom.rs L208-219);
    // `slint::Rgba8Pixel` is `[R, G, B, A]` per pixel. Per-pixel
    // swap of bytes 0 and 2; alpha forced to 0xFF for opaqueness
    // (Doom's alpha is already 0xFF by convention but explicit
    // makes it deterministic if a future WASM build drifts).
    //
    // SharedPixelBuffer::new fills with `Rgba8Pixel::default()`
    // (all-zero == fully transparent black); we overwrite all
    // 256_000 pixels below so the initial state never shows.
    let mut pixel_buf: SharedPixelBuffer<Rgba8Pixel> =
        SharedPixelBuffer::new(DOOM_W, DOOM_H);
    {
        let dst = pixel_buf.make_mut_bytes();
        // Both buffers are exactly DOOM_FRAME_LEN bytes; the
        // safety check below guards against a guest that re-
        // shaped the framebuffer mid-flight (not expected with
        // the 640x400 hard-coded build, but the host import
        // contract leaves it possible).
        if dst.len() == buf.bgra.len() && dst.len() == DOOM_FRAME_LEN {
            for i in (0..DOOM_FRAME_LEN).step_by(4) {
                dst[i]     = buf.bgra[i + 2]; // R = src[B-slot+2]
                dst[i + 1] = buf.bgra[i + 1]; // G unchanged
                dst[i + 2] = buf.bgra[i];     // B = src[R-slot]
                dst[i + 3] = 0xFF;            // A: opaque
            }
        } else {
            // Surface dimension mismatch — drop this frame
            // silently. The next `draw_frame` will resize
            // `bgra` to match if the guest stabilises.
            return;
        }
    }
    drop(buf);
    let image = Image::from_rgba8(pixel_buf);
    window.set_frame(image);
}

/// One-time wasmi guest setup. Returns `Ok(DoomGuest)` on full
/// success or `Err(reason)` describing why the guest couldn't be
/// instantiated. Reason strings are short-and-grep-able for the
/// boot serial log.
fn instantiate_guest(frame: CapturedFrame) -> Result<DoomGuest, String> {
    if crate::doom_bin::DOOM_WASM.is_empty() {
        return Err("DOOM_WASM binary absent (fresh clone)".to_string());
    }

    // Engine config: `consume_fuel(true)` — same shape as
    // `entry_uefi.rs`'s boot smoke so wasmi accepts `Store::set_fuel`
    // calls below. Without this, every fuel call returns Err and
    // tickGame would loop forever inside `D_DoomLoop`.
    let mut config = wasmi::Config::default();
    config.consume_fuel(true);
    let engine = Engine::new(&config);

    let module = Module::new(&engine, crate::doom_bin::DOOM_WASM)
        .map_err(|e| format!("module parse failed: {e}"))?;

    let host = SlintDoomHost::new(frame);
    let mut store = Store::new(&engine, host);
    store
        .set_fuel(DOOM_FUEL)
        .map_err(|e| format!("set initial fuel failed: {e}"))?;

    let mut linker = Linker::<SlintDoomHost>::new(&engine);
    bind_doom_imports(&mut linker);

    let instance = linker
        .instantiate_and_start(&mut store, &module)
        .map_err(|e| format!("instantiate failed: {e}"))?;

    // Refill fuel before initGame so it gets the full budget.
    store
        .set_fuel(DOOM_FUEL)
        .map_err(|e| format!("refill for initGame failed: {e}"))?;
    let init_fn = instance
        .get_typed_func::<(), ()>(&store, "initGame")
        .map_err(|e| format!("get initGame export: {e}"))?;
    crate::println!("doom: initGame... (fuel={DOOM_FUEL})");
    let result = init_fn.call(&mut store, ());
    let remaining = store.get_fuel().unwrap_or(0);
    let consumed = DOOM_FUEL.saturating_sub(remaining);
    match result {
        Ok(()) => {
            crate::println!("doom: initGame OK (fuel consumed={consumed})");
        }
        Err(e) if e.as_trap_code() == Some(wasmi::TrapCode::OutOfFuel) => {
            // initGame ran out of fuel before completing. The
            // engine state is partially-initialized; tickGame may
            // still produce frames, may not. Surface the
            // condition; the Window will show whatever the guest
            // can render.
            crate::println!(
                "doom: initGame ran out of fuel after {consumed} instructions \
                 (raise DOOM_FUEL or split staging)"
            );
        }
        Err(e) => {
            return Err(format!("initGame trapped: {e}"));
        }
    }

    Ok(DoomGuest { store, instance })
}

// ── Tests ─────────────────────────────────────────────────────────
//
// `arest-kernel`'s bin target has `test = false` (Cargo.toml L33),
// so these `#[cfg(test)]` cases are reachable only when the crate is
// re-shaped into a lib for hosted testing — same convention the
// other ui_apps modules + `system.rs`, `slint_backend.rs`, etc. use.
// They document the intended behaviour and form a smoke battery for
// the day the kernel grows a lib facade.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frame_buffer_starts_empty() {
        let f = FrameBuffer::new();
        assert!(f.bgra.is_empty());
        assert_eq!(f.generation, 0);
    }

    #[test]
    fn slint_doom_host_draw_frame_captures_and_bumps_generation() {
        let frame: CapturedFrame = Rc::new(RefCell::new(FrameBuffer::new()));
        let mut host = SlintDoomHost::new(frame.clone());

        // First call — sized to allocate.
        let initial: Vec<u8> = (0..DOOM_FRAME_LEN as u8).collect::<Vec<_>>()
            .into_iter()
            .cycle()
            .take(DOOM_FRAME_LEN)
            .collect();
        host.draw_frame(&initial);
        {
            let buf = frame.borrow();
            assert_eq!(buf.bgra.len(), DOOM_FRAME_LEN);
            assert_eq!(buf.generation, 1);
        }

        // Second call — overwrite + bump.
        let next = vec![0xAAu8; DOOM_FRAME_LEN];
        host.draw_frame(&next);
        {
            let buf = frame.borrow();
            assert_eq!(buf.generation, 2);
            assert_eq!(buf.bgra[0], 0xAA);
        }
    }

    /// Smoke test: `build_app()` constructs without panicking even
    /// when the WASM binary isn't baked (CI-friendly). Mirrors the
    /// `appshell_constructs_under_minimal_window` and
    /// `repl::tests::build_app_constructs_under_minimal_window`
    /// pattern. Installs a `UefiSlintPlatform` so the Slint codegen
    /// for `Doom` runs through `register_bitmap_font` + the
    /// component constructor.
    #[test]
    fn build_app_constructs_under_minimal_window() {
        use crate::arch::uefi::slint_backend::UefiSlintPlatform;
        let platform = UefiSlintPlatform::new(1024, 720);
        let _ = slint::platform::set_platform(alloc::boxed::Box::new(platform));

        let app = build_app().expect("Doom construction failed");
        // Frame generation starts at 0 — no frames captured before
        // the timer fires (the timer needs Slint's
        // `update_timers_and_animations` to advance, which the
        // unit-test harness doesn't drive).
        assert_eq!(app.frame_generation(), 0);
        // Whether `guest_alive()` is true depends on whether the
        // host has DOOM_WASM baked. Both states are valid for this
        // smoke (we just check the constructor returned).
    }
}
