// crates/arest-kernel/src/ui_apps/hateoas.rs
//
// HATEOAS resource browser — Rust glue (#429 Track SSS).
//
// Bridges the live SYSTEM state (`crate::system::with_state`, the
// `RwLock<&'static Object>`-backed accessor introduced by Track KKK
// in #451) to the `HateoasBrowser` Slint component generated by
// `slint::include_modules!()` from `ui/apps/HateoasBrowser.slint`.
//
// The browser presents a three-pane "see anything" lens for the
// kernel's metamodel:
//
//   1. Resources sidebar — every Noun the metamodel knows about
//      (Directory, File, Tag, Color, ColorToken, …). Nouns are
//      discovered by walking `arest::ast::cells_iter` over the live
//      state and grouping by the `<Noun>_has_<Attribute>` cell-name
//      shape — the canonical FORML 2 fact-type naming convention,
//      same as `file_serve::lookup_*` consumes against
//      `File_has_MimeType`, `File_has_Name`, etc.
//
//   2. Instance list — for the selected Noun, every distinct value
//      that appears in the `<Noun>` role across that Noun's fact
//      cells. Each instance row shows a one-line summary built from
//      the Noun's primary identifier (the `<Noun>` binding itself).
//
//   3. Detail panel — for the selected instance, every
//      <Noun>_has_<Attr> binding plus every back-reference (any other
//      cell where this instance appears as a value). The
//      back-reference walk is the "follow the hyperlink" part of
//      HATEOAS — you can navigate from a File to the Directory it's
//      `is_in_Directory` of, then to that Directory's other Files,
//      and so on.
//
// Navigation is a `Vec<Breadcrumb>` stack. Forward navigation
// (clicking an instance, or in a future iteration clicking a
// back-reference link) pushes; the back button pops. The breadcrumb
// trail at the top of the window is computed from the stack.
//
// The Rust state lives in a `Rc<RefCell<BrowserState>>` shared
// between the Slint callbacks. Each callback mutates the state and
// then re-pushes the four `*-model` properties on the
// `HateoasBrowser` weak reference. This is the standard Slint
// callback shape; the kernel's `unsafe-single-threaded` slint
// feature makes the `Rc<RefCell<...>>` sound (no cross-thread
// access at boot).
//
// Wiring vs. invocation: this module produces a constructed
// `HateoasBrowser` window — it does NOT show it or run an event
// loop. `crate::entry_uefi` does not reference `ui_apps`; the boot
// launcher (#431) is what eventually calls `build_app()` and pumps
// the Slint event loop against `arch::uefi::slint_backend::
// FramebufferBackend`. Until then this module is dead code from
// the boot flow's perspective and exists to be `cargo
// check`-clean + smoke-test-callable.

#![allow(dead_code)]

use alloc::collections::BTreeMap;
use alloc::collections::BTreeSet;
use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use alloc::vec;
use core::cell::RefCell;

use arest::ast::{self, Object};
use slint::{ComponentHandle, ModelRc, SharedString, VecModel};

use crate::arch::uefi::slint_backend::HateoasBrowser;

/// Convenience alias — every Slint `[string]` property is bridged
/// through a `ModelRc<SharedString>` backed by a `VecModel`. Pulled
/// out so the property setters at the bottom of `redraw` aren't a
/// wall of generic angle brackets.
type StringModel = ModelRc<SharedString>;

/// One step in the navigation trail. Each forward click pushes one
/// of these; the back button pops.
///
/// The variant captures *what* the user picked, not the live data —
/// the data is re-derived from `crate::system::with_state` on each
/// `redraw` so the view stays consistent if the SYSTEM state is
/// mutated under us by a concurrent `system::apply` call (#451's
/// mutator). The `noun` and `instance` strings are the only
/// identifiers we keep across redraws; everything else is a function
/// of the current `Object` snapshot.
#[derive(Debug, Clone)]
enum Breadcrumb {
    /// Initial root — "Resources" landing page. Always sits at index
    /// 0 of the stack; the back button is disabled when this is the
    /// only entry.
    Root,
    /// User picked a Noun from the sidebar. `noun` is the bare Noun
    /// name (e.g. "File", "Directory", "ColorToken"), without the
    /// `_has_<Attr>` suffix.
    Noun { noun: String },
    /// User picked an instance from the centre column. `noun` is the
    /// owning Noun; `instance` is the value of the Noun's identifier
    /// binding (e.g. "file_42", "Inter-Regular").
    Instance { noun: String, instance: String },
}

impl Breadcrumb {
    /// Display label for the breadcrumb bar.
    fn label(&self) -> String {
        match self {
            Breadcrumb::Root => "Resources".to_string(),
            Breadcrumb::Noun { noun } => noun.clone(),
            Breadcrumb::Instance { instance, .. } => instance.clone(),
        }
    }
}

/// Mutable navigation + selection state shared between the Slint
/// callbacks. Wrapped in `Rc<RefCell<...>>` so the closures captured
/// by `on_resource_selected` / `on_instance_selected` /
/// `on_back_clicked` can each take their own clone of the `Rc` and
/// mutate the state independently — every callback mutates and then
/// re-pushes the `*-model` properties via `redraw`.
struct BrowserState {
    /// Navigation stack. Always non-empty; index 0 is `Root`.
    stack: Vec<Breadcrumb>,
}

impl BrowserState {
    fn new() -> Self {
        Self { stack: alloc::vec![Breadcrumb::Root] }
    }

    /// Top-of-stack — what the user is currently looking at.
    fn current(&self) -> &Breadcrumb {
        // Safe — `new()` seeds the stack and `pop` refuses to drop
        // below 1 entry.
        self.stack.last().expect("stack always has Root")
    }

    fn push(&mut self, crumb: Breadcrumb) {
        self.stack.push(crumb);
    }

    /// Pop one step. Refuses to pop the `Root` entry — the back
    /// button is disabled in the Slint side when the stack has only
    /// one entry, but this guards against stack underflow if the
    /// disable somehow gets bypassed.
    fn pop(&mut self) {
        if self.stack.len() > 1 {
            self.stack.pop();
        }
    }
}

// ── Cell-walk helpers (pure functions over &Object) ────────────────
//
// Every function below takes a `&Object` (the live SYSTEM snapshot)
// and returns owned data — so the read-side `RwLock` guard inside
// `system::with_state` can be released as soon as the helper
// returns. No `Object` references escape the closure.

/// Walk every cell in `state` and return the sorted, deduplicated
/// set of Noun names (the leading token before `_has_`).
///
/// Cell shape recognised: `<Noun>_has_<Attribute>` — the FORML 2
/// fact-type naming convention. Cells whose names don't match (def
/// cells like `D_has_welcome`, schema shards with a `:` in the
/// name, anything else) are filtered out.
///
/// Special case: `D_has_<Name>` is the def cell shape that
/// `defs_to_state` emits for every named Func. Filtering D out by
/// default keeps the sidebar focused on user-meaningful nouns
/// (Directory, File, Tag, Color, ColorToken, …) instead of cluttering
/// it with the welcome / echo / list:* / get:* def names. A future
/// "show defs" toggle can drop the D-filter when the user wants the
/// full surface.
fn discover_nouns(state: &Object) -> Vec<String> {
    let mut set: BTreeSet<String> = BTreeSet::new();
    for (cell_name, _) in ast::cells_iter(state) {
        if cell_name.contains(':') {
            // Schema shards / index cells / migration overlays — not
            // a Noun in the user's sense.
            continue;
        }
        let Some(noun) = noun_of(cell_name) else { continue };
        if noun == "D" {
            // Def cell sentinel — always present after `system::init`,
            // never user-meaningful in the resource browser.
            continue;
        }
        set.insert(noun.to_string());
    }
    set.into_iter().collect()
}

/// Extract the leading `<Noun>` token from a `<Noun>_has_<Attribute>`
/// cell name. Returns `None` when the cell name doesn't contain
/// `_has_` (e.g. an opaque internal cell).
///
/// Implementation: `str::split_once` returns the substring before
/// the first `_has_` occurrence. Returns the &str by pointer arithmetic
/// on the input — caller copies if it needs an owned `String`.
fn noun_of(cell_name: &str) -> Option<&str> {
    cell_name.split_once("_has_").map(|(noun, _)| noun)
}

/// Every cell that belongs to `noun` in `state`, returned as
/// `(attribute, &cell_contents)` pairs. The attribute is the trailing
/// token after `<noun>_has_`.
///
/// Returned slice references borrow from `state`, so the caller is
/// expected to immediately project owned summary strings out and let
/// the references drop before the `with_state` closure returns.
fn cells_for_noun<'a>(noun: &str, state: &'a Object) -> Vec<(&'a str, &'a Object)> {
    let prefix_full = format!("{noun}_has_");
    let mut out: Vec<(&str, &Object)> = Vec::new();
    for (cell_name, contents) in ast::cells_iter(state) {
        if let Some(attr) = cell_name.strip_prefix(&prefix_full[..]) {
            out.push((attr, contents));
        }
    }
    // Stable order: alphabetical by attribute. The metamodel doesn't
    // declare an order on attributes, but a stable visual layout
    // helps the user scan repeat sessions.
    out.sort_by(|a, b| a.0.cmp(b.0));
    out
}

/// Every distinct instance identifier for `noun` in `state`. For each
/// `<noun>_has_<attr>` cell we read the value bound to the `<noun>`
/// role across every fact, deduplicate, and sort.
///
/// This is the "list all instances of this Noun" view — equivalent to
/// `SELECT DISTINCT noun FROM noun_has_anything` in SQL terms.
fn instances_of(noun: &str, state: &Object) -> Vec<String> {
    let mut set: BTreeSet<String> = BTreeSet::new();
    for (_attr, cell) in cells_for_noun(noun, state) {
        let Some(facts) = cell.as_seq() else { continue };
        for fact in facts {
            if let Some(id) = ast::binding(fact, noun) {
                set.insert(id.to_string());
            }
        }
    }
    set.into_iter().collect()
}

/// Build the detail view for one instance of `noun`. Returns a list
/// of one-line `String`s suitable for the `detail-lines` Slint model.
///
/// Two sections are emitted, separated by a blank `String::new()`
/// line for visual grouping:
///
///   1. Bindings — every `<noun>_has_<attr>` fact where the
///      `<noun>` binding equals `instance`. Each line is rendered as
///      `attr = value` in the `Theme.type-code` (JetBrains Mono) face
///      so equals signs align.
///
///   2. Back-references — every cell anywhere in `state` that has a
///      binding whose value equals `instance` (for any role name).
///      Each line is rendered as
///      `← <cell> as <role>: <other-bindings>` so the user can see
///      both the source cell and the role the instance plays inside
///      it. This is the "hyperlinks point at me" half of HATEOAS;
///      a future iteration can make these click-targets to push a
///      new `Instance` breadcrumb directly.
///
/// Empty when the instance doesn't appear in any cell.
fn detail_lines_for(noun: &str, instance: &str, state: &Object) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();

    // Section 1: bindings. Walk every `<noun>_has_<attr>` cell and
    // for each fact whose `<noun>` binding matches `instance`, emit
    // every other binding pair as `key = value`.
    out.push(format!("# {noun}/{instance}"));
    let cells = cells_for_noun(noun, state);
    let mut binding_count = 0usize;
    for (attr, cell) in &cells {
        let Some(facts) = cell.as_seq() else { continue };
        for fact in facts {
            if ast::binding(fact, noun) != Some(instance) {
                continue;
            }
            // Bingo — this fact describes our instance. Emit every
            // binding except the self-referential `<noun> = instance`
            // pair (the heading already conveys it).
            if let Some(value) = ast::binding(fact, attr) {
                out.push(format!("{attr} = {value}"));
                binding_count += 1;
            }
        }
    }
    if binding_count == 0 {
        out.push("(no bindings)".to_string());
    }

    // Section 2: back-references. Walk every cell in the entire
    // state; for every fact whose any binding's value equals
    // `instance`, record `← <cell> as <role>`. Skip the self-cells
    // (those we just listed in section 1) so we don't double-count.
    out.push(String::new());
    out.push("← back-references".to_string());
    let self_cell_names: BTreeSet<String> = cells.iter()
        .map(|(attr, _)| format!("{noun}_has_{attr}"))
        .collect();
    let mut backref_count = 0usize;
    let mut backrefs: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (cell_name, cell) in ast::cells_iter(state) {
        if self_cell_names.contains(cell_name) {
            continue;
        }
        if cell_name.contains(':') {
            continue;
        }
        let Some(facts) = cell.as_seq() else { continue };
        for fact in facts {
            // Walk the fact's bindings and look for any role whose
            // value equals our instance.
            let Some(pairs) = fact.as_seq() else { continue };
            for pair in pairs {
                let Some(items) = pair.as_seq() else { continue };
                if items.len() != 2 { continue; }
                let Some(role) = items[0].as_atom() else { continue };
                let Some(value) = items[1].as_atom() else { continue };
                if value == instance {
                    backrefs
                        .entry(cell_name.to_string())
                        .or_default()
                        .push(role.to_string());
                    backref_count += 1;
                    // One match per fact is enough — multiple matches
                    // on the same fact would emit the same line
                    // anyway.
                    break;
                }
            }
        }
    }
    for (cell_name, roles) in &backrefs {
        let roles_joined = roles.join(", ");
        out.push(format!("  {cell_name} (as {roles_joined})"));
    }
    if backref_count == 0 {
        out.push("  (no back-references)".to_string());
    }

    out
}

// ── Redraw: project state into the four Slint `*-model` properties ─

/// Compute the four Slint models + status text for the current
/// breadcrumb stack, and push them onto the live `HateoasBrowser`
/// instance.
///
/// Called once at startup and again from each callback. The four
/// `*-model` Slint properties are reset wholesale on each call —
/// `VecModel::from_iter` builds a fresh model and `set_*_model`
/// swaps it atomically; the previous model is dropped. This is
/// O(n) in the cell count per redraw, which is acceptable at the
/// kernel's working-set scale (tens of cells, hundreds of facts);
/// a future incremental-update pass can add `ModelExt::push` /
/// `ModelExt::remove` differentials when the working set grows.
fn redraw(window: &HateoasBrowser, state: &BrowserState) {
    // Snapshot the live SYSTEM state. `with_state` returns `None`
    // when `system::init` hasn't run yet; in that case we paint the
    // empty-state UI (every model is empty, status reflects the
    // missing-init).
    let snapshot = crate::system::with_state(|s| Snapshot::collect(s, state));
    let snap = snapshot.unwrap_or_else(Snapshot::empty);

    // Resources sidebar.
    let resources_model: StringModel = ModelRc::new(VecModel::from_iter(
        snap.resources.iter().map(SharedString::from),
    ));
    window.set_resources(resources_model);
    window.set_selected_resource_index(snap.selected_resource_index);

    // Instance list.
    let instances_model: StringModel = ModelRc::new(VecModel::from_iter(
        snap.instances.iter().map(SharedString::from),
    ));
    window.set_instances(instances_model);
    window.set_selected_instance_index(snap.selected_instance_index);

    // Detail panel.
    let detail_model: StringModel = ModelRc::new(VecModel::from_iter(
        snap.detail_lines.iter().map(SharedString::from),
    ));
    window.set_detail_lines(detail_model);

    // Breadcrumbs + status.
    let crumbs_model: StringModel = ModelRc::new(VecModel::from_iter(
        snap.breadcrumbs.iter().map(SharedString::from),
    ));
    window.set_breadcrumbs(crumbs_model);
    window.set_status_text(SharedString::from(snap.status));
}

/// One redraw's worth of derived data. Computed inside the
/// `with_state` closure so the read lock is released the moment
/// `Snapshot::collect` returns.
struct Snapshot {
    resources: Vec<String>,
    selected_resource_index: i32,
    instances: Vec<String>,
    selected_instance_index: i32,
    detail_lines: Vec<String>,
    breadcrumbs: Vec<String>,
    status: String,
}

impl Snapshot {
    fn empty() -> Self {
        Self {
            resources: Vec::new(),
            selected_resource_index: -1,
            instances: Vec::new(),
            selected_instance_index: -1,
            detail_lines: vec!["SYSTEM not initialised — call system::init() first.".to_string()],
            breadcrumbs: vec!["Resources".to_string()],
            status: "system::init() not yet called".to_string(),
        }
    }

    fn collect(state: &Object, browser: &BrowserState) -> Self {
        let resources = discover_nouns(state);

        // Selected resource = the deepest Noun on the breadcrumb
        // stack, or none. We walk back through the stack rather than
        // peeking just the top because a click on an instance leaves
        // both the Noun and the Instance breadcrumb live (Instance is
        // top, Noun is one below).
        let active_noun: Option<&str> = browser.stack.iter().rev().find_map(|c| match c {
            Breadcrumb::Noun { noun } => Some(noun.as_str()),
            Breadcrumb::Instance { noun, .. } => Some(noun.as_str()),
            Breadcrumb::Root => None,
        });
        let selected_resource_index = match active_noun {
            Some(n) => resources.iter().position(|r| r == n).map(|p| p as i32).unwrap_or(-1),
            None => -1,
        };

        // Instance list for the active Noun (empty when no Noun is
        // selected).
        let instances: Vec<String> = match active_noun {
            Some(n) => instances_of(n, state),
            None => Vec::new(),
        };

        // Selected instance = the top-of-stack Instance breadcrumb,
        // if any.
        let selected_instance_id: Option<&str> = match browser.current() {
            Breadcrumb::Instance { instance, .. } => Some(instance.as_str()),
            _ => None,
        };
        let selected_instance_index = match selected_instance_id {
            Some(id) => instances.iter().position(|i| i == id).map(|p| p as i32).unwrap_or(-1),
            None => -1,
        };

        // Detail panel — only populated when an Instance breadcrumb
        // is on top.
        let detail_lines: Vec<String> = match browser.current() {
            Breadcrumb::Instance { noun, instance } => {
                detail_lines_for(noun, instance, state)
            }
            _ => Vec::new(),
        };

        // Breadcrumb labels. Always begins with "Resources" (the Root
        // entry) so the trail makes sense visually.
        let breadcrumbs: Vec<String> = browser.stack.iter().map(|c| c.label()).collect();

        // Status footer text — pithy summary of the current view.
        let status = match browser.current() {
            Breadcrumb::Root => format!("{} resources", resources.len()),
            Breadcrumb::Noun { noun } => {
                format!("{} — {} instance(s)", noun, instances.len())
            }
            Breadcrumb::Instance { noun, instance } => {
                format!("{noun}/{instance}")
            }
        };

        Self {
            resources,
            selected_resource_index,
            instances,
            selected_instance_index,
            detail_lines,
            breadcrumbs,
            status,
        }
    }
}

// ── Public constructor ────────────────────────────────────────────

/// Construct the HATEOAS browser window and wire its callbacks.
///
/// Returns the constructed `HateoasBrowser` ready to be shown by the
/// caller. The Slint platform must be installed before this is called
/// (`slint::platform::set_platform(Box::new(UefiSlintPlatform::new(...)))`)
/// — Slint refuses to instantiate components otherwise.
///
/// The window is *not* shown here; the caller drives the event loop
/// (Track #431 — boot UI launcher). This keeps `build_app` callable
/// from a unit-test smoke that doesn't have a framebuffer attached.
pub fn build_app() -> Result<HateoasBrowser, slint::PlatformError> {
    let window = HateoasBrowser::new()?;
    let state = Rc::new(RefCell::new(BrowserState::new()));

    // Initial population. Calling `redraw` once before any user
    // interaction means the window has correct contents the moment
    // `show()` runs.
    redraw(&window, &state.borrow());

    // Resource picked from the sidebar — push a `Noun` breadcrumb
    // (replacing any prior Noun/Instance) and re-render.
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_resource_selected(move |idx| {
            let Some(window) = weak.upgrade() else { return };
            // Project the index back to a noun name by re-running
            // `discover_nouns` against the live state. We don't cache
            // the previous resources Vec on the Rust side because the
            // SYSTEM state can mutate between redraws (#451's
            // mutator) and a stale cache would be wrong; one extra
            // walk of `cells_iter` per click is trivial.
            let noun: Option<String> = crate::system::with_state(|s| {
                discover_nouns(s).into_iter().nth(idx as usize)
            }).flatten();
            let Some(noun) = noun else { return };
            // Reset the stack to Root + the new Noun so every click
            // on the sidebar lands at the Noun's instance list, not
            // somewhere deep in a prior trail.
            let mut s = state.borrow_mut();
            s.stack.truncate(1);
            s.push(Breadcrumb::Noun { noun });
            drop(s);
            redraw(&window, &state.borrow());
        });
    }

    // Instance row picked — push an `Instance` breadcrumb on top of
    // the existing `Noun` (or replace any existing top `Instance`).
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_instance_selected(move |idx| {
            let Some(window) = weak.upgrade() else { return };
            let active_noun: Option<String> = {
                let s = state.borrow();
                s.stack.iter().rev().find_map(|c| match c {
                    Breadcrumb::Noun { noun } => Some(noun.clone()),
                    Breadcrumb::Instance { noun, .. } => Some(noun.clone()),
                    Breadcrumb::Root => None,
                })
            };
            let Some(noun) = active_noun else { return };
            let instance: Option<String> = crate::system::with_state(|st| {
                instances_of(&noun, st).into_iter().nth(idx as usize)
            }).flatten();
            let Some(instance) = instance else { return };
            let mut s = state.borrow_mut();
            // If the top is an Instance, replace it (sibling jump)
            // rather than nest — a long chain of replaced sibling
            // instances would clutter the breadcrumb trail without
            // adding navigation value.
            if matches!(s.current(), Breadcrumb::Instance { .. }) {
                s.pop();
            }
            s.push(Breadcrumb::Instance { noun, instance });
            drop(s);
            redraw(&window, &state.borrow());
        });
    }

    // Back button — pop one level off the breadcrumb stack.
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_back_clicked(move || {
            let Some(window) = weak.upgrade() else { return };
            state.borrow_mut().pop();
            redraw(&window, &state.borrow());
        });
    }

    // Theme toggle is a passive forward — the Theme global has
    // already swapped `mode` inside its Slint-side handler. Forward
    // the event so a future hook (e.g. persisting the theme choice
    // to a `ThemePref` cell) has a place to land. Today: no-op.
    {
        window.on_theme_toggled(|| {});
    }

    Ok(window)
}

// ── Tests ─────────────────────────────────────────────────────────
//
// `arest-kernel`'s bin target has `test = false` (Cargo.toml L33),
// so these `#[cfg(test)]` cases are reachable only when the crate is
// re-shaped into a lib for hosted testing — the same pattern
// `system.rs`, `file_serve.rs`, and `slint_backend.rs` use. They
// document the intended behaviour and form a smoke battery for the
// day the kernel grows a lib facade.
//
// The pure cell-walk helpers (`discover_nouns`, `cells_for_noun`,
// `instances_of`, `detail_lines_for`) are exercised against
// hand-built `Object` snapshots — no Slint platform setup needed for
// those. The `build_app_constructs` test mirrors the existing
// `appshell_constructs_under_minimal_window` pattern: it installs a
// `UefiSlintPlatform` and confirms `build_app()` returns Ok.

#[cfg(test)]
mod tests {
    use super::*;
    use arest::ast::{cell_push, fact_from_pairs};

    /// Build a tiny synthetic state with two Nouns (`File`, `Tag`)
    /// and a few facts each, so the discovery + instance + detail
    /// helpers have something to chew on.
    fn synth_state() -> Object {
        let s = Object::phi();
        let s = cell_push(
            "File_has_Name",
            fact_from_pairs(&[("File", "f1"), ("Name", "alpha.txt")]),
            &s,
        );
        let s = cell_push(
            "File_has_Name",
            fact_from_pairs(&[("File", "f2"), ("Name", "beta.txt")]),
            &s,
        );
        let s = cell_push(
            "File_has_MimeType",
            fact_from_pairs(&[("File", "f1"), ("MimeType", "text/plain")]),
            &s,
        );
        let s = cell_push(
            "Tag_has_Label",
            fact_from_pairs(&[("Tag", "t1"), ("Label", "important")]),
            &s,
        );
        // Back-reference: Tag is_on File f1.
        let s = cell_push(
            "Tag_is_on_File",
            fact_from_pairs(&[("Tag", "t1"), ("File", "f1")]),
            &s,
        );
        s
    }

    #[test]
    fn discover_nouns_dedupes_and_sorts() {
        let state = synth_state();
        let nouns = discover_nouns(&state);
        // File appears in two cells, Tag in two — should dedup to
        // exactly two entries.
        assert_eq!(nouns, vec!["File".to_string(), "Tag".to_string()]);
    }

    #[test]
    fn discover_nouns_filters_d_def_cell() {
        // Simulate the def cell `D_has_welcome` that `defs_to_state`
        // emits. It must NOT show up as a user-visible Noun.
        let state = cell_push(
            "D_has_welcome",
            fact_from_pairs(&[("D", "x"), ("welcome", "y")]),
            &synth_state(),
        );
        let nouns = discover_nouns(&state);
        assert!(!nouns.contains(&"D".to_string()), "D filtered, got {nouns:?}");
        assert!(nouns.contains(&"File".to_string()));
    }

    #[test]
    fn instances_of_collects_distinct_ids() {
        let state = synth_state();
        let files = instances_of("File", &state);
        assert_eq!(files, vec!["f1".to_string(), "f2".to_string()]);
    }

    #[test]
    fn detail_lines_includes_bindings_and_back_references() {
        let state = synth_state();
        let lines = detail_lines_for("File", "f1", &state);
        // Heading.
        assert_eq!(lines[0], "# File/f1");
        // Bindings — both Name and MimeType for f1 should be present
        // in the first section (before the empty separator).
        let blank_idx = lines.iter().position(|l| l.is_empty()).unwrap_or(lines.len());
        let bindings = &lines[..blank_idx];
        assert!(bindings.iter().any(|l| l == "Name = alpha.txt"),
            "expected Name binding, got {bindings:?}");
        assert!(bindings.iter().any(|l| l == "MimeType = text/plain"),
            "expected MimeType binding, got {bindings:?}");
        // Back-reference — Tag_is_on_File should be listed since f1
        // appears as the `File` value in that cell.
        let backrefs = &lines[blank_idx..];
        assert!(backrefs.iter().any(|l| l.contains("Tag_is_on_File")),
            "expected Tag_is_on_File backref, got {backrefs:?}");
    }

    #[test]
    fn detail_lines_for_unknown_instance_reports_no_bindings() {
        let state = synth_state();
        let lines = detail_lines_for("File", "ghost", &state);
        // Heading + "(no bindings)" section + back-references hint.
        assert_eq!(lines[0], "# File/ghost");
        assert!(lines.iter().any(|l| l == "(no bindings)"));
    }

    #[test]
    fn breadcrumb_label_round_trip() {
        assert_eq!(Breadcrumb::Root.label(), "Resources");
        assert_eq!(
            Breadcrumb::Noun { noun: "File".into() }.label(),
            "File"
        );
        assert_eq!(
            Breadcrumb::Instance { noun: "File".into(), instance: "f1".into() }.label(),
            "f1"
        );
    }

    #[test]
    fn browser_state_pop_refuses_to_drop_root() {
        let mut s = BrowserState::new();
        assert!(matches!(s.current(), Breadcrumb::Root));
        s.pop(); // Should be a no-op.
        assert!(matches!(s.current(), Breadcrumb::Root));
        assert_eq!(s.stack.len(), 1);
    }

    /// Smoke test: `build_app()` constructs without panicking. This
    /// installs a `UefiSlintPlatform` (no framebuffer attached — just
    /// a `MinimalSoftwareWindow` adapter) so the Slint codegen for
    /// `HateoasBrowser` runs through `register_bitmap_font` + the
    /// component constructor without falling over. Mirrors the
    /// `appshell_constructs_under_minimal_window` pattern in
    /// `slint_backend.rs`.
    ///
    /// `set_platform` returns Err on the second call within a single
    /// process (Slint enforces one platform per process); the test
    /// harness shares a binary with the slint_backend tests, so we
    /// ignore the result and let either install win — the second
    /// caller's existing platform is sufficient for `HateoasBrowser::
    /// new` to succeed.
    #[test]
    fn build_app_constructs_under_minimal_window() {
        use crate::arch::uefi::slint_backend::UefiSlintPlatform;
        let platform = UefiSlintPlatform::new(1100, 760);
        let _ = slint::platform::set_platform(alloc::boxed::Box::new(platform));

        let window = build_app().expect("HateoasBrowser construction failed");
        // Confirm the window starts in the empty / pre-init state —
        // `system::init()` hasn't run in this test, so `with_state`
        // returns None and `redraw` paints `Snapshot::empty`.
        // (Property reads aren't part of the public Slint API on
        // ComponentHandle, so we just verify `_window` is alive.)
        let _ = window;
    }
}
