// crates/arest-kernel/src/ui_apps/mod.rs
//
// Slint apps for the AREST kernel (#429 Track SSS — first app;
// #510 / EPIC #496 merged the original two apps into UnifiedRepl).
//
// Each submodule wires `crate::system::with_state` queries to a
// component generated by `slint::include_modules!()` in
// `crate::arch::uefi::slint_backend`. The generated component types
// (e.g. `UnifiedRepl`, `AppShell`) are re-exported through that
// module's `slint::include_modules!()` site, so this submodule can
// reach them via `crate::arch::uefi::slint_backend::UnifiedRepl`
// without re-running the codegen.
//
// Platform note: the only target that wires Slint into a render path
// is `x86_64-unknown-uefi` (per Cargo.toml's slint = { ... } block
// being target-gated). The `mod ui_apps;` declaration in `main.rs` is
// therefore cfg-gated to that triple — this module's submodules
// transitively reach `crate::arch::uefi::slint_backend`, which is
// only present under the same cfg.
//
// Future apps add themselves here by sibling submodule. Each app's
// `build_app() -> ComponentHandle` constructor stays the canonical
// entry; #431 (Boot UI launcher) decides which app(s) actually go on
// screen at boot.

pub mod keyboard;
pub mod launcher;
pub mod registry;
// Unified REPL (#510, EPIC #496). Foundational structural merge of
// the previous `hateoas` (Track SSS #429) + `repl` (Track TTT #430)
// modules into a single panel — left pane drives the HATEOAS browse
// today's `hateoas` did, right pane drives the REPL prompt + scrollback
// today's `repl` did. Subsequent sub-tasks (#511 cell-as-screen, #512
// navigation actions, #513 SYSTEM-as-actions, …) layer on top.
pub mod unified_repl;
// Doom (#455 + #456 Track VVV). Gated behind `feature = "doom"`
// because the wasmi-instantiated jacobenget/doom.wasm v0.1.0 binary
// is GPL-2.0; the default kernel build ships AGPL-3.0-or-later only
// (#396). With the feature off, the app submodule is absent from the
// crate graph and `launcher.rs` skips the Doom button row.
#[cfg(feature = "doom")]
pub mod doom;
