// crates/arest-kernel/src/ui_apps/repl.rs
//
// REPL toolkit — Rust glue (#430 Track TTT).
//
// Bridges the BIOS-era `crate::repl` dispatch table (#183 / GGG #365)
// to the `Repl` Slint component generated by `slint::include_modules!()`
// from `ui/apps/Repl.slint`. Mirrors the shape Track SSS introduced in
// `ui_apps::hateoas` (#429): a `pub fn build_app() -> Result<ReplApp,
// PlatformError>` constructor that wires every Slint callback to a
// closure capturing a shared `Rc<RefCell<ReplState>>`, plus a
// `#[cfg(test)]` smoke battery that exercises the construction path
// without a framebuffer attached.
//
// State model:
//
//   * `scrollback: Vec<String>` — every line ever written to the
//     scrollback panel, capped at `SCROLLBACK_MAX` entries with the
//     oldest dropped on overflow. Each entry is one rendered Slint
//     `Text` row (no trailing newlines — the Slint side handles
//     vertical layout). Submitted commands land here as
//     `"<prompt><line>"` (single line); responses are split on `\n`
//     so multi-line responses (like `help`) render correctly.
//
//   * `history: Vec<String>` — every submitted command line, in
//     chronological order. Up/Down arrow walks `history_idx` over
//     this; submit pushes onto the tail.
//
//   * `history_idx: Option<usize>` — `None` = the user is editing
//     an in-progress line (not browsing history). `Some(i)` = the
//     user pressed Up `history.len() - i` times; the input field
//     shows `history[i]`. Down toward the present moves toward
//     `None`.
//
//   * `pending_input: String` — snapshot of the user's in-progress
//     input at the moment they pressed Up. Restored when Down walks
//     past the most recent history entry, so a partial command isn't
//     lost.
//
// The Rust state lives behind a `Rc<RefCell<...>>` shared by every
// callback closure. The kernel's `unsafe-single-threaded` slint
// feature (Cargo.toml L205) makes the lack of `Send` on `Rc` /
// `RefCell` sound — boot is single-threaded.
//
// Wiring vs. invocation: `crate::entry_uefi`'s drainer loop (GGG
// #365) still pumps `crate::repl::process_key` per `DecodedKey::
// Unicode` for the BIOS-era console REPL. `build_app()` is reachable
// only from the boot UI launcher (#431, future) — until that lands,
// this module is dead code from the boot flow's perspective and
// exists to be `cargo check`-clean + smoke-test-callable.

#![allow(dead_code)]

use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cell::RefCell;

use slint::{ComponentHandle, ModelRc, SharedString, VecModel};

use crate::arch::uefi::slint_backend::Repl;

/// Convenience alias — every Slint `[string]` property is bridged
/// through a `ModelRc<SharedString>` backed by a `VecModel`. Same
/// alias used by `ui_apps::hateoas`.
type StringModel = ModelRc<SharedString>;

/// Hard ceiling on `scrollback` length. When `push_line` would push
/// the count over this, the oldest entry is `remove(0)`-ed first.
/// Picked at 1000 to match the spec — at ~20px per rendered line
/// this is enough scrollback for hours of interaction without
/// unbounded memory growth.
const SCROLLBACK_MAX: usize = 1000;

/// First line shown in the scrollback panel before the user types.
/// Mirrors the BIOS-era boot banner — `arch/uefi/entry_uefi.rs`
/// prints a similar one to the framebuffer console at boot, but the
/// Slint REPL is its own surface so a fresh banner here keeps the
/// app self-contained.
const WELCOME: &str =
    "AREST kernel REPL — type `help` for built-in commands.";

/// Mutable state shared between the Slint callbacks. Wrapped in
/// `Rc<RefCell<...>>` so each callback can take its own clone of
/// the `Rc` and mutate independently — every callback mutates and
/// then re-pushes the `scrollback` model via `redraw`.
struct ReplState {
    /// Visible scrollback. Each entry is one rendered line (no
    /// trailing newlines).
    scrollback: Vec<String>,
    /// Command history, oldest first.
    history: Vec<String>,
    /// `None` = user is editing a fresh line; `Some(i)` = the input
    /// field currently shows `history[i]`.
    history_idx: Option<usize>,
    /// Snapshot of the in-progress input at the moment the user
    /// first pressed Up. Restored when Down walks past the newest
    /// history entry.
    pending_input: String,
}

impl ReplState {
    fn new() -> Self {
        Self {
            scrollback: alloc::vec![WELCOME.to_string()],
            history: Vec::new(),
            history_idx: None,
            pending_input: String::new(),
        }
    }

    /// Append one line to scrollback, dropping the oldest if at cap.
    /// `line` should NOT contain `\n` — multi-line content must be
    /// split by the caller (see `push_response`).
    fn push_line(&mut self, line: String) {
        if self.scrollback.len() >= SCROLLBACK_MAX {
            // Drop the oldest. `remove(0)` is O(n) but at the
            // 1000-line cap this is cheap relative to a re-render
            // and keeps the impl honest about the FIFO contract.
            self.scrollback.remove(0);
        }
        self.scrollback.push(line);
    }

    /// Push a multi-line response onto scrollback by splitting on
    /// `\n`. Empty trailing lines (from a response that ends with
    /// `\n`) are preserved so the visual spacing matches what the
    /// console REPL would print.
    fn push_response(&mut self, response: &str) {
        for line in response.split('\n') {
            self.push_line(line.to_string());
        }
    }

    /// Wholesale clear scrollback. Bound to Ctrl+L. History is
    /// preserved — only the visible buffer is reset.
    fn clear_scrollback(&mut self) {
        self.scrollback.clear();
    }

    /// Walk one step into the past. Returns the new `current_input`
    /// the Slint side should show, or `None` when there's no older
    /// entry (no-op for the caller). On the first Up press, captures
    /// `current` into `pending_input` so a Down walk past the newest
    /// entry can restore it.
    fn history_prev(&mut self, current: &str) -> Option<String> {
        if self.history.is_empty() {
            return None;
        }
        let new_idx = match self.history_idx {
            None => {
                // First Up press — snapshot the in-progress line so
                // Down can later restore it. Newest history entry is
                // at `len - 1`.
                self.pending_input = current.to_string();
                self.history.len() - 1
            }
            Some(0) => return None, // Already at oldest.
            Some(i) => i - 1,
        };
        self.history_idx = Some(new_idx);
        Some(self.history[new_idx].clone())
    }

    /// Walk one step toward the present. Returns the new
    /// `current_input` the Slint side should show. Off the end (past
    /// the newest entry), restores `pending_input` and resets
    /// `history_idx` to `None`.
    fn history_next(&mut self) -> Option<String> {
        match self.history_idx {
            None => None, // Not browsing — nothing to do.
            Some(i) if i + 1 < self.history.len() => {
                self.history_idx = Some(i + 1);
                Some(self.history[i + 1].clone())
            }
            Some(_) => {
                // Walked past the newest — restore the pre-browse
                // snapshot. The clone is cheap (typical input is
                // short) and avoids a partial-move out of `self`.
                self.history_idx = None;
                let restored = self.pending_input.clone();
                self.pending_input.clear();
                Some(restored)
            }
        }
    }

    /// Submit a line: render it into scrollback, evaluate it, render
    /// the response, push to history, and reset history browsing.
    /// `line` is captured raw from the TextInput — `evaluate_line`
    /// trims it before dispatch.
    fn submit(&mut self, prompt: &str, line: String) {
        // Echo the typed line (with prompt prefix) into scrollback,
        // matching the BIOS REPL's behaviour where `\n` causes the
        // prompt-prefixed line to scroll up.
        self.push_line(format!("{prompt}{line}"));

        // Evaluate. `evaluate_line` is the GUI-side sibling of
        // `process_key('\n')` — it returns the response as a String
        // instead of routing through `print!`.
        let response = crate::repl::evaluate_line(&line);
        if !response.is_empty() {
            self.push_response(&response);
        }

        // Push to history (only non-blank lines — typing Enter on an
        // empty input shouldn't pollute the history walk).
        let trimmed = line.trim();
        if !trimmed.is_empty() {
            // De-dup consecutive duplicates: pressing Up after running
            // the same command twice in a row should still walk
            // backwards one step at a time, but storing the duplicate
            // doesn't add value. Same convention as bash's
            // `HISTCONTROL=ignoredups`.
            let is_dup = self.history.last().map(|s| s == trimmed).unwrap_or(false);
            if !is_dup {
                self.history.push(trimmed.to_string());
            }
        }

        // Reset history browse cursor so the next Up press starts
        // from the newest entry again.
        self.history_idx = None;
        self.pending_input.clear();
    }
}

/// The constructed REPL window plus its mutable state. Returned from
/// `build_app` so the boot UI launcher (#431) can both `show()` the
/// window and reach into the state for follow-up wiring (e.g. piping
/// kernel log lines into the scrollback as a future enhancement).
pub struct ReplApp {
    /// The Slint window. `ComponentHandle` requires the inner Repl
    /// stay alive for the duration of the event loop; `ReplApp` holds
    /// it by value to make that lifetime explicit.
    pub window: Repl,
    /// The shared mutable state. Cloned by every callback closure
    /// installed during `build_app`; exposed here for tests and
    /// for the launcher's downstream wiring.
    state: Rc<RefCell<ReplState>>,
}

impl ReplApp {
    /// Read-only access to the current scrollback length, used by
    /// tests + diagnostics. Borrows the state immutably; safe to
    /// call from outside an event handler.
    pub fn scrollback_len(&self) -> usize {
        self.state.borrow().scrollback.len()
    }

    /// Read-only access to the current history length.
    pub fn history_len(&self) -> usize {
        self.state.borrow().history.len()
    }
}

/// Refresh the Slint `scrollback` model from the Rust state. Called
/// once at startup and again from each callback. The model is reset
/// wholesale — `VecModel::from_iter` builds a fresh one and
/// `set_scrollback` swaps it atomically; the previous model is
/// dropped. Same shape as `ui_apps::hateoas::redraw`.
fn redraw(window: &Repl, state: &ReplState) {
    let model: StringModel = ModelRc::new(VecModel::from_iter(
        state.scrollback.iter().map(SharedString::from),
    ));
    window.set_scrollback(model);
}

/// Construct the REPL window and wire its callbacks.
///
/// The Slint platform must be installed before this is called
/// (`slint::platform::set_platform(Box::new(UefiSlintPlatform::new(...)))`)
/// — Slint refuses to instantiate components otherwise.
///
/// The window is *not* shown here; the caller (boot UI launcher,
/// #431) drives the event loop. This keeps `build_app` callable
/// from a unit-test smoke that doesn't have a framebuffer attached.
pub fn build_app() -> Result<ReplApp, slint::PlatformError> {
    let window = Repl::new()?;
    let state = Rc::new(RefCell::new(ReplState::new()));

    // Initial paint — populates the scrollback with the welcome
    // banner before any user interaction.
    redraw(&window, &state.borrow());
    // Default prompt mirrors the BIOS REPL's prompt constant.
    window.set_prompt(SharedString::from("arest> "));

    // Submit (Enter pressed in the input row).
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_submit(move |line| {
            let Some(window) = weak.upgrade() else { return };
            // Pull the live prompt from the Slint side so the echoed
            // line in scrollback always matches what the user actually
            // saw — Rust never renders the prompt directly.
            let prompt = window.get_prompt().to_string();
            let line_owned = line.to_string();
            {
                let mut s = state.borrow_mut();
                s.submit(&prompt, line_owned);
            }
            // Clear the input field. Slint's two-way binding
            // (`text <=> root.current-input`) propagates this to the
            // TextInput.
            window.set_current_input(SharedString::from(""));
            redraw(&window, &state.borrow());
        });
    }

    // Ctrl+L — wholesale scrollback clear.
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_clear(move || {
            let Some(window) = weak.upgrade() else { return };
            state.borrow_mut().clear_scrollback();
            redraw(&window, &state.borrow());
        });
    }

    // Up arrow — walk one step into the past.
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_history_prev(move || {
            let Some(window) = weak.upgrade() else { return };
            let current = window.get_current_input().to_string();
            let new_input = state.borrow_mut().history_prev(&current);
            if let Some(text) = new_input {
                window.set_current_input(SharedString::from(text));
            }
        });
    }

    // Down arrow — walk one step toward the present.
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_history_next(move || {
            let Some(window) = weak.upgrade() else { return };
            let new_input = state.borrow_mut().history_next();
            if let Some(text) = new_input {
                window.set_current_input(SharedString::from(text));
            }
        });
    }

    // Theme toggle — passive forward, same as HateoasBrowser's hook.
    // The Theme global has already swapped `mode` inside its Slint
    // handler; this gives a host (the future #431 launcher) a place
    // to persist the choice if it wants to.
    {
        window.on_theme_toggled(|| {});
    }

    Ok(ReplApp { window, state })
}

// ── Tests ─────────────────────────────────────────────────────────
//
// `arest-kernel`'s bin target has `test = false` (Cargo.toml L33),
// so these `#[cfg(test)]` cases are reachable only when the crate is
// re-shaped into a lib for hosted testing — the same convention
// `system.rs`, `file_serve.rs`, `slint_backend.rs`, and
// `ui_apps::hateoas` use. They document the intended behaviour and
// form a smoke battery for the day the kernel grows a lib facade.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_state_seeds_welcome_and_empty_history() {
        let s = ReplState::new();
        assert_eq!(s.scrollback.len(), 1);
        assert!(s.scrollback[0].contains("AREST"));
        assert!(s.history.is_empty());
        assert!(s.history_idx.is_none());
    }

    #[test]
    fn push_line_caps_at_scrollback_max() {
        let mut s = ReplState::new();
        for i in 0..(SCROLLBACK_MAX + 50) {
            s.push_line(format!("line {i}"));
        }
        assert_eq!(s.scrollback.len(), SCROLLBACK_MAX);
        // Oldest entries dropped — the welcome banner is gone, and
        // the first remaining line is one of the later "line N"
        // pushes.
        assert!(s.scrollback[0].starts_with("line "));
    }

    #[test]
    fn push_response_splits_multiline() {
        let mut s = ReplState::new();
        s.push_response("alpha\nbeta\ngamma");
        // Welcome + 3 response lines.
        assert_eq!(s.scrollback.len(), 4);
        assert_eq!(s.scrollback[1], "alpha");
        assert_eq!(s.scrollback[2], "beta");
        assert_eq!(s.scrollback[3], "gamma");
    }

    #[test]
    fn clear_scrollback_drops_all_lines() {
        let mut s = ReplState::new();
        s.push_line("foo".to_string());
        s.push_line("bar".to_string());
        s.clear_scrollback();
        assert!(s.scrollback.is_empty());
    }

    #[test]
    fn submit_pushes_prompt_line_and_response_to_scrollback() {
        let mut s = ReplState::new();
        s.scrollback.clear(); // Drop the welcome for a clean count.
        s.submit("arest> ", "help".to_string());
        // First line: echoed prompt + command. Subsequent lines:
        // response from `repl::evaluate_line("help")`.
        assert_eq!(s.scrollback[0], "arest> help");
        assert!(s.scrollback.len() > 1, "expected response lines, got {:?}", s.scrollback);
        // Help response should mention "help" and "heap" somewhere.
        let blob = s.scrollback.join("\n");
        assert!(blob.contains("help"), "missing help mention: {blob}");
    }

    #[test]
    fn submit_pushes_to_history_and_resets_browse_cursor() {
        let mut s = ReplState::new();
        s.submit("> ", "help".to_string());
        s.submit("> ", "heap".to_string());
        assert_eq!(s.history, alloc::vec!["help".to_string(), "heap".to_string()]);
        assert!(s.history_idx.is_none());
    }

    #[test]
    fn submit_dedups_consecutive_duplicates() {
        let mut s = ReplState::new();
        s.submit("> ", "help".to_string());
        s.submit("> ", "help".to_string());
        // Only one "help" recorded — duplicates folded.
        assert_eq!(s.history, alloc::vec!["help".to_string()]);
    }

    #[test]
    fn submit_ignores_blank_for_history() {
        let mut s = ReplState::new();
        s.submit("> ", "   ".to_string());
        assert!(s.history.is_empty());
    }

    #[test]
    fn history_prev_walks_back_then_stops_at_oldest() {
        let mut s = ReplState::new();
        s.history = alloc::vec!["one".to_string(), "two".to_string(), "three".to_string()];
        // Newest first: Up should yield three, then two, then one,
        // then no more.
        assert_eq!(s.history_prev(""), Some("three".to_string()));
        assert_eq!(s.history_prev(""), Some("two".to_string()));
        assert_eq!(s.history_prev(""), Some("one".to_string()));
        // At oldest — further Ups are no-ops (None).
        assert_eq!(s.history_prev(""), None);
    }

    #[test]
    fn history_prev_snapshots_in_progress_input() {
        let mut s = ReplState::new();
        s.history = alloc::vec!["one".to_string()];
        // First Up captures the in-progress text.
        s.history_prev("partial-edit");
        assert_eq!(s.pending_input, "partial-edit");
    }

    #[test]
    fn history_next_walks_forward_and_restores_pending() {
        let mut s = ReplState::new();
        s.history = alloc::vec!["one".to_string(), "two".to_string()];
        // Walk back to "one" (snapshots "in-progress").
        s.history_prev("in-progress");
        s.history_prev("in-progress");
        assert_eq!(s.history_idx, Some(0));
        // Forward: one -> two -> in-progress.
        assert_eq!(s.history_next(), Some("two".to_string()));
        assert_eq!(s.history_next(), Some("in-progress".to_string()));
        assert!(s.history_idx.is_none());
    }

    #[test]
    fn history_next_with_no_browse_in_progress_is_noop() {
        let mut s = ReplState::new();
        s.history = alloc::vec!["one".to_string()];
        assert_eq!(s.history_next(), None);
    }

    #[test]
    fn history_prev_on_empty_history_returns_none() {
        let mut s = ReplState::new();
        assert_eq!(s.history_prev("x"), None);
    }

    /// Smoke test: `build_app()` constructs without panicking. Mirrors
    /// the `appshell_constructs_under_minimal_window` and
    /// `hateoas::tests::build_app_constructs_under_minimal_window`
    /// pattern. Installs a `UefiSlintPlatform` (no framebuffer
    /// attached) so the Slint codegen for `Repl` runs through
    /// `register_bitmap_font` + the component constructor.
    ///
    /// `set_platform` returns Err on the second call within a single
    /// process (Slint enforces one platform per process); we ignore
    /// the result so any prior installer in the same test binary
    /// (e.g. the slint_backend AppShell smoke or the hateoas smoke)
    /// keeps its platform.
    #[test]
    fn build_app_constructs_under_minimal_window() {
        use crate::arch::uefi::slint_backend::UefiSlintPlatform;
        let platform = UefiSlintPlatform::new(1024, 720);
        let _ = slint::platform::set_platform(alloc::boxed::Box::new(platform));

        let app = build_app().expect("Repl construction failed");
        // Welcome banner present after construction — no user
        // interaction yet.
        assert_eq!(app.scrollback_len(), 1);
        assert_eq!(app.history_len(), 0);
    }
}
