// The C# binding of the INTERSECTION SOURCE vocabulary (shared/intersection.md):
// the same names Python execs and Rust defines as closures, here as static
// methods so the byte-wrapped canon (Canon.g.cs, generated by the csproj's
// WrapCanon target) is one varargs method call per file. Trees build in the
// NATIVE form the delta evaluator uses: an atom is a scalar (string/long),
// a sequence is an object[], K(x) is the pair ("CONST", x).
namespace Arestlam;

static partial class Canon
{
    internal static readonly List<KeyValuePair<string, object>> Defs = new();

    static object T(params object[] elements) => elements;

    static object DEF(string name, object tree)
    {
        Defs.Add(new KeyValuePair<string, object>(name, tree));
        return name;
    }

    static object A(string s) => s;
    static object A(long i) => i;
    static object N(long i) => i;
    static object PHI() => Array.Empty<object>();
    static object K(object x) => new object[] { "CONST", x };

    static object S1(object a) => new[] { a };
    static object S2(object a, object b) => new[] { a, b };
    static object S3(object a, object b, object c) => new[] { a, b, c };
    static object S4(object a, object b, object c, object d) => new[] { a, b, c, d };
    static object S5(object a, object b, object c, object d, object e)
        => new[] { a, b, c, d, e };
    static object S6(object a, object b, object c, object d, object e, object f)
        => new[] { a, b, c, d, e, f };
    static object S7(object a, object b, object c, object d, object e, object f,
                     object g) => new[] { a, b, c, d, e, f, g };
    static object S8(object a, object b, object c, object d, object e, object f,
                     object g, object h) => new[] { a, b, c, d, e, f, g, h };
    static object S9(object a, object b, object c, object d, object e, object f,
                     object g, object h, object i)
        => new[] { a, b, c, d, e, f, g, h, i };

    // One merged file (arest.canon); discipline order is preserved WITHIN it:
    // theta, constraints, ast, system.
    internal static List<KeyValuePair<string, object>> LoadAll()
    {
        Defs.Clear();
        LoadArest();
        return Defs;
    }
}
