// crates/arest-kernel/src/qt_adapter/widgets.rs
//
// Qt 6 widget table — for each widget class DDDD's #485 declared an
// `ImplementationBinding` for in `readings/ui/components.md`, hold a
// `*const QMetaObject` resolved via `dlsym(handle,
// "<class>::staticMetaObject")` against the appropriate library
// (libqt6core.so.6 for QObject + base classes; libqt6widgets.so.6 for
// every concrete widget — Qt's library split.
//
// Qt's reflection model
// ---------------------
// Qt 6 adopts the "Meta-Object Compiler" (`moc`) approach: every
// QObject subclass has a `static const QMetaObject staticMetaObject`
// generated by `moc` from the class's `Q_OBJECT` macro. The
// `QMetaObject` struct carries the class's property table, signal
// slot table, and method invocation thunks. AREST's marshalling
// layer (`marshalling.rs`) reaches the property table to implement
// `QObject::setProperty(name, QVariant)` reflection, and the signal
// slot table to wire `connect_signal` callbacks back to the AREST
// runtime.
//
// On the foundation slice we only need the *pointer* to each
// `staticMetaObject` — we don't decode it (that's #491's job). The
// pointer is what `binding.rs` records as the resolved Symbol value
// for each `ImplementationBinding` cell so that future composition
// work (#489) can hand it back to `marshalling.rs`.
//
// Symbol mangling
// ---------------
// Qt's `staticMetaObject` is a C++ static data member, so the symbol
// is Itanium-ABI-mangled (e.g. `_ZN11QPushButton16staticMetaObjectE`).
// Real `dlsym` would take the mangled name; future symbol-resolver
// work could expose a `cxxabi`-aware lookup that takes the demangled
// name. For the foundation slice we don't need either: every dlsym
// returns null because the library never loaded, so we record null
// pointers and the registration step still emits the cells.
//
// Foundation-slice behaviour
// --------------------------
// `init()` walks the `QT_WIDGET_TABLE` constant, calls `loader::dlsym`
// for each entry, and writes the resolved pointer into the
// `RESOLVED_SYMBOLS` map. On the foundation slice every entry comes
// back null. `binding.rs` consumes the table by class-name key, not
// by pointer, so null pointers don't break registration — they just
// mean the cells point at nothing executable until the loader
// extension lands.

use alloc::collections::BTreeMap;
use alloc::string::{String, ToString};
use core::ffi::c_void;
use spin::{Mutex, Once};

use super::loader;

/// Where in the Qt 6 library tree a class's `staticMetaObject` lives.
/// Drives which `LibHandle` we hand to `dlsym`. Today every widget
/// class except `QObject` itself lives in `libqt6widgets.so.6`; the
/// `Core` variant is reserved for the future when a non-widget
/// reflection target (QString, QVariant) gets added to the table.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum QtLibrary {
    /// libqt6core.so.6 — QObject, QString, QVariant base classes.
    Core,
    /// libqt6widgets.so.6 — every concrete widget class DDDD's #485
    /// registered.
    Widgets,
}

/// One row of the Qt widget table. `class_name` is the unmangled
/// C++ class name (matches DDDD's #485 ImplementationBinding Symbol
/// values verbatim — "QPushButton", "QLineEdit", etc.). `library`
/// picks which loaded library to `dlsym` against. `mangled_symbol`
/// is the Itanium-ABI-mangled symbol name for the class's
/// `staticMetaObject` static data member; passed through to
/// `loader::dlsym` as-is.
#[derive(Clone, Copy, Debug)]
pub struct QtWidget {
    pub class_name: &'static str,
    pub library: QtLibrary,
    pub mangled_symbol: &'static str,
}

/// The 11 Qt 6 widget classes DDDD's #485 ImplementationBinding facts
/// reference, in declaration order. Each row maps to exactly one
/// Component cell registered by `binding::register_qt_components`.
/// The mangled symbols follow the Itanium ABI (Qt is built with
/// `-fvisibility=default` for `staticMetaObject` so the symbols are
/// in the dynamic table) — mostly the
/// `_ZN<len><class>16staticMetaObjectE` shape for single-namespace
/// names.
///
/// QLabel covers BOTH the `image` Component (DDDD reuses QLabel +
/// pixmap because QImage is the data type, not the widget — see
/// components.md L577) AND a future plain-text label component, so
/// it appears once here and `binding.rs` references it for the
/// Image binding. The 11 classes:
///
///   QPushButton    — button
///   QLineEdit      — text-input
///   QListView      — list
///   QDateEdit      — date-picker
///   QDialog        — dialog
///   QLabel         — image (QLabel + pixmap)
///   QSlider        — slider
///   QComboBox      — combo-box
///   QProgressBar   — progress-bar
///   QCheckBox      — checkbox
///   QTabBar        — tab
pub const QT_WIDGET_TABLE: &[QtWidget] = &[
    QtWidget {
        class_name: "QPushButton",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN11QPushButton16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QLineEdit",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN9QLineEdit16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QListView",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN9QListView16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QDateEdit",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN9QDateEdit16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QDialog",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN7QDialog16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QLabel",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN6QLabel16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QSlider",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN7QSlider16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QComboBox",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN9QComboBox16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QProgressBar",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN12QProgressBar16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QCheckBox",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN9QCheckBox16staticMetaObjectE",
    },
    QtWidget {
        class_name: "QTabBar",
        library: QtLibrary::Widgets,
        mangled_symbol: "_ZN7QTabBar16staticMetaObjectE",
    },
];

/// Send-safe wrapper around the resolved `*const c_void` symbol
/// pointer. The pointer is either null (foundation-slice default)
/// or an address inside the loaded library's read-only data segment
/// (future loader extension). Either way, single-threaded kernel
/// boot — Send/Sync only exist for the static `Once`/`Mutex` bounds.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SymbolPtr(pub *const c_void);

unsafe impl Send for SymbolPtr {}
unsafe impl Sync for SymbolPtr {}

impl SymbolPtr {
    pub const fn null() -> Self {
        Self(core::ptr::null())
    }

    pub fn is_null(&self) -> bool {
        self.0.is_null()
    }
}

/// Resolved-symbols table, keyed by the unmangled `class_name` from
/// `QT_WIDGET_TABLE`. Populated once during `init`. Read by
/// `binding.rs` (to check whether a Symbol resolved cleanly — though
/// the cell registration is unconditional) and by `marshalling.rs`
/// (to find the QMetaObject pointer for a given widget class when
/// `setProperty`/`connect_signal` is invoked).
///
/// `BTreeMap` rather than a sized array so a future row addition
/// (e.g. QMenu, QCard) is a one-line table edit + a one-line
/// binding registration with no resize churn elsewhere.
static RESOLVED_SYMBOLS: Once<Mutex<BTreeMap<String, SymbolPtr>>> = Once::new();

/// Walk `QT_WIDGET_TABLE`, resolve each entry's `mangled_symbol`
/// against the matching loaded library, and record the result in
/// `RESOLVED_SYMBOLS`. On the foundation slice every result is
/// `SymbolPtr::null()` because `loader::dlsym` always returns null
/// when the library never loaded. Idempotent — `Once::call_once`
/// short-circuits a second call.
pub fn init() {
    RESOLVED_SYMBOLS.call_once(|| {
        let mut map: BTreeMap<String, SymbolPtr> = BTreeMap::new();
        for w in QT_WIDGET_TABLE {
            let handle = match w.library {
                QtLibrary::Core => loader::qt_core(),
                QtLibrary::Widgets => loader::qt_widgets(),
            };
            let raw = loader::dlsym(&handle, w.mangled_symbol);
            map.insert(w.class_name.to_string(), SymbolPtr(raw));
        }
        Mutex::new(map)
    });
}

/// Look up the resolved `*const QMetaObject` pointer for a widget
/// class by its unmangled name (`"QPushButton"`, `"QLineEdit"`, …).
/// Returns `None` when `init` hasn't run; returns `Some(SymbolPtr::null())`
/// on the foundation slice (the row was registered but the dlsym
/// returned null). Marshalling code differentiates the two cases by
/// checking `SymbolPtr::is_null` after unwrapping the Option.
pub fn resolved(class_name: &str) -> Option<SymbolPtr> {
    let map = RESOLVED_SYMBOLS.get()?;
    map.lock().get(class_name).copied()
}

/// Iterate the resolved-symbols table in declaration order. Returns
/// `Vec<(class_name, SymbolPtr)>` so callers (binding.rs at registration
/// time) don't have to hold the inner mutex while traversing.
///
/// Returns an empty vec when `init` hasn't run.
pub fn iter_resolved() -> alloc::vec::Vec<(String, SymbolPtr)> {
    match RESOLVED_SYMBOLS.get() {
        Some(m) => m.lock().iter().map(|(k, v)| (k.clone(), *v)).collect(),
        None => alloc::vec::Vec::new(),
    }
}

// ── Tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Foundation-slice: every row resolves to a null pointer
    /// because the libraries never loaded. This is the assertion
    /// that flips when the future loader extension lands real
    /// dlopen — at that point at least the widget classes whose
    /// libraries ARE present should resolve to non-null pointers.
    #[test]
    fn init_resolves_every_row_to_null_on_foundation_slice() {
        loader::init();
        init();
        for w in QT_WIDGET_TABLE {
            let p = resolved(w.class_name).expect("init populated row");
            assert!(p.is_null(), "{} resolved non-null on foundation slice", w.class_name);
        }
    }

    /// The widget table has the 11 entries DDDD's #485 declared.
    /// Locks the table size against accidental drift — adding a row
    /// here without updating binding.rs would emit a Symbol pointer
    /// for a class with no Component cell, which is harmless but
    /// silently wastes a registration cycle.
    #[test]
    fn widget_table_has_expected_count() {
        assert_eq!(QT_WIDGET_TABLE.len(), 11);
    }

    /// Spot-check the class-name → mangled-symbol mapping for the
    /// most-likely-to-be-resolved class (QPushButton). The mangling
    /// is `_ZN<len><class>16staticMetaObjectE`; a typo here would
    /// silently break the future dlopen path.
    #[test]
    fn qpushbutton_mangling_matches_itanium_abi() {
        let row = QT_WIDGET_TABLE
            .iter()
            .find(|w| w.class_name == "QPushButton")
            .expect("QPushButton in table");
        assert_eq!(row.mangled_symbol, "_ZN11QPushButton16staticMetaObjectE");
        assert_eq!(row.library, QtLibrary::Widgets);
    }

    /// `iter_resolved` returns the same set of class names as
    /// `QT_WIDGET_TABLE`. Catches a missing `Mutex::insert` if the
    /// init body is ever refactored.
    #[test]
    fn iter_resolved_yields_every_class_name() {
        loader::init();
        init();
        let resolved: alloc::collections::BTreeSet<String> = iter_resolved()
            .into_iter()
            .map(|(k, _)| k)
            .collect();
        for w in QT_WIDGET_TABLE {
            assert!(
                resolved.contains(w.class_name),
                "{} missing from resolved set",
                w.class_name
            );
        }
    }
}
