(
"The AST layer's cell accessors (Backus 13.3.4/13.3.5) as canonical definitions in INTERSECTION SOURCE (one tuple literal, normal Python and normal Rust verbatim; discipline in shared/theta.py). A cell is CELL,name,contents; fetch answers the top of the name's stack or the unaddressable mark; pop removes the top preserving deeper cells; store is push after pop, verbatim from 13.3.4; a definition is an ORDINARY cell, so DefineIn is store of the object (13.3.5) and definitions travel with the store. Every accessor is a builder applied to the cell NAME (DefineIn to the pair of name and object).",

DEF("ast:named",
    S4(A("CONS"), K(A("COMP")), K(A("eq")),
       S4(A("CONS"), K(A("CONS")), K(N(2)),
          S3(A("CONS"), K(A("CONST")), A("id"))))),

DEF("ast:Fetch",
    S5(A("CONS"), K(A("COND")),
       S4(A("CONS"), K(A("COMP")), K(A("null")),
          S3(A("COMP"), A("theta:Filter"), A("ast:named"))),
       K(S2(A("CONST"), A("#"))),
       S5(A("CONS"), K(A("COMP")), K(N(3)), K(N(1)),
          S3(A("COMP"), A("theta:Filter"), A("ast:named"))))),

DEF("ast:FetchPop",
    S5(A("CONS"), K(A("COND")),
       S4(A("CONS"), K(A("COMP")), K(A("eq")),
          S4(A("CONS"), K(A("CONS")), A("ast:Fetch"),
             K(S2(A("CONST"), A("#"))))),
       K(S2(A("CONST"), PHI())),
       A("ast:Fetch"))),

DEF("ast:Pop",
    S5(A("CONS"), K(A("COMP")), K(N(2)),
       S4(A("CONS"), K(A("WHILE")),
          K(S4(A("COMP"), A("not"), A("null"), N(3))),
          S5(A("CONS"), K(A("COND")),
             S4(A("CONS"), K(A("COMP")), K(A("and")),
                S4(A("CONS"), K(A("CONS")),
                   K(S3(A("COMP"), A("eq"),
                        S3(A("CONS"), N(1), S2(A("CONST"), A("F"))))),
                   S4(A("CONS"), K(A("COMP")), A("ast:named"),
                      K(S3(A("COMP"), N(1), N(3)))))),
             K(S4(A("CONS"), S2(A("CONST"), A("T")), N(2),
                  S3(A("COMP"), A("tl"), N(3)))),
             K(S4(A("CONS"), N(1),
                  S3(A("COMP"), A("apndr"),
                     S3(A("CONS"), N(2), S3(A("COMP"), N(1), N(3)))),
                  S3(A("COMP"), A("tl"), N(3)))))),
       K(S4(A("CONS"), S2(A("CONST"), A("F")), S2(A("CONST"), PHI()),
            A("id"))))),

DEF("ast:Purge",
    S3(A("COMP"), A("theta:Filter"),
       S4(A("CONS"), K(A("COMP")), K(A("not")), A("ast:named")))),

DEF("ast:Store",
    S4(A("CONS"), K(A("COMP")), K(A("apndl")),
       S4(A("CONS"), K(A("CONS")),
          S5(A("CONS"), K(A("CONS")), K(S2(A("CONST"), A("CELL"))),
             S3(A("CONS"), K(A("CONST")), A("id")), K(N(1))),
          S4(A("CONS"), K(A("COMP")), A("ast:Pop"), K(N(2)))))),

DEF("ast:DefineIn",
    S4(A("CONS"), K(A("COMP")),
       S3(A("COMP"), A("ast:Store"), N(1)),
       S4(A("CONS"), K(A("CONS")),
          S3(A("CONS"), K(A("CONST")), N(2)),
          K(A("id"))))),
)
