(
"Constraint families as canonical definitions in INTERSECTION SOURCE (one tuple literal, normal Python and normal Rust verbatim; see shared/theta.py for the discipline). The closed families are references into theta; uniqueness is a higher-order builder applied to the key roles, and exclusion is uniqueness applied to the entity role through the apply primitive (dynamic application, the base's own higher-order mechanism).",

DEF("constraints:mandatory", A("theta:setminus")),

DEF("constraints:subset", A("theta:setminus")),

DEF("constraints:inclusive_or", A("theta:setminus")),

DEF("constraints:equality",
    S3(A("COMP"), A("cat"),
       S3(A("CONS"),
          S3(A("COMP"), A("theta:setminus"), S3(A("CONS"), N(1), N(2))),
          S3(A("COMP"), A("theta:setminus"), S3(A("CONS"), N(2), N(1)))))),

DEF("constraints:uniqueness",
    S6(A("CONS"), K(A("COMP")),
       K(S2(A("ALPHA"), N(1))),
       S3(A("COMP"), A("theta:Filter"),
          S6(A("CONS"), K(A("COMP")), K(A("not")), K(A("null")),
             S3(A("COMP"), A("theta:Filter"),
                S4(A("CONS"), K(A("COMP")), K(A("and")),
                   S4(A("CONS"), K(A("CONS")),
                      S4(A("CONS"), K(A("COMP")), K(A("eq")),
                         S4(A("CONS"), K(A("CONS")),
                            S4(A("CONS"), K(A("COMP")), A("theta:selrow"), K(N(1))),
                            S4(A("CONS"), K(A("COMP")), A("theta:selrow"), K(N(2))))),
                      K(S3(A("COMP"), A("not"), A("eq")))))),
             K(A("distl")))),
       K(A("distr")),
       K(S3(A("CONS"), A("id"), A("id"))))),

DEF("constraints:exclusion",
    S3(A("COMP"), A("apply"),
       S3(A("CONS"),
          S3(A("COMP"), A("constraints:uniqueness"), K(S1(N(1)))),
          A("id")))),

DEF("constraints:value_enumeration",
    S3(A("COMP"), A("theta:Filter"),
       S5(A("CONS"), K(A("COMP")), K(A("not")), K(A("theta:member")),
          S4(A("CONS"), K(A("CONS")), N(1),
             S3(A("CONS"), K(A("CONST")), N(2)))))),

DEF("constraints:value_range",
    S3(A("COMP"), A("theta:Filter"),
       S4(A("COND"), S3(A("COMP"), A("null"), N(2)),
          S4(A("COND"), S3(A("COMP"), A("null"), N(3)),
             K(S2(A("CONST"), A("F"))),
             A("constraints:vr_hi")),
          S4(A("COND"), S3(A("COMP"), A("null"), N(3)),
             A("constraints:vr_lo"),
             S4(A("CONS"), K(A("COMP")), K(A("or")),
                S4(A("CONS"), K(A("CONS")),
                   A("constraints:vr_lo"), A("constraints:vr_hi"))))))),

DEF("constraints:vr_lo",
    S4(A("CONS"), K(A("COMP")),
       S4(A("COND"), S4(A("COMP"), N(2), N(2), A("id")), K(A("le")), K(A("lt"))),
       S4(A("CONS"), K(A("CONS")), N(1),
          S3(A("CONS"), K(A("CONST")), S3(A("COMP"), N(1), N(2)))))),

DEF("constraints:vr_hi",
    S4(A("CONS"), K(A("COMP")),
       S4(A("COND"), S4(A("COMP"), N(2), N(3), A("id")), K(A("ge")), K(A("gt"))),
       S4(A("CONS"), K(A("CONS")), N(1),
          S3(A("CONS"), K(A("CONST")), S3(A("COMP"), N(1), N(3)))))),

DEF("constraints:frequency",
    S6(A("CONS"), K(A("COMP")),
       K(S2(A("ALPHA"), N(1))),
       S3(A("COMP"), A("theta:Filter"),
          S4(A("COND"), S3(A("COMP"), A("null"), N(2)),
             S4(A("COND"), S3(A("COMP"), A("null"), N(3)),
                K(S2(A("CONST"), A("F"))),
                A("constraints:fq_hi")),
             S4(A("COND"), S3(A("COMP"), A("null"), N(3)),
                A("constraints:fq_lo"),
                S4(A("CONS"), K(A("COMP")), K(A("or")),
                   S4(A("CONS"), K(A("CONS")),
                      A("constraints:fq_lo"), A("constraints:fq_hi")))))),
       K(A("distr")),
       K(S3(A("CONS"), A("id"), A("id"))))),

DEF("constraints:fq_cnt",
    S5(A("CONS"), K(A("COMP")), K(A("length")),
       S3(A("COMP"), A("theta:Filter"),
          S4(A("CONS"), K(A("COMP")), K(A("eq")),
             S4(A("CONS"), K(A("CONS")),
                S4(A("CONS"), K(A("COMP")),
                   S3(A("COMP"), A("theta:selrow"), N(1)), K(N(1))),
                S4(A("CONS"), K(A("COMP")),
                   S3(A("COMP"), A("theta:selrow"), N(1)), K(N(2)))))),
       K(A("distl")))),

DEF("constraints:fq_lo",
    S4(A("CONS"), K(A("COMP")), K(A("lt")),
       S4(A("CONS"), K(A("CONS")), A("constraints:fq_cnt"),
          S3(A("CONS"), K(A("CONST")), S3(A("COMP"), N(1), N(2)))))),

DEF("constraints:fq_hi",
    S4(A("CONS"), K(A("COMP")), K(A("gt")),
       S4(A("CONS"), K(A("CONS")), A("constraints:fq_cnt"),
          S3(A("CONS"), K(A("CONST")), S3(A("COMP"), N(1), N(3)))))),

DEF("constraints:exclusive_or",
    S3(A("COMP"), A("cat"),
       S3(A("CONS"),
          S3(A("COMP"), A("theta:setminus"),
             S3(A("CONS"), N(1),
                S3(A("COMP"),
                   S3(A("COMP"), A("theta:dedup"),
                      S2(A("ALPHA"), S2(A("CONS"), N(1)))),
                   N(2)))),
          S4(A("COMP"),
             S3(A("COMP"), A("theta:dedup"),
                S2(A("ALPHA"), S2(A("CONS"), N(1)))),
             A("constraints:exclusion"), N(2))))),

DEF("constraints:pop_of",
    S4(A("CONS"), K(A("COMP")), A("ast:FetchPop"), K(N(2)))),

DEF("constraints:scoped_subset",
    S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
       S4(A("CONS"), K(A("CONS")), K(N(1)), A("constraints:pop_of")))),

DEF("constraints:scoped_mandatory_entities",
    S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
       S4(A("CONS"), K(A("CONS")),
          S4(A("CONS"), K(A("COMP")), K(A("theta:proj1")),
             A("constraints:pop_of")),
          K(S3(A("COMP"), A("theta:proj1"), N(1)))))),

DEF("constraints:scoped_mandatory_facts",
    S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
       S4(A("CONS"), K(A("CONS")),
          K(S3(A("COMP"), A("theta:proj1"), N(1))),
          S4(A("CONS"), K(A("COMP")), K(A("theta:proj1")),
             A("constraints:pop_of"))))),

DEF("constraints:scoped_equality_side",
    S4(A("CONS"), K(A("COMP")), K(A("cat")),
       S4(A("CONS"), K(A("CONS")),
          S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
             S4(A("CONS"), K(A("CONS")), K(N(1)), A("constraints:pop_of"))),
          S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
             S4(A("CONS"), K(A("CONS")), A("constraints:pop_of"), K(N(1))))))),

DEF("constraints:part_one",
    S4(A("CONS"), K(A("COMP")),
       S3(A("CONS"), K(A("ALPHA")),
          S4(A("CONS"), K(A("CONS")), K(N(1)),
             S3(A("CONS"), K(A("CONST")), N(2)))),
       S4(A("COND"), A("eq"), K(N(1)),
          S4(A("CONS"), K(A("COMP")),
             S3(A("COMP"), A("ast:FetchPop"), N(2)), K(N(2)))))),

DEF("constraints:participation",
    S4(A("CONS"), K(A("COMP")), K(A("theta:flatten")),
       S3(A("COMP"), A("apndl"),
          S3(A("CONS"), K(A("CONS")),
             S4(A("COMP"), S2(A("ALPHA"), A("constraints:part_one")),
                A("distl"), S3(A("CONS"), N(2), N(1))))))),

DEF("constraints:scoped_exclusion",
    S4(A("CONS"), K(A("COMP")), K(A("constraints:exclusion")),
       A("constraints:participation"))),

DEF("constraints:scoped_inclusive_or",
    S4(A("CONS"), K(A("COMP")), K(A("theta:setminus")),
       S4(A("CONS"), K(A("CONS")),
          S4(A("CONS"), K(A("COMP")), K(A("theta:proj1")),
             S4(A("CONS"), K(A("COMP")),
                S3(A("COMP"), A("ast:FetchPop"), N(1)), K(N(2)))),
          S4(A("CONS"), K(A("COMP")), K(A("theta:proj1")),
             S4(A("CONS"), K(A("COMP")),
                S3(A("COMP"), A("constraints:participation"),
                   S3(A("CONS"), N(2), N(3))),
                K(A("id"))))))),

DEF("constraints:scoped_exclusive_or",
    S4(A("CONS"), K(A("COMP")), K(A("constraints:exclusive_or")),
       S4(A("CONS"), K(A("CONS")),
          S4(A("CONS"), K(A("COMP")),
             S3(A("COMP"), A("ast:FetchPop"), N(1)), K(N(2))),
          S4(A("CONS"), K(A("COMP")),
             S3(A("COMP"), A("constraints:participation"),
                S3(A("CONS"), N(2), N(3))),
             K(A("id")))))),

DEF("theta:natjoin1",
    S3(A("COMP"), A("apply"),
       S3(A("CONS"),
          S3(A("COMP"), A("theta:NatJoin"), S2(A("CONST"), N(1))),
          A("id")))),

DEF("constraints:scoped_external_uniqueness",
    S4(A("CONS"), K(A("COMP")),
       S4(A("CONS"), K(A("COMP")), K(A("apply")),
          S4(A("CONS"), K(A("CONS")),
             S4(A("CONS"), K(A("COMP")), K(A("constraints:uniqueness")),
                S3(A("CONS"), K(A("CONST")), N(2))),
             K(A("id")))),
       S4(A("CONS"), K(A("COMP")), K(A("theta:natjoin1")),
          S4(A("CONS"), K(A("CONS")), K(N(1)),
             S4(A("CONS"), K(A("COMP")),
                S3(A("COMP"), A("ast:FetchPop"), N(1)), K(N(2)))))))
)
