(
"The cross-host differential's case table in INTERSECTION SOURCE: each case is DEF(name, S2(expr, operand)) and every host reduces expr applied to operand, printing name=result for the harness to compare byte-for-byte. The cases pin the semantics of record (python/delta.py): selectors and their range edge, the sequence prims and their bottom edges, NATEQ, coercion in arithmetic and comparison (int-first then float, lexical only for non-numeric string pairs), the controlling forms including the WHILE countdown, and transpose. Fuel cases stay host-side (fuel is a host policy, not canon).",

DEF("case:sel2", S2(N(2), S3(A("x"), A("y"), A("z")))),
DEF("case:sel-range", S2(N(5), S2(A("x"), A("y")))),
DEF("case:tl", S2(A("tl"), S3(A("x"), A("y"), A("z")))),
DEF("case:tl-atom", S2(A("tl"), A("atomic"))),
DEF("case:atom-t", S2(A("atom"), A("x"))),
DEF("case:atom-f", S2(A("atom"), S2(A("x"), A("y")))),
DEF("case:null-t", S2(A("null"), PHI())),
DEF("case:null-f", S2(A("null"), S1(A("x")))),
DEF("case:eq-nateq", S2(A("eq"), S2(N(1), A("1")))),
DEF("case:eq-same", S2(A("eq"), S2(A("a"), A("a")))),
DEF("case:add-int", S2(A("+"), S2(N(2), N(3)))),
DEF("case:add-lex", S2(A("+"), S2(A("120"), A("30")))),
DEF("case:add-bad", S2(A("+"), S2(A("a"), A("3")))),
DEF("case:mul-lex", S2(A("*"), S2(A("4"), N(5)))),
DEF("case:lt-coerce", S2(A("lt"), S2(A("9"), A("10")))),
DEF("case:lt-mixed", S2(A("lt"), S2(N(4997), A("11000")))),
DEF("case:ge-multi", S2(A("ge"), S2(A("305"), A("1190")))),
DEF("case:lt-words", S2(A("lt"), S2(A("apple"), A("pear")))),
DEF("case:apndl", S2(A("apndl"), S2(A("h"), S2(A("a"), A("b"))))),
DEF("case:apndr", S2(A("apndr"), S2(S2(A("a"), A("b")), A("t")))),
DEF("case:distl", S2(A("distl"), S2(A("k"), S2(A("p"), A("q"))))),
DEF("case:distr", S2(A("distr"), S2(S2(A("p"), A("q")), A("k")))),
DEF("case:cat", S2(A("cat"), S2(S2(A("a"), A("b")), S1(A("c"))))),
DEF("case:reverse", S2(A("reverse"), S3(N(1), N(2), N(3)))),
DEF("case:rotl", S2(A("rotl"), S3(N(1), N(2), N(3)))),
DEF("case:rotr", S2(A("rotr"), S3(N(1), N(2), N(3)))),
DEF("case:oner", S2(A("1r"), S3(N(1), N(2), N(3)))),
DEF("case:tlr-phi", S2(A("tlr"), PHI())),
DEF("case:trans", S2(A("trans"), S3(S2(N(1), N(2)), S2(N(3), N(4)), S2(N(5), N(6))))),
DEF("case:trans-ragged", S2(A("trans"), S2(S2(N(1), N(2)), S1(N(3))))),
DEF("case:div", S2(A("div"), S2(N(4), N(2)))),
DEF("case:div-zero", S2(A("div"), S2(N(4), N(0)))),
DEF("case:comp", S2(S3(A("COMP"), A("tl"), A("tl")), S3(A("a"), A("b"), A("c")))),
DEF("case:cons", S2(S3(A("CONS"), N(2), N(1)), S2(A("p"), A("q")))),
DEF("case:const", S2(S2(A("CONST"), A("k")), A("ignored"))),
DEF("case:cond", S2(S4(A("COND"), A("null"), S2(A("CONST"), A("empty")), S2(A("CONST"), A("full"))), PHI())),
DEF("case:alpha", S2(S2(A("ALPHA"), A("tl")), S2(S2(A("a"), A("b")), S2(A("c"), A("d"))))),
DEF("case:insert-max", S2(S2(A("INSERT"), A("system:max2")), S4(A("2"), A("19"), A("7"), A("4")))),
DEF("case:while-count", S2(S3(A("WHILE"), S3(A("COMP"), A("gt"), S3(A("CONS"), A("id"), S2(A("CONST"), N(0)))), S3(A("COMP"), A("-"), S3(A("CONS"), A("id"), S2(A("CONST"), N(1))))), N(5))),
DEF("case:bu", S2(S3(A("BU"), A("+"), N(10)), N(7)))
)
