(
"The AREST command pipeline's canonical definitions in INTERSECTION SOURCE (one tuple literal, normal Python and normal Rust verbatim; discipline in shared/intersection.md). validate_S per Def. Command and Def. Violation: from the record of local constraints, an optional alethic subset, scoped constraints, and an optional scoped-alethic subset, build P,V,flag over P,D. V unions every family; only the ALETHIC subset raises the commit-blocking flag, deontic families warn and commit. An absent alethic slot defaults to the whole family; a provided-but-empty one is deliberately deontic. Local constraints compose with the target-population selector; scoped ones consume the pair whole.",

DEF("system:viols",
    S4(A("COND"), A("null"),
       K(S2(A("CONST"), PHI())),
       S4(A("CONS"), K(A("COMP")), K(A("theta:flatten")), A("theta:selrow")))),

DEF("system:wrap_local",
    S4(A("CONS"), K(A("COMP")), A("id"), K(N(1)))),

DEF("system:validate_of",
    S5(A("CONS"), K(A("CONS")),
       K(N(1)),
       S3(A("COMP"), A("system:viols"),
          S3(A("COMP"), A("cat"),
             S3(A("CONS"),
                S3(A("COMP"), S2(A("ALPHA"), A("system:wrap_local")), N(1)),
                N(3)))),
       S5(A("CONS"), K(A("COMP")), K(A("not")), K(A("null")),
          S3(A("COMP"), A("system:viols"),
             S3(A("COMP"), A("cat"),
                S3(A("CONS"),
                   S4(A("COND"), S3(A("COMP"), A("null"), N(2)),
                      S3(A("COMP"), S2(A("ALPHA"), A("system:wrap_local")), N(1)),
                      S3(A("COMP"), S2(A("ALPHA"), A("system:wrap_local")),
                         S3(A("COMP"), N(1), N(2)))),
                   S4(A("COND"), S3(A("COMP"), A("null"), N(4)),
                      N(3),
                      S3(A("COMP"), N(1), N(4))))))))),

DEF("system:cmp_filter_lit",
    S4(A("CONS"), K(A("COMP")), N(1),
       S4(A("CONS"), K(A("CONS")), N(2),
          S3(A("CONS"), K(A("CONST")), N(3))))),

DEF("system:cmp_filter_col",
    S4(A("CONS"), K(A("COMP")), N(1),
       S4(A("CONS"), K(A("CONS")), N(2), N(3)))),

DEF("system:compile_rule",
    S4(A("CONS"), K(A("COMP")),
       S3(A("COMP"), A("apply"),
          S3(A("CONS"), K(A("theta:Project")), N(2))),
       S3(A("COMP"),
          S2(A("INSERT"),
             S4(A("CONS"), K(A("COMP")),
                S3(A("COMP"), A("apply"),
                   S3(A("CONS"), K(A("theta:Filter")), N(1))),
                N(2))),
          S3(A("COMP"), A("apndr"),
             S3(A("CONS"), N(3),
                S4(A("COMP"), N(1),
                   S3(A("WHILE"),
                      S4(A("COMP"), A("not"), A("null"), N(3)),
                      S4(A("CONS"),
                         S4(A("CONS"), K(A("COMP")),
                            S4(A("COND"),
                               S3(A("COMP"), A("null"),
                                  S4(A("COMP"), N(3), N(1), N(3))),
                               S3(A("COMP"), A("apply"),
                                  S3(A("CONS"), K(A("theta:NatJoin")), N(2))),
                               S3(A("COMP"), A("apply"),
                                  S3(A("CONS"), K(A("theta:JoinOn")),
                                     S4(A("COMP"), N(3), N(1), N(3))))),
                            S4(A("CONS"), K(A("CONS")), N(1),
                               S3(A("COMP"), A("apply"),
                                  S3(A("CONS"), K(A("ast:FetchPop")),
                                     S4(A("COMP"), N(1), N(1), N(3)))))),
                         S4(A("COND"),
                            S3(A("COMP"), A("null"),
                               S4(A("COMP"), N(3), N(1), N(3))),
                            S3(A("COMP"), A("+"),
                               S3(A("CONS"), N(2),
                                  S3(A("COMP"), A("-"),
                                     S3(A("CONS"),
                                        S4(A("COMP"), N(2), N(1), N(3)),
                                        K(N(1)))))),
                            S3(A("COMP"), A("+"),
                               S3(A("CONS"), N(2),
                                  S3(A("COMP"), A("length"),
                                     S3(A("COMP"), N(2),
                                        S4(A("COMP"), N(3), N(1), N(3))))))),
                         S3(A("COMP"), A("tl"), N(3)))),
                   S4(A("CONS"),
                      S3(A("COMP"), A("apply"),
                         S3(A("CONS"), K(A("ast:FetchPop")),
                            S4(A("COMP"), N(1), N(1), N(1)))),
                      S4(A("COMP"), N(2), N(1), N(1)),
                      S3(A("COMP"), A("tl"), N(1))))))))),

DEF("system:compile_rule_delta",
    S4(A("CONS"),
       K(A("COMP")),
       S3(A("COMP"), A("apply"), S3(A("CONS"), K(A("theta:Project")), N(2))),
       S3(A("COMP"),
          S2(A("INSERT"),
             S4(A("CONS"),
                K(A("COMP")),
                S3(A("COMP"), A("apply"), S3(A("CONS"), K(A("theta:Filter")), N(1))),
                N(2))),
          S3(A("COMP"),
             A("apndr"),
             S3(A("CONS"),
                N(3),
                S4(A("COMP"),
                   N(1),
                   S3(A("WHILE"),
                      S4(A("COMP"), A("not"), A("null"), N(3)),
                      S6(A("CONS"),
                         S4(A("CONS"),
                            K(A("COMP")),
                            S4(A("COND"),
                               S3(A("COMP"), A("null"), S4(A("COMP"), N(3), N(1), N(3))),
                               S3(A("COMP"),
                                  A("apply"),
                                  S3(A("CONS"), K(A("theta:NatJoin")), N(2))),
                               S3(A("COMP"),
                                  A("apply"),
                                  S3(A("CONS"),
                                     K(A("theta:JoinOn")),
                                     S4(A("COMP"), N(3), N(1), N(3))))),
                            S4(A("CONS"),
                               K(A("CONS")),
                               N(1),
                               S4(A("COND"),
                                  S3(A("COMP"), A("eq"), S3(A("CONS"), N(4), N(5))),
                                  K(N(1)),
                                  S4(A("CONS"),
                                     K(A("COMP")),
                                     S3(A("COMP"),
                                        A("apply"),
                                        S3(A("CONS"),
                                           K(A("ast:FetchPop")),
                                           S4(A("COMP"), N(1), N(1), N(3)))),
                                     K(N(2)))))),
                         S4(A("COND"),
                            S3(A("COMP"), A("null"), S4(A("COMP"), N(3), N(1), N(3))),
                            S3(A("COMP"),
                               A("+"),
                               S3(A("CONS"),
                                  N(2),
                                  S3(A("COMP"),
                                     A("-"),
                                     S3(A("CONS"), S4(A("COMP"), N(2), N(1), N(3)), K(N(1)))))),
                            S3(A("COMP"),
                               A("+"),
                               S3(A("CONS"),
                                  N(2),
                                  S3(A("COMP"),
                                     A("length"),
                                     S3(A("COMP"), N(2), S4(A("COMP"), N(3), N(1), N(3))))))),
                         S3(A("COMP"), A("tl"), N(3)),
                         S3(A("COMP"), A("+"), S3(A("CONS"), N(4), K(N(1)))),
                         N(5))),
                   S6(A("CONS"),
                      S4(A("COND"),
                         S3(A("COMP"), A("eq"), S3(A("CONS"), K(N(1)), N(4))),
                         K(N(1)),
                         S4(A("CONS"),
                            K(A("COMP")),
                            S3(A("COMP"),
                               A("apply"),
                               S3(A("CONS"),
                                  K(A("ast:FetchPop")),
                                  S4(A("COMP"), N(1), N(1), N(1)))),
                            K(N(2)))),
                      S4(A("COMP"), N(2), N(1), N(1)),
                      S3(A("COMP"), A("tl"), N(1)),
                      K(N(2)),
                      N(4)))))))),

DEF("system:agg_psel1",
    S4(A("CONS"), K(A("COMP")), A("id"), K(N(1)))),

DEF("system:agg_psel2",
    S4(A("CONS"), K(A("COMP")), A("id"), K(N(2)))),

DEF("system:compile_agg_rule",
    S4(A("CONS"),
       K(A("COMP")),
       S6(A("CONS"),
          K(A("COMP")),
          K(A("theta:dedup")),
          S3(A("CONS"),
             K(A("ALPHA")),
             S3(A("COMP"),
                A("apndl"),
                S3(A("CONS"),
                   K(A("CONS")),
                   S3(A("COMP"),
                      A("apndr"),
                      S3(A("CONS"),
                         S3(A("COMP"), S2(A("ALPHA"), A("system:agg_psel1")), N(2)),
                         S4(A("CONS"),
                            K(A("COMP")),
                            S3(A("CONS"),
                               K(A("INSERT")),
                               S5(A("CONS"),
                                  K(A("COND")),
                                  S4(A("CONS"),
                                     K(A("COMP")),
                                     S4(A("COND"),
                                        S3(A("COMP"), A("eq"), S3(A("CONS"), N(4), K(A("min")))),
                                        K(A("le")),
                                        K(A("ge"))),
                                     K(S3(A("CONS"), N(1), N(2)))),
                                  K(N(1)),
                                  K(N(2)))),
                            S4(A("CONS"),
                               K(A("COMP")),
                               S3(A("CONS"),
                                  K(A("ALPHA")),
                                  S4(A("CONS"), K(A("COMP")), N(3), K(N(1)))),
                               S5(A("CONS"),
                                  K(A("COMP")),
                                  S3(A("COMP"),
                                     A("apply"),
                                     S3(A("CONS"),
                                        K(A("theta:Filter")),
                                        S4(A("CONS"),
                                           K(A("COMP")),
                                           K(A("eq")),
                                           S4(A("CONS"),
                                              K(A("CONS")),
                                              S3(A("COMP"),
                                                 A("apndl"),
                                                 S3(A("CONS"),
                                                    K(A("CONS")),
                                                    S3(A("COMP"),
                                                       S2(A("ALPHA"), A("system:agg_psel1")),
                                                       N(2)))),
                                              S3(A("COMP"),
                                                 A("apndl"),
                                                 S3(A("CONS"),
                                                    K(A("CONS")),
                                                    S3(A("COMP"),
                                                       S2(A("ALPHA"), A("system:agg_psel2")),
                                                       N(2)))))))),
                                  K(A("distr")),
                                  K(S3(A("CONS"), N(2), N(1))))))))))),
          K(A("distr")),
          K(S3(A("CONS"), A("id"), A("id")))),
       S3(A("COMP"),
          S2(A("INSERT"),
             S4(A("CONS"),
                K(A("COMP")),
                S3(A("COMP"), A("apply"), S3(A("CONS"), K(A("theta:Filter")), N(1))),
                N(2))),
          S3(A("COMP"),
             A("apndr"),
             S3(A("CONS"),
                N(5),
                S4(A("COMP"),
                   N(1),
                   S3(A("WHILE"),
                      S4(A("COMP"), A("not"), A("null"), N(3)),
                      S4(A("CONS"),
                         S4(A("CONS"),
                            K(A("COMP")),
                            S4(A("COND"),
                               S3(A("COMP"), A("null"), S4(A("COMP"), N(3), N(1), N(3))),
                               S3(A("COMP"),
                                  A("apply"),
                                  S3(A("CONS"), K(A("theta:NatJoin")), N(2))),
                               S3(A("COMP"),
                                  A("apply"),
                                  S3(A("CONS"),
                                     K(A("theta:JoinOn")),
                                     S4(A("COMP"), N(3), N(1), N(3))))),
                            S4(A("CONS"),
                               K(A("CONS")),
                               N(1),
                               S3(A("COMP"),
                                  A("apply"),
                                  S3(A("CONS"),
                                     K(A("ast:FetchPop")),
                                     S4(A("COMP"), N(1), N(1), N(3)))))),
                         S4(A("COND"),
                            S3(A("COMP"), A("null"), S4(A("COMP"), N(3), N(1), N(3))),
                            S3(A("COMP"),
                               A("+"),
                               S3(A("CONS"),
                                  N(2),
                                  S3(A("COMP"),
                                     A("-"),
                                     S3(A("CONS"), S4(A("COMP"), N(2), N(1), N(3)), K(N(1)))))),
                            S3(A("COMP"),
                               A("+"),
                               S3(A("CONS"),
                                  N(2),
                                  S3(A("COMP"),
                                     A("length"),
                                     S3(A("COMP"), N(2), S4(A("COMP"), N(3), N(1), N(3))))))),
                         S3(A("COMP"), A("tl"), N(3)))),
                   S4(A("CONS"),
                      S3(A("COMP"),
                         A("apply"),
                         S3(A("CONS"), K(A("ast:FetchPop")), S4(A("COMP"), N(1), N(1), N(1)))),
                      S4(A("COMP"), N(2), N(1), N(1)),
                      S3(A("COMP"), A("tl"), N(1))))))))),
)
