/**
 * 3NF DDL for the GraphDL core metamodel.
 *
 * Derived from FORML2 readings in readings/core.md + readings/organizations.md.
 * These tables live in the GraphDL DO's SQLite database.
 *
 * Conventions:
 * - Snake_case table and column names
 * - id TEXT PRIMARY KEY (generated by @dotdo/db's generateEntityId)
 * - Foreign keys as _id suffixes
 * - created_at / updated_at timestamps on every table
 * - version INTEGER for optimistic concurrency
 */
export const METAMODEL_DDL: string[] = [
  // ── Organizations & Access Control ──────────────────────────────────
  `CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE TABLE IF NOT EXISTS org_memberships (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1,
    UNIQUE(user_email, organization_id)
  )`,

  `CREATE INDEX IF NOT EXISTS idx_org_memberships_email ON org_memberships(user_email)`,
  `CREATE INDEX IF NOT EXISTS idx_org_memberships_org ON org_memberships(organization_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_org_one_owner ON org_memberships(organization_id) WHERE role = 'owner'`,

  `CREATE TABLE IF NOT EXISTS apps (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT,
    organization_id TEXT REFERENCES organizations(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_apps_slug ON apps(slug)`,
  `CREATE INDEX IF NOT EXISTS idx_apps_org ON apps(organization_id)`,

  `CREATE TABLE IF NOT EXISTS domains (
    id TEXT PRIMARY KEY,
    domain_slug TEXT NOT NULL UNIQUE,
    name TEXT,
    app_id TEXT REFERENCES apps(id),
    organization_id TEXT REFERENCES organizations(id),
    visibility TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_domains_org ON domains(organization_id)`,
  `CREATE INDEX IF NOT EXISTS idx_domains_slug ON domains(domain_slug)`,
  // idx_domains_app is created in do.ts migrations (after ALTER TABLE adds app_id column)

  // ── Core Metamodel ──────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS nouns (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    object_type TEXT NOT NULL DEFAULT 'entity' CHECK (object_type IN ('entity', 'value')),
    domain_id TEXT REFERENCES domains(id),
    super_type_id TEXT REFERENCES nouns(id),
    plural TEXT,
    value_type TEXT,
    format TEXT,
    enum_values TEXT,
    minimum REAL,
    maximum REAL,
    pattern TEXT,
    prompt_text TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_nouns_domain ON nouns(domain_id)`,
  `CREATE INDEX IF NOT EXISTS idx_nouns_name_domain ON nouns(name, domain_id)`,

  `CREATE TABLE IF NOT EXISTS graph_schemas (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    domain_id TEXT REFERENCES domains(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_graph_schemas_domain ON graph_schemas(domain_id)`,

  `CREATE TABLE IF NOT EXISTS readings (
    id TEXT PRIMARY KEY,
    text TEXT NOT NULL,
    graph_schema_id TEXT REFERENCES graph_schemas(id),
    domain_id TEXT REFERENCES domains(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_readings_domain ON readings(domain_id)`,
  `CREATE INDEX IF NOT EXISTS idx_readings_schema ON readings(graph_schema_id)`,
  `CREATE INDEX IF NOT EXISTS idx_readings_text_domain ON readings(text, domain_id)`,

  `CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    reading_id TEXT REFERENCES readings(id),
    noun_id TEXT REFERENCES nouns(id),
    graph_schema_id TEXT REFERENCES graph_schemas(id),
    role_index INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_roles_reading ON roles(reading_id)`,
  `CREATE INDEX IF NOT EXISTS idx_roles_schema ON roles(graph_schema_id)`,

  `CREATE TABLE IF NOT EXISTS constraints (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('UC', 'MC', 'SS', 'XC', 'EQ', 'OR', 'XO')),
    modality TEXT NOT NULL DEFAULT 'Alethic' CHECK (modality IN ('Alethic', 'Deontic')),
    domain_id TEXT REFERENCES domains(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_constraints_domain ON constraints(domain_id)`,

  `CREATE TABLE IF NOT EXISTS constraint_spans (
    id TEXT PRIMARY KEY,
    constraint_id TEXT NOT NULL REFERENCES constraints(id),
    role_id TEXT NOT NULL REFERENCES roles(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    version INTEGER NOT NULL DEFAULT 1
  )`,

  `CREATE INDEX IF NOT EXISTS idx_constraint_spans_constraint ON constraint_spans(constraint_id)`,
  `CREATE INDEX IF NOT EXISTS idx_constraint_spans_role ON constraint_spans(role_id)`,
]
